targets := delete_files
targets += sum_int
targets += __VA_ARGS__
targets += va_arg
targets += va_start
targets += va_copy

CFLAGS :=

include ../../template/main.mk

delete_files: delete_files.o
sum_int: sum_int.o
__VA_ARGS__: __VA_ARGS__.o
va_arg: va_arg.o
va_start: va_start.o
va_copy: va_copy.o
