/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class poll */

#ifndef _Included_poll
#define _Included_poll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     poll
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_poll_init
  (JNIEnv *, jclass);

/*
 * Class:     poll
 * Method:    poll
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_poll_poll
  (JNIEnv *, jclass, jint);

/*
 * Class:     poll
 * Method:    echo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_poll_echo
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
