# This is configuration of fstabd.
#
# Check Mountpoint in fstab file
# Mount points that must exist can be added to this array, like /boot/efi
# below, the syntax follows the bash script.
declare -a FSTABD_MOUNTPOINTS

#  Root, it seems that the detection of the '/' root is necessary. If you
#  want to delete the detection of the root mount point, then you are free.
FSTABD_MOUNTPOINTS+=( / )

#  EFI
if [[ $(uname -r) == aarch64 ]] || [[ -d /sys/firmware/efi/ ]]; then
	FSTABD_MOUNTPOINTS+=( /boot/efi )
fi
