include ../../tlbuild.mk


sub-dir := auxv
sub-dir += time
sub-dir += timeb

include ../../template/subdir-header.mk

.PHONY: build
build: $(sub-dir-build)

.PHONY: clean
clean: $(sub-dir-clean)

include ../../template/subdir-footer.mk
