target-y := wchar_t
target-y += iswctype
target-y += wcstol
target-y += demo-1

CFLAGS :=
CFLAGS += -pthread

include ../../template/main.mk

iswctype: iswctype.o
wchar_t: wchar_t.o
wcstol: wcstol.o
demo-1: demo-1.o
