target-y := semaphore
target-y += latency
target-y += pthread-semaphore

CFLAGS :=
CFLAGS += -lpthread

include main.mk

semaphore: semaphore.o
latency: latency.o
pthread-semaphore: pthread-semaphore.o
