// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
/* Copyright (C) 2025-2026 Rong Tao */
/**
 * refs
 * - https://docs.nvidia.com/cuda/curand/group__HOST.html
 */
#ifndef __CUDA_ADAPTER_RAND_H
#define __CUDA_ADAPTER_RAND_H 1

#include "wrapper_defs.h"

#define curandStatus_t __cu(randStatus_t)
#define CURAND_STATUS_SUCCESS __CU(RAND_STATUS_SUCCESS)
#define CURAND_STATUS_SUCCESS __CU(RAND_STATUS_SUCCESS)
#define CURAND_STATUS_VERSION_MISMATCH __CU(RAND_STATUS_VERSION_MISMATCH)
#define CURAND_STATUS_NOT_INITIALIZED __CU(RAND_STATUS_NOT_INITIALIZED)
#define CURAND_STATUS_ALLOCATION_FAILED __CU(RAND_STATUS_ALLOCATION_FAILED)
#define CURAND_STATUS_TYPE_ERROR __CU(RAND_STATUS_TYPE_ERROR)
#define CURAND_STATUS_OUT_OF_RANGE __CU(RAND_STATUS_OUT_OF_RANGE)
#define CURAND_STATUS_LENGTH_NOT_MULTIPLE __CU(RAND_STATUS_LENGTH_NOT_MULTIPLE)
#define CURAND_STATUS_DOUBLE_PRECISION_REQUIRED \
	__CU(RAND_STATUS_DOUBLE_PRECISION_REQUIRED)
#define CURAND_STATUS_LAUNCH_FAILURE __CU(RAND_STATUS_LAUNCH_FAILURE)
#define CURAND_STATUS_PREEXISTING_FAILURE __CU(RAND_STATUS_PREEXISTING_FAILURE)
#define CURAND_STATUS_INITIALIZATION_FAILED \
	__CU(RAND_STATUS_INITIALIZATION_FAILED)
#define CURAND_STATUS_ARCH_MISMATCH __CU(RAND_STATUS_ARCH_MISMATCH)
#define CURAND_STATUS_INTERNAL_ERROR __CU(RAND_STATUS_INTERNAL_ERROR)
#define CURAND_STATUS_NOT_IMPLEMENTED __CU(RAND_STATUS_NOT_IMPLEMENTED)

#define curandGetVersion(version) __cu(randGetVersion(version))

#endif
