// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
/* Copyright (C) 2025-2026 Rong Tao */
/******************************************************************************\
 *             Solver: LAPACK-marshalling library                             *
\******************************************************************************/
#ifndef __CUDA_ADAPTER_SOLVER_H
#define __CUDA_ADAPTER_SOLVER_H 1

#include "wrapper_defs.h"

#define cusolverStatus_t __nv(solverStatus_t)
#define CUSOLVER_STATUS_SUCCESS __CU(SOLVER_STATUS_SUCCESS)
#define CUSOLVER_STATUS_NOT_INITIALIZED __CU(SOLVER_STATUS_NOT_INITIALIZED)
#define CUSOLVER_STATUS_ALLOC_FAILED __CU(SOLVER_STATUS_ALLOC_FAILED)
#define CUSOLVER_STATUS_INVALID_VALUE __CU(SOLVER_STATUS_INVALID_VALUE)
#define CUSOLVER_STATUS_ARCH_MISMATCH __CU(SOLVER_STATUS_ARCH_MISMATCH)
#define CUSOLVER_STATUS_MAPPING_ERROR __CU(SOLVER_STATUS_MAPPING_ERROR)
#define CUSOLVER_STATUS_EXECUTION_FAILED __CU(SOLVER_STATUS_EXECUTION_FAILED)
#define CUSOLVER_STATUS_INTERNAL_ERROR __CU(SOLVER_STATUS_INTERNAL_ERROR)
#define CUSOLVER_STATUS_MATRIX_TYPE_NOT_SUPPORTED \
	__CU(SOLVER_STATUS_MATRIX_TYPE_NOT_SUPPORTED)
#define CUSOLVER_STATUS_NOT_SUPPORTED __CU(SOLVER_STATUS_NOT_SUPPORTED)
#define CUSOLVER_STATUS_ZERO_PIVOT __CU(SOLVER_STATUS_ZERO_PIVOT)
#define CUSOLVER_STATUS_INVALID_LICENSE __CU(SOLVER_STATUS_INVALID_LICENSE)
#define CUSOLVER_STATUS_IRS_PARAMS_NOT_INITIALIZED \
	__CU(SOLVER_STATUS_IRS_PARAMS_NOT_INITIALIZED)
#define CUSOLVER_STATUS_IRS_PARAMS_INVALID \
	__CU(SOLVER_STATUS_IRS_PARAMS_INVALID)
#define CUSOLVER_STATUS_IRS_PARAMS_INVALID_PREC \
	__CU(SOLVER_STATUS_IRS_PARAMS_INVALID_PREC)
#define CUSOLVER_STATUS_IRS_PARAMS_INVALID_REFINE \
	__CU(SOLVER_STATUS_IRS_PARAMS_INVALID_REFINE)
#define CUSOLVER_STATUS_IRS_PARAMS_INVALID_MAXITER \
	__CU(SOLVER_STATUS_IRS_PARAMS_INVALID_MAXITER)
#define CUSOLVER_STATUS_IRS_INTERNAL_ERROR \
	__CU(SOLVER_STATUS_IRS_INTERNAL_ERROR)
#define CUSOLVER_STATUS_IRS_NOT_SUPPORTED __CU(SOLVER_STATUS_IRS_NOT_SUPPORTED)
#define CUSOLVER_STATUS_IRS_OUT_OF_RANGE __CU(SOLVER_STATUS_IRS_OUT_OF_RANGE)
#define CUSOLVER_STATUS_IRS_NRHS_NOT_SUPPORTED_FOR_REFINE_GMRES \
	__CU(SOLVER_STATUS_IRS_NRHS_NOT_SUPPORTED_FOR_REFINE_GMRES)
#define CUSOLVER_STATUS_IRS_INFOS_NOT_INITIALIZED \
	__CU(SOLVER_STATUS_IRS_INFOS_NOT_INITIALIZED)
#define CUSOLVER_STATUS_IRS_INFOS_NOT_DESTROYED \
	__CU(SOLVER_STATUS_IRS_INFOS_NOT_DESTROYED)
#define CUSOLVER_STATUS_IRS_MATRIX_SINGULAR \
	__CU(SOLVER_STATUS_IRS_MATRIX_SINGULAR)
#define CUSOLVER_STATUS_INVALID_WORKSPACE __CU(SOLVER_STATUS_INVALID_WORKSPACE)

/**
 * cusolverStatus_t cusolverGetVersion(int *version);
 */
#define cusolverGetVersion(v) __nv(solverGetVersion(v))

#endif
