// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
/* Copyright (C) 2025-2026 Rong Tao */
#ifndef __CUDA_ADAPTER_SPARSE_H
#define __CUDA_ADAPTER_SPARSE_H 1

#include "wrapper_defs.h"

#define cusparseStatus_t __cu(sparseStatus_t)
/**
 * HIP 5.7.1 has no hipsparseGetProperty()
 */
#define cusparseGetProperty(v, pval) __cu(sparseGetProperty(v, pval))
#define CUSPARSE_STATUS_SUCCESS __CU(SPARSE_STATUS_SUCCESS)
#define CUSPARSE_STATUS_NOT_INITIALIZED __CU(SPARSE_STATUS_NOT_INITIALIZED)
#define CUSPARSE_STATUS_ALLOC_FAILED __CU(SPARSE_STATUS_ALLOC_FAILED)
#define CUSPARSE_STATUS_INVALID_VALUE __CU(SPARSE_STATUS_INVALID_VALUE)
#define CUSPARSE_STATUS_ARCH_MISMATCH __CU(SPARSE_STATUS_ARCH_MISMATCH)
#define CUSPARSE_STATUS_MAPPING_ERROR __CU(SPARSE_STATUS_MAPPING_ERROR)
#define CUSPARSE_STATUS_EXECUTION_FAILED __CU(SPARSE_STATUS_EXECUTION_FAILED)
#define CUSPARSE_STATUS_INTERNAL_ERROR __CU(SPARSE_STATUS_INTERNAL_ERROR)
#define CUSPARSE_STATUS_MATRIX_TYPE_NOT_SUPPORTED \
	__CU(SPARSE_STATUS_MATRIX_TYPE_NOT_SUPPORTED)
#define CUSPARSE_STATUS_ZERO_PIVOT __CU(SPARSE_STATUS_ZERO_PIVOT)
#define CUSPARSE_STATUS_NOT_SUPPORTED __CU(SPARSE_STATUS_NOT_SUPPORTED)
#define CUSPARSE_STATUS_INSUFFICIENT_RESOURCES \
	__CU(SPARSE_STATUS_INSUFFICIENT_RESOURCES)

#endif
