# SPDX-License-Identifier: GPL-3.0
# Copyright (C) 2025-2026 Rong Tao
ifndef _EMOJI_MK
_EMOJI_MK = 1

EMOJI_CLOCK := 🕘
EMOJI_MOONS := 🌑 🌒 🌓 🌔 🌕 🌖 🌗 🌘 🌑
EMOJI_LOCK := 🔒
EMOJI_UNLOCK := 🔓
EMOJI_KEY := 🔑

EMOJI_WARNING := ⚠️

# MORE: ✓ ✔ ✗ ✘ ☓ ✕ ✖ 〤 √ ☐ ☑ ☒ ✅ ❎ ❌
EMOJI_CHECK := ✅
EMOJI_CROSS := ❌

EMOJI_PENDING := ⏳
EMOJI_COMPUTER := 💻
EMOJI_LOOP := 🔁
EMOJI_BOY := 🧑

EMOJI_ROBOT := 🤖
EMOJI_AIRPLANE := ✈️

# Unicode
# ♥ U+2665
# ❤ U+2764
# ❥ U+2765
# ❦ U+2766
# ❧ U+2767
EMOJI_HEART := ❤

EMOJI_FIRE := 🔥

EMOJI_POINT_RIGHT := 👉
EMOJI_STAR := 🌟

ifdef DEBUG
  $(info EMOJI ${EMOJI_MOONS}${EMOJI_LOCK}${EMOJI_UNLOCK}${EMOJI_KEY} \
         ${EMOJI_WARNING}${EMOJI_CHECK}${EMOJI_CROSS}${EMOJI_AIRPLANE} \
         ${EMOJI_HEART}${EMOJI_FIRE}${EMOJI_PENDING}${EMOJI_ROBOT} \
         ${EMOJI_COMPUTER}${EMOJI_LOOP}${EMOJI_BOY}${EMOJI_CLOCK} \
	 ${EMOJI_POINT_RIGHT}${EMOJI_STAR})
endif

endif
