# SPDX-License-Identifier: GPL-3.0
ifeq ($(shell uname -m),x86_64)
endif
ifeq ($(shell uname -m),aarch64)
endif

obj-m :=

KERNELDIR ?= /lib/modules/$(shell uname -r)/build

ifneq ($(wildcard $(KERNELDIR)),)
  obj-m += main.kernel.o
else
  $(warning "WARNING: You need to install kernel devel")
endif

.PHONY: build
build:
	make -C ${KERNELDIR} M=$(PWD) modules

test:
	@echo "empty, [cd $(PWD)] to insmod"

.PHONY: clean
clean:
	make -C ${KERNELDIR} M=$(PWD) clean
