# Use template to default support some definitions, and include main.mk is not
# necessacy.

# subdirectory need USRC=y by default, see also top Makefile.
USRC ?= y

include arch.mk
include ansi.mk
include dir.mk
include output.mk

# usage: subdir-y += ${ALL_SUBDIR}
ALL_SUBDIR := $(call list_dir)
ALL_SUBDIR := $(filter-out ${OUTPUT}, ${ALL_SUBDIR})
ALL_SUBDIR := $(filter-out $(subst /,,${OUTPUT}), ${ALL_SUBDIR})

ifeq (${USRC}, y)
  include ${CURDIR}/Build.mk
endif

include	main.mk

# Target.mk is not necessacy.
ifneq ($(wildcard ${CURDIR}/Target.mk),)
  include ${CURDIR}/Target.mk
endif
