# SPDX-License-Identifier: GPL-3.0
# This Makefile is a template for test-linux userspace code. You can copy the
# code blob to develope Makefile your own.

include verbose.mk
include ../kconfig.mk

STDIO_H := /usr/include/stdio.h

sub-dir := SUBDIR

targets :=

ifneq ($(wildcard $(STDIO_H)),)
  targets += main.user
else
  $(warning "WARNING: You need to install glibc-headers")
endif

ifeq ($(shell uname -m),x86_64)
else ifeq ($(shell uname -m),aarch64)
endif

OS := $(shell grep ^ID= /etc/os-release | sed 's/ID=//g' | sed 's/"//g')

DEBUG := yes
CC := gcc

include ../compiler/compiler.mk

CFLAGS := -Werror -Wall
CFLAGS += -Wstrict-prototypes

LDFLAGS :=

ifdef DEBUG
  CFLAGS += -DDEBUG=${DEBUG} -O0 -g
endif

ifdef STATIC
  LDFLAGS += -static
  $(info Defined STATIC)
endif

include ../elf/pie.mk

ifdef M32
  CFLAGS += -m32 -DM32=1
  LDFLAGS += -m32
  $(info Compile 32bit ELF)
  ifneq (${CC_M32},1)
    $(error ${CC} not support -m32)
  endif
endif

include ../glibc/glibc.mk
# The following demostration is probe printf(3) function, and add macro to
# CFLAGS.
feature-printf := $(findstring 1,$(call probe_libc_printf))
ifeq ($(feature-printf),1)
  CFLAGS += -DHAVE_PRINTF=1
endif

CFLAGS_main.user := -D_MAIN_USER=1
ifeq ($(CONFIG_MMU),y)
  CFLAGS_main.user += -DCONFIG_MMU=1
endif
CFLAGS_main.user += -Wno-error=cpp
LDFLAGS_main.user :=

define user_strip
  $(Q)strip $(1) -o $(1).strip
endef

include subdir-header.mk

.PHONY: build
build: ${targets} $(sub-dir-build)
	@echo -e "  CFLAGS=${CFLAGS}"
	@echo -e "  LDFLAGS=${LDFLAGS}"
	@echo -e "  PRINTF  ${feature-printf} "
	@echo -e "  CFLAGS  $(CFLAGS)"
	@echo -e "  \033[1;33mDone\033[m"

main.user: main.user.o
main.user.o: main.h main.user.d

%.d: %.c
	@echo -e "  CC.d  \033[1m$(<)\033[m to \033[1m$(@)\033[m"
	$(Q)$(CC) -MMD -o $(@) -c $(<) $(CFLAGS) $(CFLAGS_$(*))

%.o: %.c %.d
	@echo -e "  CC.o  \033[1m$(<)\033[m to \033[1m$(@)\033[m"
	$(Q)$(CC) -MMD -MF $(@:.o=.d) -MP -S $(<) -o $(<:.c=.s) $(CFLAGS) $(CFLAGS_$(*))
	$(Q)$(CC) -MMD -MF $(@:.o=.d) -MP -o $(@) -c $(<) $(CFLAGS) $(CFLAGS_$(*))

$(targets): %:
	@echo -e "  LD  \033[1;32m$(@)\033[m"
	$(Q)$(CC) -o $(@) $(^) $(LDFLAGS) $(LDFLAGS_$(*)) $(CFLAGS) $(CFLAGS_$(*))
	$(Q)$(call user_strip,$(@))

test: ${targets}
	@echo -e "  TEST  \033[1;32m$(targets)\033[m"

.PHONY: clean
clean: $(sub-dir-clean)
	@echo -e "  CLEAN  \033[1;32m$(targets)\033[m"
	$(Q)rm -f ${targets} *.s *.o *.strip *.d

include subdir-footer.mk
