# SPDX-License-Identifier: GPL-3.0
# This Makefile is a template for test-linux userspace code. You can copy the
# code blob to develope Makefile your own.

STDIO_HEADER = /usr/include/stdio.h
KERN_CONFIG=/boot/config-$(shell uname -r)

ifneq ($(wildcard $(KERN_CONFIG)),)
  include ${KERN_CONFIG}
else
  $(warning "WARNING: not found ${KERN_CONFIG}")
endif

sub-dir := SUBDIR

sub-dir-build := $(sub-dir:=.build)
sub-dir-clean := $(sub-dir:=.clean)

TARGETS :=

ifneq ($(wildcard $(STDIO_HEADER)),)
  TARGETS += main.user
else
  $(warning "WARNING: You need to install glibc-headers")
endif

ifeq ($(shell uname -m),x86_64)
endif
ifeq ($(shell uname -m),aarch64)
endif

OS := $(shell grep ^ID= /etc/os-release | sed 's/ID=//g' | sed 's/"//g')

DEBUG = yes
CC = gcc
SHELL = /bin/bash

CFLAGS := -Werror -Wall
CFLAGS += -Wstrict-prototypes

LDFLAGS :=

ifdef DEBUG
  CFLAGS += -DDEBUG -O0 -g
endif
ifdef STATIC
  LDFLAGS += -static
  $(info Defined STATIC)
endif

ifdef PIE
  CFLAGS += -pie -fPIE
  LDFLAGS += -pie -fPIE
endif

ifdef NOPIE
  CFLAGS += -no-pie
  LDFLAGS += -no-pie
  ifdef PIE
    $(error "Could no specify PIE and NOPIE at the same time")
  endif
endif

include ../scripts/libc-printf.mk
# The following demostration is probe printf(3) function, and add macro to
# CFLAGS.
feature-printf := $(findstring 1,$(call probe_libc_printf))
ifeq ($(feature-printf),1)
  CFLAGS += -DHAVE_PRINTF=1
endif

define user_strip
  @strip $(1) -o $(1).strip
endef

.PHONY: build
build: ${TARGETS} $(sub-dir-build)
	@echo
	@echo -e "  CFLAGS=${CFLAGS}"
	@echo -e "  LDFLAGS=${LDFLAGS}"
	@echo -e "  PRINTF  ${feature-printf} "
	@echo -e "  CFLAGS  $(CFLAGS)"
	@echo -e "  \033[1;33mDone\033[m"

$(sub-dir-build):
	make -C $(@:.build=)

# Add more object.o file
main.user: main.user.o

CFLAGS_main.user := -D_MAIN_USER=1
ifeq ($(CONFIG_MMU),y)
  CFLAGS_main.user += -DCONFIG_MMU=1
endif
CFLAGS_main.user += -Wno-error=cpp
LDFLAGS_main.user :=

%.o: %.c
	@echo -e "  CC  \033[1m$(<)\033[m to \033[1m$(@)\033[m"
	@$(CC) -o $(@) -c $(<) $(CFLAGS) $(CFLAGS_$(*))
	@$(CC) -S $(<) -o $(<:.c=.s) $(CFLAGS) $(CFLAGS_$(*))

$(TARGETS): %:
	@echo -e "  LD  \033[1;32m$(@)\033[m"
	@$(CC) -o $(@) $(^) $(LDFLAGS) $(LDFLAGS_$(*)) $(CFLAGS) $(CFLAGS_$(*))
	$(call user_strip,$(@))

test: ${TARGETS}
	@echo -e "  TEST  \033[1;32m$(TARGETS)\033[m"

.PHONY: clean
clean: $(sub-dir-clean)
	@echo -e "  CLEAN  \033[1;32m$(TARGETS)\033[m"
	@rm -f ${TARGETS} *.s *.o *.strip

$(sub-dir-clean):
	@make -C $(@:.clean=) clean
