# SPDX-License-Identifier: GPL-3.0
include ../tlbuild.mk

sub-dir := SUBDIR
include subdir-header.mk

.PHONY: build
build: $(sub-dir-build)
	@echo -e " \033[1;33m Done \033[m"

.PHONY: test
test: $(sub-dir-test)
	@echo -e " \033[1;33m Done \033[m"

.PHONY: clean
clean: $(sub-dir-clean)
	@echo -e " \033[1;33m Done \033[m"

include subdir-footer.mk
