
define success
	@echo >&2 -e " 	                       dBWWS-"
	@echo >&2 -e " 	  zP=====Se-           S=    So"
	@echo >&2 -e " 	 4S       +S          S=      S"
	@echo >&2 -e " 	 +S        +S        JS       SF"
	@echo >&2 -e " 	  +b        Sk       S>       S"
	@echo >&2 -e " 	   Sk        Sr     JS       dS"
	@echo >&2 -e " 	   +S         S     S=       S~"
	@echo >&2 -e " 	    +S        =S   +SE       S"
	@echo >&2 -e " 	     S         SL   S=      SF ---"
	@echo >&2 -e " 	      S-       4B   S      SSSB==+Bb"
	@echo >&2 -e " 	      +S        S-  SS     SS      SF"
	@echo >&2 -e " 	       =S       RS  SF     S=      S"
	@echo >&2 -e " 	        Sk      3S uB     dF      -S"
	@echo >&2 -e " 	        0S-      SS=     zS      uSSSSe"
	@echo >&2 -e " 	         WSb             SE-dW8eS=    3S"
	@echo >&2 -e " 	          WS           -oSSW dSSSSc    3F"
	@echo >&2 -e " 	           S      -dSSW= - zoS>   WSr -uF"
	@echo >&2 -e " 	           SL -uSB=      S&SSSk   -SSdSSF"
	@echo >&2 -e " 	            SS=            ==0=SSSP=SP9S"
	@echo >&2 -e " 	           JP              -oSSSSu:SP SS"
	@echo >&2 -e " 	           S          --ueS=      ==  S="
	@echo >&2 -e " 	          dS          SF              S"
	@echo >&2 -e " 	          SS     ----udE             4B"
	@echo >&2 -e " 	           WS    ====- Sr            8S"
	@echo >&2 -e " 	            0SL        +S            SF"
	@echo >&2 -e " 	              RN        4N           S"
	@echo >&2 -e " 	               BSb                  dS"
	@echo >&2 -e " 	                SSk                 SF"
	@echo >&2 -e " 	                SSb                SF"
	@echo >&2 -e " 	                  S==               SF"
	@echo >&2 -e " 	                  +S                S"
	@echo >&2 -e " 	                   SL               S"
endef

