# SPDX-License-Identifier: GPL-3.0
# Copyright (C) 2026 Rong Tao
#
# Functions:
# - version3_code1688()
# - version3_code1688_cmp()=[y|n]
# - version2_code100010()
# - version2_code100010_cmp()=[y|n]
# - version2_code1616()
# - version2_code1616_cmp()=[y|n]
#
ifndef _VERSION_MK
_VERSION_MK = 1

include shell.mk

###### Version3 1688

# Generate version code from major,minor,patchlevel.
# linux kernel use this method, see /usr/include/linux/version.h.
#
# $1: major, high 16bits
# $2: minor, middle 8bits
# $3: patchlevel, low 8bits
define version3_code1688
$(shell echo "$$(( (${1}<<16) + (${2}<<8) + (${3}>255?255:${3}) ))" )
endef

# Arguments:
# $1: real version code, generated by version3_code1688()
# $2: [-gt|-ge|-eq|-lt|-le]
# $3: major
# $4: minor
# $5: patchlevel
define version3_code1688_cmp
$(shell if [[ ${1} ${2} $(call version3_code1688,${3},${4},${5}) ]]; then \
		echo y; \
	else echo n; \
	fi)
endef

ifneq ($(call version3_code1688_cmp,66051,-eq,1,2,3),y)
  $(error version3_code1688_cmp failed)
endif

###### Version2 100010

# Generate version code from major,minor
# Example: CUDA
# $1: major, multiple 1000
# $2: minor, multiple 10
define version2_code100010
$(shell echo "$$(( (${1}*1000) + (${2}*10) ))" )
endef

# Arguments:
# $1: real version code, generated by version2_code100010()
# $2: [-gt|-ge|-eq|-lt|-le]
# $3: major
# $4: minor
define version2_code100010_cmp
$(shell if [[ ${1} ${2} $(call version2_code100010,${3},${4}) ]]; then \
		echo y; \
	else echo n; \
	fi)
endef

ifneq ($(call version2_code100010_cmp,1020,-eq,1,2),y)
  $(error version2_code100010_cmp failed)
endif

###### Version2 16

# Generate version code from major,minor
# Example: CUDA
# $1: major, high 16 bits
# $2: minor, low 16 bits
define version2_code1616
$(shell echo "$$(( (${1}<<16) + ${2} ))" )
endef

# Arguments:
# $1: real version code, generated by version3_code1616()
# $2: [-gt|-ge|-eq|-lt|-le]
# $3: major
# $4: minor
define version2_code1616_cmp
$(shell if [[ ${1} ${2} $(call version2_code1616,${3},${4}) ]]; then \
		echo y; \
	else echo n; \
	fi)
endef

ifneq ($(call version2_code1616_cmp,65538,-eq,1,2),y)
  $(error version2_code1616_cmp failed)
endif

endif
