# SPDX-License-Identifier: GPL-3.0
# Copyright (C) 2026 Rong Tao. All rights reserved.
#
# Functions:
# - version3_code1688()
# - version3_code1688_cmp()=[<?|y|m>|n]
# - version2_code100010()
# - version2_code100010_cmp()=[<?|y|m>|n]
# - version2_code1616()
# - version2_code1616_cmp()=[<?|y|m>|n]
# - define_version()
#
ifndef _VERSION_MK
_VERSION_MK = 1

include shell.mk

###### Version3 1688

# Generate version code from major,minor,patchlevel.
# linux kernel use this method, see /usr/include/linux/version.h.
#
# $1: major, high 16bits
# $2: minor, middle 8bits
# $3: patchlevel, low 8bits
define version3_code1688
$(shell echo "$$(( (${1}<<16) + (${2}<<8) + (${3}>255?255:${3}) ))" )
endef

# Arguments:
# $1: real version code, generated by version3_code1688()
# $2: [-gt|-ge|-eq|-lt|-le]
# $3: yes letter, such as 'y', 'm'
# $4: major
# $5: minor
# $6: patchlevel
define version3_code1688_cmp
$(shell if [[ ${1} ${2} $(call version3_code1688,${4},${5},${6}) ]]; then \
		echo ${3}; \
	else echo n; \
	fi)
endef

ifneq ($(call version3_code1688_cmp,66051,-eq,y,1,2,3),y)
  $(error version3_code1688_cmp failed)
endif

###### Version2 100010

# Generate version code from major,minor
# Example: CUDA
# $1: major, multiple 1000
# $2: minor, multiple 10
define version2_code100010
$(shell echo "$$(( (${1}*1000) + (${2}*10) ))" )
endef

# Arguments:
# $1: real version code, generated by version2_code100010()
# $2: [-gt|-ge|-eq|-lt|-le]
# $3: yes letter, such as 'y', 'm'
# $4: major
# $5: minor
define version2_code100010_cmp
$(shell if [[ ${1} ${2} $(call version2_code100010,${4},${5}) ]]; then \
		echo ${3}; \
	else echo n; \
	fi)
endef

ifneq ($(call version2_code100010_cmp,1020,-eq,y,1,2),y)
  $(error version2_code100010_cmp failed)
endif

###### Version2 16

# Generate version code from major,minor
# Example: CUDA
# $1: major, high 16 bits
# $2: minor, low 16 bits
define version2_code1616
$(shell echo "$$(( (${1}<<16) + ${2} ))" )
endef

# Arguments:
# $1: real version code, generated by version3_code1616()
# $2: [-gt|-ge|-eq|-lt|-le]
# $3: yes letter, such as 'y', 'm'
# $4: major
# $5: minor
define version2_code1616_cmp
$(shell if [[ ${1} ${2} $(call version2_code1616,${4},${5}) ]]; then \
		echo ${3}; \
	else echo n; \
	fi)
endef

ifneq ($(call version2_code1616_cmp,65538,-eq,y,1,2),y)
  $(error version2_code1616_cmp failed)
endif

# Define version compare functions
#
# Functions: x_gt(), x_ge(), x_eq(), x_lt(), x_le()
#
# $1: name, like glibc
# $2: version function, like version3_code1688
# $3: yes letter, such as 'y', 'm'
# $4: major of version
# $5: minor of version
# $6: patchlevel of version, could be empty
define define_version
$(if ${4},,$(error Empty major is not allowed for '${1}'))
$(eval ${1}_VERSION_CODE := $$(call ${2},${4},${5},${6}))

define ${1}_gt
$$(call ${2}_cmp,$${${1}_VERSION_CODE},-gt,${3},$${1},$${2},$${3})
endef
define ${1}_ge
$$(call ${2}_cmp,$${${1}_VERSION_CODE},-ge,${3},$${1},$${2},$${3})
endef
define ${1}_eq
$$(call ${2}_cmp,$${${1}_VERSION_CODE},-eq,${3},$${1},$${2},$${3})
endef
define ${1}_lt
$$(call ${2}_cmp,$${${1}_VERSION_CODE},-lt,${3},$${1},$${2},$${3})
endef
define ${1}_le
$$(call ${2}_cmp,$${${1}_VERSION_CODE},-le,${3},$${1},$${2},$${3})
endef

# Make sure function works fine.
ifneq ($$(call ${1}_eq,${4},${5},${6}),${3})
  $$(error ${1}_eq failed, get '$$(call ${1}_eq,${4},${5},${6})' but need 'y')
endif
ifneq ($$(call ${1}_le,${4},${5},${6}),${3})
  $$(error ${1}_le failed, get '$(call ${1}_le,${4},${5},${6})' but need 'y')
endif
ifneq ($$(call ${1}_ge,${4},${5},${6}),${3})
  $$(error ${1}_ge failed, get '$$(call ${1}_ge,${4},${5},${6})' but need 'y')
endif
ifneq ($$(call ${1}_ge,0,0,0),${3})
  $$(error "Call ${1}_gt failed, get '$$(call ${1}_gt,0,0,0)' but need 'y'")
endif
$$(if $${DEBUG}, $$(info ${1}_VERSION_CODE = ${${1}_VERSION_CODE}))
endef # end of define_version()

$(eval $(call define_version,rtoax1,version2_code1616,y,1,2))
$(eval $(call define_version,rtoax2,version2_code100010,x,1,2))
ifneq ($(call rtoax2_eq,1,2),x)
  $(error rtoax2_eq failed)
endif
$(eval $(call define_version,rtoax3,version3_code1688,m,1,2,3))
ifneq ($(call rtoax3_eq,1,2,3),m)
  $(error rtoax3_eq failed)
endif

endif
