# SPDX-License-Identifier: GPL-3.0
# Copyright (C) 2026 Rong Tao
#
# Functions:
# - version3_code1688()
# - version3_code1688_cmp()
# - version2_code100010()
#
ifndef _VERSION_MK
_VERSION_MK = 1

# Generate version code from major,minor,patchlevel
# $1: major, 16bits
# $2: minor, 8bits
# $3: patchlevel, 8bits
define version3_code1688
$(shell echo "$$(( (${1}<<16) + (${2}<<8) + (${3}>255?255:${3}) ))" )
endef

# Arguments:
# $1: real version code, generated by version3_code1688()
# $2: [-gt|-ge|-eq|-lt|-le]
# $3: major
# $4: minor
# $5: patchlevel
define version3_code1688_cmp
$(shell if [[ ${1} ${2} $(call version3_code1688,${3},${4},${5}) ]]; then \
		echo y; \
	else echo n; \
	fi)
endef

# Generate version code from major,minor
# Example: CUDA
# $1: major, multiple 1000
# $2: minor, multiple 10
define version2_code100010
$(shell echo "$$(( (${1}*1000) + (${2}*10) ))" )
endef

endif
