apiVersion: v1
kind: Pod
metadata:
  name: fedora-pod
spec:
  # Containers shared one virtual NIC, see
  # commit 5e723caca9c1 ("podman: pod: network: containers in pod share nic")
  containers:
    - name: fedora44
      image: registry.fedoraproject.org/fedora:44
      command: ["/bin/bash", "-c", "sleep infinity"]
    - name: fedora43
      image: registry.fedoraproject.org/fedora:43
      command: ["/bin/bash", "-c", "sleep infinity"]
