apiVersion: v1
kind: Pod
metadata:
  name: fedora-pod
spec:
  # Containers shared one virtual NIC, see
  # commit 5e723caca9c1 ("podman: pod: network: containers in pod share nic")
  containers:
    - name: fedora44
      image: registry.fedoraproject.org/fedora:44
      volumeMounts:
      - name: git-data
        mountPath: /root/Git/
      command: ["/bin/bash", "-c", "sleep infinity"]
    - name: fedora43
      image: registry.fedoraproject.org/fedora:43
      volumeMounts:
      - name: git-data
        mountPath: /root/Git/
      command: ["/bin/bash", "-c", "sleep infinity"]
  volumes:
  - name: git-data
    hostPath:
      path: /home/rongtao/Git/
      type: DirectoryOrCreate
