# SPDX-License-Identifier: GPL-3.0
sub-dir :=
sub-dir += alias
sub-dir += array
sub-dir += commands
sub-dir += math
sub-dir += network
sub-dir += string

target-shell-y :=
target-shell-y += args.sh
target-shell-y += call.sh
target-shell-y += digit.sh
target-shell-y += nested-func.sh
target-shell-y += num.sh
target-shell-y += open-fd.sh
target-shell-y += parallel.sh
target-shell-y += replace.sh
target-shell-y += ret.sh
target-shell-y += root-chk.sh
target-shell-y += select.sh
target-shell-y += stat.sh
target-shell-y += tracing.sh
target-shell-y += trap.sh
target-shell-y += while.sh
target-shell-y += cmdline.sh
target-shell-y += sudo.sh
target-shell-y += c_code.sh

SHELL_ARGS_stat.sh := /etc/os-release /etc/hosts

include ../template/main.mk
