# SPDX-License-Identifier: GPL-3.0
sub-dir :=
sub-dir += alias
sub-dir += array
sub-dir += commands
sub-dir += math
sub-dir += network
sub-dir += string

TARGETS_SHELL :=
TARGETS_SHELL += args.sh
TARGETS_SHELL += call.sh
TARGETS_SHELL += digit.sh
TARGETS_SHELL += nested-func.sh
TARGETS_SHELL += num.sh
TARGETS_SHELL += open-fd.sh
TARGETS_SHELL += parallel.sh
TARGETS_SHELL += replace.sh
TARGETS_SHELL += ret.sh
TARGETS_SHELL += root-chk.sh
TARGETS_SHELL += select.sh
TARGETS_SHELL += stat.sh
TARGETS_SHELL += tracing.sh
TARGETS_SHELL += trap.sh
TARGETS_SHELL += while.sh
TARGETS_SHELL += cmdline.sh
TARGETS_SHELL += sudo.sh
TARGETS_SHELL += c_code.sh

SHELL_ARGS_stat.sh := /etc/os-release /etc/hosts

include ../template/main.mk
