# ref: https://www.kernel.org/doc/html/latest/bpf/btf.html
# 6. BTF Generation

target-bpf-y := t1.bpf.o
target-bpf-y += t2.bpf.o

target-post-y := t1.bpf.btf
target-post-y += t2.bpf.s

include ../../../template/main.mk
