# ref: https://www.kernel.org/doc/html/latest/bpf/btf.html
# 6. BTF Generation

TARGETS_BPF := t1.bpf.o
TARGETS_BPF += t2.bpf.o

TARGETS_POST := t1.bpf.btf
TARGETS_POST += t2.bpf.s

include ../../../template/main.mk
