# SPDX-License-Identifier: GPL-3.0
include ../../../tlbuild.mk

.PHONY: build
build:
	${Q}./create.sh
	${Q}./create2.sh
	@echo -e " \033[1;33m Done \033[m"

test:
	@echo -e "  TEST"

.PHONY: clean
clean:
	@echo -e "  CLEAN"

