include ../../tlbuild.mk


sub-dir := c
sub-dir += lr
sub-dir += samples

include ../../template/subdir-header.mk

.PHONY: build
build: $(sub-dir-build)

.PHONY: clean
clean: $(sub-dir-clean)

include ../../template/subdir-footer.mk
