# SPDX-License-Identifier: GPL-3.0
# Copyright (C) 2026 Rong Tao
#
# Functions:
# - make_gen_cachefile()
# - make_append_var_to_file()
#
ifndef _BITS_MK_CACHE_MK
_BITS_MK_CACHE_MK = 1

include shell.mk

# Generate cache file
# $1: file
define make_gen_cachefile
$(shell rm -f ${1} && echo > ${1})
$(shell sed -i "1i# Generated in $$(date '+%Y/%m/%d %H:%M:%S')" ${1})
$(shell sed -i "1i# File ${1}" ${1})
$(shell sed -i "1i# This file was generated by test-linux, do not modify it" ${1})
endef

# Append makefile variable to file and export it, better call
# make_gen_cachefile() first to create cache file.
#
# $1: variable append to cache file
# $2: cache file name
define make_append_var_to_file
$(eval $(shell echo "export ${1} := ${${1}}" >> ${2}))
endef

endif
