#!/bin/bash
answer=N
[[ ! -z $1 ]] && answer=$1

no_commit_files() {
	echo "Files not commited will be removed:"
	git status --porcelain | grep '^??' | cut -c4- | sed 's/^/- /g'
}

ignore_files() {
	echo "Files ignored will be removed:"
	git clean -dfx --dry-run | sed 's/^/- /g'
}

pre_hint() {
	no_commit_files
	ignore_files
}

if [[ ${answer} != y ]]; then
	while pre_hint && read -p "Are you sure? [N/y] " answer
	do
		case $answer in
		y | Y | Yes | yes)
			break
			;;
		n | N | No | no)
			echo "Bye!"
			exit 0
			;;
		*)
			continue
			;;
		esac
	done
fi

sudo git clean -dfx
echo "Clean git"
