#!/bin/bash
answer=N
[[ ! -z $1 ]] && answer=$1

no_commit_files() {
	echo "Files not commited will be removed:"
	git status --porcelain | grep '^??' | cut -c4-
}

pre_hint() {
	no_commit_files
}

if [[ ${answer} != y ]]; then
	while pre_hint && read -p "Are you sure? [N/y] " answer
	do
		case $answer in
		y)
			break
			;;
		N)
			echo "Bye!"
			exit 0
			;;
		*)
			continue
			;;
		esac
	done
fi

git clean -dfx
echo "Clean git"
