#!/bin/bash
answer=N
[[ ! -z $1 ]] && answer=$1

if [[ ${answer} != y ]]; then
	while read -p "Are you sure? [N/y] " answer
	do
		case $answer in
		y)
			break
			;;
		N)
			echo "Bye!"
			exit 0
			;;
		*)
			continue
			;;
		esac
	done
fi

git clean -dfx
echo "Clean git"
