TARGETS := semaphore
TARGETS += latency
TARGETS += pthread-semaphore

CFLAGS :=
CFLAGS += -lpthread

include ../../../template/main.mk

semaphore: semaphore.o
latency: latency.o
pthread-semaphore: pthread-semaphore.o
