# SPDX-License-Identifier: GPL-3.0
target-shell-y := gsub.sh
target-shell-y += index.sh
target-shell-y += length.sh
target-shell-y += match.sh
target-shell-y += strtonum.sh
target-shell-y += swap-two-words.sh

include ../../../template/main.mk
