# SPDX-License-Identifier: GPL-3.0
TARGETS_SHELL := gsub.sh
TARGETS_SHELL += index.sh
TARGETS_SHELL += length.sh
TARGETS_SHELL += match.sh
TARGETS_SHELL += strtonum.sh
TARGETS_SHELL += swap-two-words.sh

include ../../../template/main.mk
