target-y += dallocx
target-y += mallctl
target-y += malloc_stats_print
target-y += malloc_usable_size
target-y += mallocx
target-y += nallocx
target-y += rallocx
target-y += sallocx
target-y += sdallocx
target-y += xallocx
target-y += stress

LDFLAGS += -ljemalloc

include main.mk
