# SPDX-License-Identifier: GPL-3.0
include ../../tlbuild.mk

.PHONY: all
all:
	@echo -e "  BUILD  \033[1;33m SUBDIR build \033[m"

.PHONY: test
test:
	@echo -e "  TEST  \033[1;33m SUBDIR test \033[m"

.PHONY: clean
clean:
	@echo -e "  CLEAN  \033[1;33m SUBDIR clean \033[m"
