targets :=
targets += perf_event_open
targets += perf_event_open-2

include ../../../template/main.mk

perf_event_open: perf_event_open.o perf_helpers.o
perf_event_open-2: perf_event_open-2.o perf_helpers.o
