# SPDX-License-Identifier: GPL-3.0
TARGETS :=
TARGETS += atomic_fetch_add

CFLAGS := -Werror -Wall
CFLAGS += -Wstrict-prototypes
CFLAGS += -lpthread

include ../../../template/main.mk

atomic_fetch_add: atomic_fetch_add.o
