# SPDX-License-Identifier: GPL-3.0
target-shell-y := archive.sh
target-shell-y += diff.sh
target-shell-y += file-change.sh
target-shell-y += uncommitted-files.sh
target-shell-y += version.sh

include main.mk
