#if !defined(PATH_CONF)
# error Not define PATH_CONF
#endif
/* pathconf(3) */
PATH_CONF(_PC_LINK_MAX)
PATH_CONF(_PC_MAX_CANON)
PATH_CONF(_PC_MAX_INPUT)
PATH_CONF(_PC_NAME_MAX)
PATH_CONF(_PC_PATH_MAX)
PATH_CONF(_PC_PIPE_BUF)
PATH_CONF(_PC_CHOWN_RESTRICTED)
PATH_CONF(_PC_NO_TRUNC)
PATH_CONF(_PC_VDISABLE)

