# 此文件配置内容为/etc/dhcp/dhcpd.conf
#
# 如果你想要在局域网中，用一个交换机+一个PC机搭建一个DHCP环境，首先给PC的网口
# 配置一个IP地址，无需网关（也没有网关）
#
# $ sudo nmcli connecttion modify enp4s0 ipv4.addresses 192.168.1.100/24 ipv4.method manual
#
# 然后，/etc/dhcp/dhcpd.conf 内容修改为此文件内容，
#
# 再重启 dhcpd.service 即刻

subnet 192.168.1.0 netmask 255.255.255.0 {
	range 192.168.1.110 192.168.1.250;
	option domain-name-servers 192.168.1.100;
	default-lease-time 600;
	max-lease-time 7200;
}
