#!/bin/env lua

-- Execute command
cmd = function(cmd)
	cmd = io.popen(cmd, 'r')
	cmd = cmd:read('a+')
	return cmd
end

erg = cmd('cat /etc/os-release')
print(erg)

erg = cmd('test -e /lib64/libc.so.6 && echo /lib64/libc.so.6')
print(erg)

cmd('test -e libc.so.6 && rm -f libc.so.6')
cmd('test -e /lib64/libc.so.6 && ln -s /lib64/libc.so.6 libc.so.6')
