// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
/* Copyright (C) 2026 Rong Tao */
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "file.h"
#include "plot.h"
#include "load.h"
#include "line.h"
#include "ram.h"
#ifdef HAVE_JSON_C
#include <json-c/json.h>
#endif

#define FILE_TXT "plotcake.txt"
#define FILE_JSON "plotcake.json"

struct plot_file_operations {
	const char *name;
	int (*save)(const struct plot *p, const char *filename, bool debug);
	int (*load)(struct plot *p, const char *file, bool debug);
};

static int __create_lgroup(struct plot *p, const char *lname)
{
	if (!strcmp(lname, "loadavg")) {
		plot_add_lgroup(p, &lg_loadavg, NULL);
	} else if (!strcmp(lname, "ram")) {
		plot_add_lgroup(p, &lg_ram, NULL);
	} else {
		fprintf(stderr, "ERROR: not support '%s' yet.\n", lname);
		return -EINVAL;
	}
	return 0;
}

static int save_txt(const struct plot *p, const char *filename, bool debug)
{
	char path[256];
	FILE *fp;

	sprintf(path, "%s.txt", filename);

	fp = fopen(path, "w");
	if (!fp) {
		fprintf(stderr, "ERROR: open %s failed, %m\n", path);
		return -errno;
	}

	fprintf(fp, "# This file was generated by plotcake %s\n", MY_VERSION);
	fprintf(fp, "#\n");
	fprintf(fp, "# File: %s\n", path);
	fprintf(fp, "# Version: %s\n", MY_VERSION);
	fprintf(fp, "#\n");
	fprintf(fp, "#    nlgroup title xlabel ylabel\n");
	fprintf(fp, "plot %d \"%s\" \"%s\" \"%s\"\n", p->lgcount, p->title,
		p->label_x, p->label_y);

	for_each_lgroup(p, lg)
	{
		fprintf(fp, "#      name idx nline\n");
		fprintf(fp, "lgroup %s %d %d\n", lg->name, lg->id, lg->count);

		for_each_line(lg, ln)
		{
			fprintf(fp,
				"#    lgidx lnidx lname nvals color type\n");
			fprintf(fp, "line %d %d \"%s\" %ld %s %s\n", lg->id,
				ln->id, ln->name, ln->count,
				color_names[ln->color], ln->ops->name);

			fprintf(fp,
				"#     lgidx lnidx value timeval{ sec usec }\n");
			for_each_value(ln, v)
			{
				fprintf(fp, "value %d %d %lf %ld %ld\n", lg->id,
					ln->id, v->v, v->tv.tv_sec,
					v->tv.tv_usec);
			}
		}
	}

	fclose(fp);
	return 0;
}

static int load_txt(struct plot *p, const char *file, bool debug)
{
	int ln, err = 0;
	char linebuf[256];
	FILE *fp;

	fp = fopen(file, "r");
	if (!fp) {
		fprintf(stderr, "ERROR: open file %s failed, %m\n", file);
		return -errno;
	}

	ln = 0;
	while (fgets(linebuf, sizeof(linebuf), fp) != NULL) {
		ln++;
		if (linebuf[0] == '#')
			continue;

		if (!strncmp(linebuf, "plot ", 5)) {
			char *start = linebuf, *end;
#define Check(s, c)                                                      \
	if (s == NULL) {                                                 \
		fprintf(stderr, "[%d] Missing %s in line %d, col %ld\n", \
			__LINE__, #c, ln, (unsigned long)(s - linebuf)); \
		err = -EINVAL;                                           \
		break;                                                   \
	}
			start = strchr(start, '"') + 1;
			Check(start - 1, '"');
			end = strchr(start, '"');
			Check(end, '"');
			*end = '\0';
			set_plot_title(p, start);

			start = end + 1;
			start = strchr(start, '"') + 1;
			Check(start - 1, '"');
			end = strchr(start, '"');
			Check(end, '"');
			*end = '\0';
			set_plot_xlabel(p, start);

			start = end + 1;
			start = strchr(start, '"') + 1;
			Check(start - 1, '"');
			end = strchr(start, '"');
			Check(end, '"');
			*end = '\0';
			set_plot_ylabel(p, start);

		} else if (!strncmp(linebuf, "lgroup ", 7)) {
			char *start = linebuf, *end;

			start = strchr(start, ' ') + 1;
			Check(start - 1, ' ');
			end = strchr(start, ' ');
			Check(end, ' ');
			*end = '\0';

			err = __create_lgroup(p, start);
			if (err)
				break;
		} else if (!strncmp(linebuf, "line ", 5)) {
			char *start = linebuf, *end;
			int idx;
			char *lname, *lcolor;
			struct lgroup *lg = NULL;

			/* lgroup index */
			start = strchr(start, ' ') + 1;
			Check(start - 1, ' ');
			end = strchr(start, ' ');
			Check(end, ' ');
			*end = '\0';

			idx = atoi(start);
			lg = plot_lgroup(p, idx);
			if (!lg) {
				fprintf(stderr, "ERROR: not found lgroup %d.\n",
					idx);
				err = -EINVAL;
				break;
			}

			/* line index */
			start = end + 1;
			end = strchr(start + 1, ' ');
			Check(end, ' ');
			*end = '\0';

			/* line name */
			start = end + 1;
			start = strchr(start, '"') + 1;
			Check(start - 1, '"');
			end = strchr(start, '"');
			Check(end, '"');
			*end = '\0';
			lname = start;
			(void)lname;
			end++; /* skip '"' */

			/* line values count */
			start = end + 1;
			end = strchr(start, ' ');
			Check(end, ' ');

			/* line color */
			start = end + 1;
			end = strchr(start, ' ');
			Check(end, ' ');
			*end = '\0';
			lcolor = start;
			if (!lcolor_hasname(lcolor)) {
				fprintf(stderr, "ERROR: unknown color '%s'.\n",
					lcolor);
				err = -EINVAL;
				break;
			}

			/* line draw operation */
			start = strrchr(linebuf, ' ') + 1;
			Check(start - 1, ' ');

			new_line(lg, lname, lcolor_name2num(lcolor));

		} else if (!strncmp(linebuf, "value ", 6)) {
			char *start = linebuf, *end;
			struct lgroup *lg = NULL;
			struct line *line = NULL;
			int idx;
			double v;
			struct timeval tv;

			/* lgroup index */
			start = strchr(start, ' ') + 1;
			Check(start - 1, ' ');
			end = strchr(start, ' ');
			Check(end, ' ');
			*end = '\0';

			idx = atoi(start);
			lg = plot_lgroup(p, idx);
			if (!lg) {
				fprintf(stderr, "ERROR: not found lgroup %d.\n",
					idx);
				err = -EINVAL;
				break;
			}

			/* line index */
			start = end + 1;
			end = strchr(start + 1, ' ');
			Check(end, ' ');
			*end = '\0';

			idx = atoi(start);
			line = lgroup_line(lg, idx);
			if (!line) {
				fprintf(stderr, "ERROR: not found line %d.\n",
					idx);
				err = -EINVAL;
				break;
			}

			/* value */
			start = end + 1;
			end = strchr(start + 1, ' ');
			Check(end, ' ');
			*end = '\0';

			if (sscanf(start, "%lf", &v) != 1) {
				fprintf(stderr,
					"ERROR: not found value in line %d.\n",
					ln);
				err = -EINVAL;
				break;
			}

			/* timeval sec */
			start = end + 1;
			end = strchr(start + 1, ' ');
			Check(end, ' ');
			*end = '\0';

			tv.tv_sec = strtoul(start, NULL, 10);

			/* timeval usec */
			start = end + 1;
			end = strchr(start + 1, '\n');
			Check(end, ' ');
			*end = '\0';

			tv.tv_usec = strtoul(start, NULL, 10);

			line_add_value(line, v, -1, &tv);
		} else {
			err = -EINVAL;
			break;
		}
#undef Check
	}

	fclose(fp);
	return err;
}

#ifdef HAVE_JSON_C
static int save_json(const struct plot *p, const char *filename, bool debug)
{
	char path[256];

	sprintf(path, "%s.json", filename);

	json_object *root, *info, *plot;

	root = json_object_new_object();
	info = json_object_new_object();
	plot = json_object_new_object();

	json_object_object_add(root, "plotcake", info);
	json_object_object_add(info, "version",
			       json_object_new_string(MY_VERSION));

	json_object_object_add(root, "plot", plot);

	json_object_object_add(plot, "title", json_object_new_string(p->title));
	json_object_object_add(plot, "xlabel",
			       json_object_new_string(p->label_x));
	json_object_object_add(plot, "ylabel",
			       json_object_new_string(p->label_y));
	json_object_object_add(plot, "lgcount",
			       json_object_new_int(p->lgcount));

	json_object *lgroups = json_object_new_object();
	json_object_object_add(plot, "lgroups", lgroups);

	for_each_lgroup(p, lg)
	{
		json_object *lines = json_object_new_object();

		char lgs[16];
		snprintf(lgs, 16, "%d", lg->id);
		json_object *lgroup = json_object_new_object();
		json_object_object_add(lgroups, lgs, lgroup);

		json_object_object_add(lgroup, "name",
				       json_object_new_string(lg->name));
		json_object_object_add(lgroup, "id",
				       json_object_new_int(lg->id));
		json_object_object_add(lgroup, "lncount",
				       json_object_new_int(lg->count));
		json_object_object_add(lgroup, "lines", lines);

		for_each_line(lg, ln)
		{
			char lns[16];
			snprintf(lns, 16, "%d", ln->id);
			json_object *line = json_object_new_object();

			json_object_object_add(lines, lns, line);

			json_object_object_add(
				line, "name", json_object_new_string(ln->name));
			json_object_object_add(line, "id",
					       json_object_new_int(ln->id));
			json_object_object_add(
				line, "color",
				json_object_new_string(color_names[ln->color]));
			json_object_object_add(
				line, "type",
				json_object_new_string(ln->ops->name));
			json_object_object_add(line, "vcount",
					       json_object_new_int(ln->count));

			json_object *values = json_object_new_object();
			json_object_object_add(line, "values", values);

			int vidx = 0;
			for_each_value(ln, v)
			{
				char vs[16];
				snprintf(vs, 16, "%d", vidx);
				json_object *value = json_object_new_object();
				json_object_object_add(values, vs, value);

				json_object_object_add(
					value, "v",
					json_object_new_double(v->v));

				json_object *tv = json_object_new_array();
				json_object_array_add(
					tv,
					json_object_new_uint64(v->tv.tv_sec));
				json_object_array_add(
					tv,
					json_object_new_uint64(v->tv.tv_usec));

				json_object_object_add(value, "tv", tv);

				vidx++;
			}
		}
	}

	json_object_to_file_ext(path, root, JSON_C_TO_STRING_PRETTY);
	json_object_put(root);
	return 0;
}

static int load_json(struct plot *p, const char *file, bool debug)
{
	int err;
	char *json;

	json_object *root, *info, *plot, *lgroups, *lines, *values;

	err = alloc_buf_read_file(file, &json);
	if (err < 0) {
		fprintf(stderr, "ERROR: read json %s failed.\n", file);
		return err;
	}

	root = json_tokener_parse(json);
	json_object_object_get_ex(root, "plotcake", &info);
	json_object_object_get_ex(root, "plot", &plot);

#define J_STRING(name)     \
	json_object *name; \
	const char *name##_s

#define J_INT(name)        \
	json_object *name; \
	int name##_i

#define J_U64(name)        \
	json_object *name; \
	uint64_t name##_u64

#define J_DOUBLE(name)     \
	json_object *name; \
	double name##_d

#define J_GET_VALUE(obj, key, value)                                        \
	if (!json_object_object_get_ex(obj, key, &value)) {                 \
		fprintf(stderr, "ERROR: not found %s in %s.\n", key, #obj); \
		err = -ENOENT;                                              \
		goto done;                                                  \
	}

#define J_GET_STRING(value)                                    \
	value##_s = json_object_get_string(value);             \
	if (debug) {                                           \
		fprintf(stderr, "%s %s\n", #value, value##_s); \
	}

#define J_GET_INT(value)                                       \
	value##_i = json_object_get_int(value);                \
	if (debug) {                                           \
		fprintf(stderr, "%s %d\n", #value, value##_i); \
	}

#define J_GET_U64(value)                                          \
	value##_u64 = json_object_get_int(value);                 \
	if (debug) {                                              \
		fprintf(stderr, "%s %ld\n", #value, value##_u64); \
	}

#define J_GET_DOUBLE(value)                                     \
	value##_d = json_object_get_double(value);              \
	if (debug) {                                            \
		fprintf(stderr, "%s %lf\n", #value, value##_d); \
	}

	J_STRING(version);
	J_GET_VALUE(info, "version", version);
	J_GET_STRING(version);

	J_STRING(title);
	J_GET_VALUE(plot, "title", title);
	J_GET_STRING(title);
	set_plot_title(p, title_s);

	J_STRING(xlabel);
	J_GET_VALUE(plot, "xlabel", xlabel);
	J_GET_STRING(xlabel);
	set_plot_xlabel(p, xlabel_s);

	J_STRING(ylabel);
	J_GET_VALUE(plot, "ylabel", ylabel);
	J_GET_STRING(ylabel);
	set_plot_ylabel(p, ylabel_s);

	J_INT(lgcount);
	J_GET_VALUE(plot, "lgcount", lgcount);
	J_GET_INT(lgcount);

	J_GET_VALUE(plot, "lgroups", lgroups);

	json_object_object_foreach(lgroups, gid_s, lgroup)
	{
		if (debug)
			printf("lgroup id %s\n", gid_s);

		J_STRING(lgname);
		J_GET_VALUE(lgroup, "name", lgname);
		J_GET_STRING(lgname);

		err = __create_lgroup(p, lgname_s);
		if (err)
			goto done;

		J_INT(lgid);
		J_GET_VALUE(lgroup, "id", lgid);
		J_GET_INT(lgid);

		J_INT(lncount);
		J_GET_VALUE(lgroup, "lncount", lncount);
		J_GET_INT(lncount);

		J_GET_VALUE(lgroup, "lines", lines);

		json_object_object_foreach(lines, lid_s, line)
		{
			if (debug)
				printf("line id %s\n", lid_s);

			J_STRING(lname);
			J_GET_VALUE(line, "name", lname);
			J_GET_STRING(lname);

			J_INT(lid);
			J_GET_VALUE(line, "id", lid);
			J_GET_INT(lid);

			J_STRING(lcolor);
			J_GET_VALUE(line, "color", lcolor);
			J_GET_STRING(lcolor);

			J_STRING(ltype);
			J_GET_VALUE(line, "type", ltype);
			J_GET_STRING(ltype);

			J_INT(vcount);
			J_GET_VALUE(line, "vcount", vcount);
			J_GET_INT(vcount);

			J_GET_VALUE(line, "values", values);

			json_object_object_foreach(values, vid_s, value)
			{
				if (debug)
					printf("value id %s\n", vid_s);

				J_DOUBLE(v);
				J_GET_VALUE(value, "v", v);
				J_GET_DOUBLE(v);

				json_object *tv;
				J_GET_VALUE(value, "tv", tv);

				if (json_object_get_type(tv) !=
				    json_type_array) {
					fprintf(stderr,
						"ERROR: tv is not arrary\n");
					goto done;
				}
				int len = json_object_array_length(tv);
				if (len != 2) {
					fprintf(stderr,
						"ERROR: tv must has two value\n");
					goto done;
				}

				J_U64(sec);
				J_U64(usec);

				sec = json_object_array_get_idx(tv, 0);
				usec = json_object_array_get_idx(tv, 1);

				if (!sec || !usec) {
					fprintf(stderr,
						"ERROR: get tv failed\n");
					goto done;
				}

				J_GET_U64(sec);
				J_GET_U64(usec);
			}
		}
	}

#undef J_STRING
#undef J_INT
#undef J_GET_VALUE
#undef J_GET_STRING
#undef J_GET_INT

done:
	free(json);
	/* TODO: return err */
	fprintf(stderr, "ERROR: Not support input json yet.\n");
	return -ENOTSUP;
}
#endif

static struct plot_file_operations pf_ops[] = {
	{
		.name = "txt",
		.save = &save_txt,
		.load = &load_txt,
	},
#ifdef HAVE_JSON_C
	{
		.name = "json",
		.save = &save_json,
		.load = &load_json,
	},
#endif
};

/**
 * only have one plot
 * @filename: file name without extension.
 */
int save_plot(const struct plot *p, const char *filename, bool debug)
{
	int err = 0;
	const char *name = filename ?: "plotcake";
	for (int i = 0; i < sizeof(pf_ops) / sizeof(pf_ops[0]); i++) {
		if (!pf_ops[i].save)
			continue;
		fprintf(stderr, "Save to %s.%s\n", name, pf_ops[i].name);
		err = err ?: pf_ops[i].save(p, name, debug);
	}
	return err;
}

int load_plot(struct plot *p, const char *file, bool debug)
{
	const struct plot_file_operations *ops = NULL;

	for (int i = 0; i < sizeof(pf_ops) / sizeof(pf_ops[0]); i++) {
		if (!pf_ops[i].load)
			continue;
		const char *ext = strrchr(file, '.');
		if (ext)
			ext++;
		else {
			fprintf(stderr,
				"ERROR: Not found extension of file %s\n",
				file);
			return -EINVAL;
		}
		if (!strcmp(ext, pf_ops[i].name)) {
			ops = &pf_ops[i];
			break;
		}
	}
	if (!ops) {
		fprintf(stderr,
			"ERROR: Not found plot file operation for file %s\n",
			file);
		return -ENOENT;
	}

	return ops->load(p, file, debug);
}

static void file_create(struct lgroup *lg, void *arg)
{
	// TODO
}

static void file_update(struct lgroup *lg, void *arg)
{
	// TODO
}

static void file_plot_debug(const struct lgroup *lg, void *arg)
{
	// TODO
}

static struct lgroup_operations file_ops = {
	.create = file_create,
	.update = file_update,
	.plot_debug = file_plot_debug,
};

struct lgroup lg_file = {
	.ops = &file_ops,
};
