#!/bin/expect -f
# test plotcake keyboard event handle
set timeout 3
set title "TITLE_XXX"
set line1 "LINE_LABEL_1"

spawn bash -c "while sleep 1; do echo 1; done |
	./plotcake --title ${title} -l ${line1} --verbose"
sleep 0.1

expect {
	"${title}" { send_user "Found title ${title}\n" }
	timeout { send_user "FATAL: not found title\n"; exit 1 }
}

send "l"
expect {
	" ${line1}" { send_user "Success check line labels\n" }
	timeout { send_user "FATAL: key 'l' failed\n"; exit 1 }
}
sleep .5

send "h"
expect {
	"'q' and Esc: quit" { send_user "Success check help" }
	timeout { send_user "FATAL: key 'h' failed\n"; exit 1 }
}
sleep .5

send "r"
expect {
	"cur=114=" { send_user "Success reset" }
	timeout { send_user "FATAL: key 'r' failed\n"; exit 1 }
}
sleep .5

# Test enter
#send "\r"
#expect {
#	"enter=1" { send_user "Success enter" }
#	timeout { send_user "FATAL: key 'enter' failed\n"; exit 1 }
#}
#sleep .5

send "q"
expect eof
puts "PASS"
