#!/bin/expect -f
# test plotcake keyboard event handle
set timeout 5

spawn bash -c "while sleep 1; do echo 1; done | ./plotcake --title TITLE_XXX -l LINE_1"
sleep 0.1

expect "TITLE_XXX"

send "l"
expect {
	" LINE_1" { send_user "Success check line labels\n" }
	timeout { send_user "FATAL: key 'l' failed\n"; exit 1 }
}
sleep .5

send "h"
expect {
	"'q' and Esc: quit" { send_user "Success check help" }
	timeout { send_user "FATAL: key 'h' failed\n"; exit 1 }
}
sleep .5

send "q"
expect eof
puts "PASS"
