#!/bin/bash
# generate all sysconf test code

function for_each_conf()
{
	if [[ ! -e /usr/include/bits/confname.h ]]; then
		echo "ERROR: /usr/include/bits/confname.h is not exist"
		exit 1
	fi

	confnames=( $(cat /usr/include/bits/confname.h | awk '{
			if ($1=="#define" && $2==$3)
				print $2
			}'
			)
		)
	local conf_list=confs_def.h

	echo "/* Generated by test-linux */" > $conf_list

	for ((i = 0; i < ${#confnames[@]}; i++))
	do
		conf=${confnames[$i]}
		echo "SYSCONF($conf)" >> $conf_list
	done
}

for_each_conf
