#!/bin/bash
# generate all sysconf test code

function for_each_conf()
{
	if [[ ! -e /usr/include/bits/confname.h ]]; then
		echo "ERROR: /usr/include/bits/confname.h is not exist"
		exit 1
	fi

	confnames=( $(cat /usr/include/bits/confname.h | awk '{
			if ($1=="#define" && $2==$3)
				print $2
			}'
			)
		)
	local conf_list=confs_def.h

cat >$conf_list <<-EOF
/* Generated by test-linux */
#if !defined(SYSCONF)
#error Not defined SYSCONF(conf)
#endif
EOF

	for ((i = 0; i < ${#confnames[@]}; i++))
	do
		conf=${confnames[$i]}
cat >>$conf_list <<-EOF
#if defined($conf)
SYSCONF($conf)
#else
# warning Undefined $conf
#endif
EOF
	done
}

for_each_conf
