target-shell-y := memory.sh
target-shell-y += oem.sh
target-shell-y += power.sh
target-shell-y += product.sh
target-shell-y += serial-number.sh
target-shell-y += string.sh
target-shell-y += type.sh

include ../../../template/main.mk
