targets-shell += memory.sh
targets-shell += oem.sh
targets-shell += power.sh
targets-shell += product.sh
targets-shell += serial-number.sh
targets-shell += string.sh
targets-shell += type.sh

include ../../../template/main.mk
