TARGETS_SHELL += memory.sh
TARGETS_SHELL += oem.sh
TARGETS_SHELL += power.sh
TARGETS_SHELL += product.sh
TARGETS_SHELL += serial-number.sh
TARGETS_SHELL += string.sh
TARGETS_SHELL += type.sh

include ../../../template/main.mk
