# SPDX-License-Identifier: GPL-3.0
targets :=
targets += if_indextoname
targets += if_nametoindex
targets += if_nameindex

CFLAGS :=

LDFLAGS :=

include ../../../template/main.mk

if_indextoname: if_indextoname.o
if_nametoindex: if_nametoindex.o
if_nameindex: if_nameindex.o
