# SPDX-License-Identifier: GPL-3.0
target-y :=
target-y += if_indextoname
target-y += if_nametoindex
target-y += if_nameindex

CFLAGS :=

LDFLAGS :=

include ../../../template/main.mk

if_indextoname: if_indextoname.o
if_nametoindex: if_nametoindex.o
if_nameindex: if_nameindex.o
