TARGETS :=
TARGETS += duplicate-decl-specifier
TARGETS += no-warn
TARGETS += no-error

CFLAGS_duplicate-decl-specifier := -Wduplicate-decl-specifier
CFLAGS_no-warn := -Wno-warn -Wno-warning
CFLAGS_no-error := -Wno-error

include ../../template/main.mk

duplicate-decl-specifier: duplicate-decl-specifier.o
no-warn: no-warn.o
no-error: no-error.o
