sub-dir := simple
sub-dir += select
sub-dir += epoll
sub-dir += poll
sub-dir += splice
sub-dir += ftp
sub-dir += ipv6

target-y += tcp-syn-flood

include ../../../template/main.mk

tcp-syn-flood: tcp-syn-flood.o
