target-y :=
target-y += cgroup_version
target-y += cgroup_get_subsys_mount_point
target-y += cgroup_new_cgroup

include ../libcgroup.mk
include ../../../template/main.mk

cgroup_version: cgroup_version.o
cgroup_get_subsys_mount_point: cgroup_get_subsys_mount_point.o
cgroup_new_cgroup: cgroup_new_cgroup.o
