target-shell-y := env.sh
target-shell-y += env.sh.1

SHELL_ENVS_env.sh := -e TEST_LINUX_TEMPLATE_TARGETS_SHELL_ENV=rtoax
SHELL_ENVS_env.sh.1 := ${SHELL_ENVS_env.sh}

SHELL_ARGS_env.sh := abc
SHELL_ARGS_env.sh.1 := def

include main.mk
