#!/bin/bash
set -e

. /boot/config-$(uname -r)

lsm=( $(cat /sys/kernel/security/lsm | tr ',' ' ') )

echo security lsm=${lsm[@]}
echo CONFIG_LSM=${CONFIG_LSM}
echo CONFIG_BPF_LSM=${CONFIG_BPF_LSM}
echo CONFIG_BPF_SYSCALL=${CONFIG_BPF_SYSCALL}
echo CONFIG_DEFAULT_SECURITY=${CONFIG_DEFAULT_SECURITY}
echo CONFIG_SECURITY_APPARMOR=${CONFIG_SECURITY_APPARMOR}
echo CONFIG_SECURITY_LOADPIN=${CONFIG_SECURITY_LOADPIN}
echo CONFIG_SECURITY_SELINUX=${CONFIG_SECURITY_SELINUX}
echo CONFIG_SECURITY_TOMOYO=${CONFIG_SECURITY_TOMOYO}
echo CONFIG_SECURITY_YAMA=${CONFIG_SECURITY_YAMA}
echo CONFIG_SECURITY_IPE=${CONFIG_SECURITY_IPE}
