targets := select
targets += heap-1 heap-2
targets += insert
targets += merge
targets += quick-1 quick-2

include ../../template/main.mk

select: select.o
heap-1: heap-1.o
heap-2: heap-2.o
insert: insert.o
merge: merge.o
quick-1: quick-1.o
quick-2: quick-2.o
