include ../../../tlbuild.mk


sub-dir := rate
sub-dir += simple
sub-dir += select

include ../../../template/subdir-header.mk

.PHONY: build
all: $(sub-dir-build)

.PHONY: clean
clean: $(sub-dir-clean)

include ../../../template/subdir-footer.mk
