#!/bin/bash
set -e

# Match format: 'node   0: mem 0x0000000000001000-0x000000000009efff]'
dmesg_node_mem_raw()
{
	sudo dmesg | \
		grep -oe "node[[:space:]]\{1,\}[[:digit:]]\{1,2\}: \[mem 0x[0-9a-fA-F]\{16\}-0x[0-9a-fA-F]\{16\}\]"
}

dmesg_node_mem_pure()
{
	dmesg_node_mem_raw | tr '[:\-]' ' '
}

dmesg_node_mem_c()
{
	dmesg_node_mem_pure | awk '
		BEGIN {
			print("/* Generated by test-linux */")
			print("#pragma once")
			print("")
			print("struct numa_mem_info {")
			print("\tint nid;")
			print("\tunsigned long mem_start, mem_end;")
			print("};")
			print("")
			print("static struct numa_mem_info __attribute__((unused)) numa_mem_info[] = {")
		}
		{
			print("\t{")
			print("\t\t.nid = "$2",")
			print("\t\t.mem_start = "$4",")
			print("\t\t.mem_end = "$5",")
			print("\t},")
		}
		END {
			print("};")
		}
		' | tee numa_mem.h
}

case $1 in
raw)
	dmesg_node_mem_raw
	;;
pure)
	dmesg_node_mem_pure
	;;
c)
	dmesg_node_mem_c
	;;
*)
	echo >&2 "Usage: $0 [raw|pure|c]"
	exit 1
	;;
esac
