target-y += fgetgrent
target-y += getgrent
target-y += getgrgid
target-y += getgrnam
target-y += getgrouplist
target-y += initgroups
target-y += setgrent
target-y += getgroups
target-y += demo-pwd-grp

include main.mk
