TARGETS :=
TARGETS += hsearch
TARGETS += lfind
TARGETS += tsearch

CFLAGS := -Werror -Wall
CFLAGS += -D_GNU_SOURCE

include ../../template/main.mk

hsearch: hsearch.o
lfind: lfind.o
tsearch: tsearch.o
