sub-dir := poll
sub-dir += epoll
sub-dir += iovec
sub-dir += proxy
sub-dir += syscall
sub-dir += unix
sub-dir += tcp
sub-dir += sctp
sub-dir += udp
sub-dir += ipv6

sub-dir-build := $(sub-dir:=.build)
sub-dir-clean := $(sub-dir:=.clean)

.PHONY: build
build: $(sub-dir-build)

.PHONY: clean
clean: $(sub-dir-clean)

$(sub-dir-build):
	@echo -e "\033[1;32m [sub-dir] build $(@)\033[m"
	make -C $(@:.build=)
$(sub-dir-clean):
	@echo -e "\033[1;32m [sub-dir] clean $(@)\033[m"
	make -C $(@:.clean=) clean
