# Copyright (C) Rong Tao
include kconfig.mk

ifeq ($(CONFIG_LIVEPATCH),y)
  LIVEPATCH := m
endif

obj-$(LIVEPATCH) += kallsyms_example.o
kallsyms_example-objs := main.o kallsyms.o

MCFLAGS += -g
ccflags-y += ${MCFLAGS}
CC += ${MCFLAGS}
