# SPDX-License-Identifier: GPL-3.0
subdir-y :=
subdir-y += awk
subdir-y += bc
subdir-y += dmesg
subdir-y += grep
subdir-y += lstopo
subdir-y += sar
subdir-y += sed
subdir-y += split
subdir-y += ssh-keygen
subdir-y += stat
subdir-y += makeself

target-shell-y := tr.sh

include main.mk
