targets := wait-wake
targets += requeue
targets += h2o
targets += spin
targets += latency

include ../../../template/main.mk

requeue: requeue.o
wait-wake: wait-wake.o
h2o: h2o.o
spin: spin.o
latency: latency.o
