TARGETS := wait-wake
TARGETS += requeue
TARGETS += h2o
TARGETS += spin
TARGETS += latency

include ../../../template/main.mk

requeue: requeue.o
wait-wake: wait-wake.o
h2o: h2o.o
spin: spin.o
latency: latency.o
