target-y :=
target-y += setpwent getpwent endpwent
target-y += putpwent
target-y += getpwnam
target-y += getpwuid
target-y += fgetpwent
target-y += demo-pwd-grp

CFLAGS :=

include ../../template/main.mk

setpwent: setpwent.o
getpwent: getpwent.o
endpwent: endpwent.o
putpwent: putpwent.o
getpwnam: getpwnam.o
getpwuid: getpwuid.o
fgetpwent: fgetpwent.o
demo-pwd-grp: demo-pwd-grp.o
