# SPDX-License-Identifier: GPL-3.0
targets-java :=
targets-java += hello.class
targets-java += malloc.class
targets-java += url_GET.class

include ../template/main.mk

hello.class: hello.java
malloc.class: malloc.java
url_GET.class: url_GET.java
