# SPDX-License-Identifier: GPL-3.0
TARGETS_JAVA :=
TARGETS_JAVA += hello.class
TARGETS_JAVA += malloc.class
TARGETS_JAVA += url_GET.class

include ../template/main.mk

hello.class: hello.java
malloc.class: malloc.java
url_GET.class: url_GET.java
