# SPDX-License-Identifier: GPL-3.0
target-java-y :=
target-java-y += hello.class
target-java-y += malloc.class
target-java-y += url_GET.class

include ../template/main.mk

hello.class: hello.java
malloc.class: malloc.java
url_GET.class: url_GET.java
