# SPDX-License-Identifier: GPL-3.0
subdir-y += debugfs
subdir-y += ext4
subdir-y += fat
subdir-y += overlayfs
subdir-y := procfs
subdir-y += sysfs
subdir-y += tracefs
subdir-y += vfs
subdir-y += xfs

include main.mk
