# SPDX-License-Identifier: GPL-3.0
subdir-y += io-sched
subdir-y += lvm
subdir-y += raid
subdir-y += scsi
subdir-y += nvme

target-shell-y := disk_examples.sh

target-y := partition-table

include main.mk
