# SPDX-License-Identifier: GPL-3.0

sub-dir := bitmask
sub-dir += bitops
sub-dir += fft
sub-dir += hashmap
sub-dir += list
sub-dir += linklist
sub-dir += rbtree
sub-dir += md5
sub-dir += math
sub-dir += string
sub-dir += sort
sub-dir += search

targets :=
targets += pi

CFLAGS :=
CFLAGS += -I../macro/

include ../template/main.mk

pi: pi.o
