#!/bin/bash
set -ex

# 1. [#1855] -DENABLE_LLVM_SHARED=1
# 2. MUST care about bpf_prog_load(),
#    replace bpf_prog_load to bpf_prog_load_v0_6_0.
cmake \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DENABLE_LLVM_SHARED=1 \
	-DCMAKE_BUILD_TYPE=Debug \
	..

make -j$(($(nproc) / 2))
sudo make install
