#!/bin/bash
set -ex

. /etc/os-release

pkgs_deb+=(
	libclang-cpp-dev libclang-dev
	libclang-cpp19-dev libclang-19-dev
	libdebuginfod-dev
)

pkgs_rpm+=(
	netperf
)

case ${ID} in
debian | ubuntu)
	sudo apt install -y ${pkgs_deb[@]}
	;;
fedora)
	sudo dnf install -y ${pkgs_rpm[@]}
	;;
*)
	;;
esac

# 1. [#1855] -DENABLE_LLVM_SHARED=1
# 2. MUST care about bpf_prog_load(),
#    replace bpf_prog_load to bpf_prog_load_v0_6_0.
cmake \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DENABLE_LLVM_SHARED=1 \
	-DCMAKE_BUILD_TYPE=Debug \
	${PYTHON_CMD:+-DPYTHON_CMD=${PYTHON_CMD}} \
	..

make -j$(nproc)
sudo make install
