#!/bin/bash
set -ex

. /etc/os-release

deb_pkgs() {
	sudo apt-get install -y \
		googletest \
		asciidoctor \
		binutils-dev \
		bison \
		build-essential \
		clang \
		cmake \
		flex \
		google-mock \
		googletest \
		libbpf-dev \
		libbpfcc-dev \
		libcereal-dev \
		libdw-dev \
		libelf-dev \
		libgtest-dev \
		libgmock-dev \
		libiberty-dev \
		libpcap-dev \
		llvm-dev \
		liblldb-dev \
		libclang-dev \
		systemtap-sdt-dev \
		xxd \
		zlib1g-dev
}

rpm_pkgs() {
	sudo dnf install -y --skip-broken \
		blazesym-c-devel \
		rubygem-asciidoctor
}

declare -a cmake_args

if [[ " debian ubuntu " =~ " ${ID} " ]]; then
	deb_pkgs
	# FIXME: update Debian 12 llvm version here
	cmake_args+=( -DLLVM_REQUESTED_VERSION=19.1.14 )
	cmake_args+=( -DLLVM_DIR=/usr/lib/llvm-19/cmake/ )
elif [[ " rhel centos fedora " =~ " ${ID} " ]]; then
	rpm_pkgs
fi

cmake \
	-DCMAKE_INSTALL_PREFIX=/usr/ \
	-DCMAKE_BUILD_TYPE=Debug \
	-DBUILD_TESTING=ON \
	${cmake_args[@]} \
	..

make -j$(nproc)
sudo make install
