#!/bin/bash
# compile bpftrace source code
set -e

readonly prog=bpftrace-compile

flags_deps=
flags_config=
flags_install=
flags_test=
use_jobs=$(nproc)
llvm_version=
llvm_dir=
verbose=

declare -a cmake_args

. /etc/os-release

run() {
	echo -e "\033[1;32m$ ${@}\033[m"
	eval "${@}"
}

deb_pkgs() {
	run sudo apt-get install -y \
		googletest \
		asciidoctor \
		binutils-dev \
		bison \
		build-essential \
		clang \
		cmake \
		flex \
		google-mock \
		googletest \
		libbpf-dev \
		libbpfcc-dev \
		libcereal-dev \
		libdw-dev \
		libelf-dev \
		libgtest-dev \
		libgmock-dev \
		libiberty-dev \
		libpcap-dev \
		llvm-dev \
		liblldb-dev \
		libclang-dev \
		python3-looseversion \
		systemtap-sdt-dev \
		xxd \
		zlib1g-dev
}

rpm_pkgs() {
	run sudo dnf install -y --skip-broken \
		blazesym-c-devel \
		python3-looseversion \
		rubygem-asciidoctor
}

__usage__()
{
	echo -e "
NAME
	${prog} - Compile bpftrace

SYNOPSIS
	${prog} [--deps] [--config] [--help] [--verbose]

DESCRIPTION
	Compile bpftrace.

ARGUMENT
	-d, --deps              install depends
	-c, --config            execute the config to generate Makefile
	-i, --install           execute the make install
	-t, --test              execute the bpftrace_test

	-j, --jobs [N]          set number of jobs, default: ${use_jobs}
	--llvm-version [N]      specify LLVM Version
	--llvm-dir [DIR]        specify LLVM directory, like: /usr/lib/llvm-18/
	--use-system-libbpf     use system libbpf instead of submodule
	-v, --verbose           run with verbose mode
	-h, --help              show this info

EXAMPLES
	$ ./compile -d -c -i --llvm-version=$(llvm-config --version) --llvm-dir=$(dirname $(llvm-config --libdir))/

LINKS
	https://github.com/bpftrace/bpftrace

SEE ALSO
	bpftrace(8)
"
	exit ${1-0}
}

TEMP_ARGS=$(getopt --options dcitj:vh \
	--long deps \
	--long config \
	--long install \
	--long test \
	--long jobs: \
	--long llvm-version: \
	--long llvm-dir: \
	--long use-system-libbpf \
	--long verbose \
	--long help \
	--name ${prog} -- "$@")

test $? != 0 && __usage__ 1

eval set -- "$TEMP_ARGS"

while true; do
	case $1 in
	-d | --deps)
		shift
		flags_deps=YES
		;;
	-c | --config)
		shift
		flags_config=YES
		;;
	-i | --install)
		shift
		flags_install=YES
		;;
	-t | --test)
		shift
		flags_test=YES
		;;
	-j | --jobs)
		shift
		use_jobs=$1
		shift
		;;
	--llvm-version)
		shift
		llvm_version=$1
		cmake_args+=( -DLLVM_REQUESTED_VERSION=${llvm_version} )
		shift
		;;
	--llvm-dir)
		shift
		llvm_dir=$1
		cmake_args+=( -DLLVM_DIR=${llvm_dir}/cmake/ )
		shift
		;;
	--use-system-libbpf)
		shift
		cmake_args+=( -DUSE_SYSTEM_LIBBPF=ON )
		;;
	-v | --verbose)
		shift
		verbose=YES
		;;
	-h | --help)
		shift
		__usage__
		;;
	--)
		shift
		break
		;;
	esac
done

if [[ ${verbose} ]]; then
	export PS4='+${BASH_SOURCE}:${LINENO}:${FUNCNAME[0]}: '
	set -x
fi

if [[ ${flags_deps} ]]; then
	if [[ " debian ubuntu " =~ " ${ID} " ]]; then
		deb_pkgs
	elif [[ " rhel centos fedora " =~ " ${ID} " ]]; then
		rpm_pkgs
	fi
fi

if [[ ${flags_config} ]]; then
	run cmake \
		-DCMAKE_INSTALL_PREFIX=/usr/ \
		-DCMAKE_BUILD_TYPE=Debug \
		-DBUILD_TESTING=ON \
		${cmake_args[@]} \
		..
fi

# Must execute make command at least
run make -j${use_jobs} ${verbose:+VERBOSE=1}

[[ ${flags_install} ]] && run sudo make install

# Check for the clang-format
run git clang-format --diff origin/master --extensions cpp,h

if [[ ${flags_test} ]]; then
	run sudo ./tests/bpftrace_test
fi
