TARGETS :=
TARGETS += msgsnd
TARGETS += msgctl
TARGETS += msg_server msg_client
TARGETS += fork-trigger

include ../../../../template/main.mk

msgsnd: msgsnd.o
msgctl: msgctl.o
msg_server: msg_server.o
msg_client: msg_client.o
fork-trigger: fork-trigger.o
