target-y :=
target-y += msgsnd
target-y += msgctl
target-y += msg_server msg_client
target-y += fork-trigger

include ../../../../template/main.mk

msgsnd: msgsnd.o
msgctl: msgctl.o
msg_server: msg_server.o
msg_client: msg_client.o
fork-trigger: fork-trigger.o
