include ../../../tlbuild.mk


sub-dir := simple
sub-dir += multicast
sub-dir += broadcast

include ../../../template/subdir-header.mk

.PHONY: build
build: $(sub-dir-build)

.PHONY: clean
clean: $(sub-dir-clean)

include ../../../template/subdir-footer.mk
