#!/bin/bash
# Copyright (C) 2024-2026 Rong Tao
#
# Usage:
# $ [FC=1] [NMOD=n] [NADD=n] [NDEL=n] git commit ...
# - FC: Force Commit
set -e

readonly GIT_TOPDIR=$(git rev-parse --show-toplevel 2>/dev/null || :)
readonly MY_DIRECTORY=$(realpath $(dirname $(realpath $0))/../../../)

# Usage: $ NMOD=6 git commit -s
[[ -z ${NMOD} ]] && NMOD=4
[[ -z ${NADD} ]] && NADD=1
[[ -z ${NDEL} ]] && NDEL=1
[[ -z ${FC} ]] && FC=

if [[ ${V} ]] || [[ ${V1} ]]; then
	set -x
fi

fatal() {
	echo >&2 -e "\033[1;31mFATAL: ${@}\033[0m"
	if [[ -z ${FC} ]]; then
		echo >&2 -e "FATAL: Try FC=1"
		exit 1
	fi
}

${MY_DIRECTORY}/scripts/clang-format.sh
${MY_DIRECTORY}/distro/README.md.check.sh

try_add=( $(git status --short | grep ^A | awk '{print $2}' || true) )
try_del=( $(git status --short | grep ^D | awk '{print $2}' || true) )
try_modify=( $(git status --short | grep ^M | awk '{print $2}' || true) )

# Redirect output to stderr.
exec 1>&2

hint_changelog() {
	if [[ -f ${GIT_TOPDIR}/CHANGELOG.md ]] &&
	  ! [[ -L ${GIT_TOPDIR}/CHANGELOG.md ]]; then
		if ! [[ " ${try_modify[@]} " =~ " CHANGELOG.md " ]]; then
			git status --short
			fatal "${@}" "you forgot modify CHANGELOG!!!"
		fi
	fi
	if [[ -f ${GIT_TOPDIR}/docs/CHANGELOG.md ]]; then
		if ! [[ " ${try_modify[@]} " =~ " docs/CHANGELOG.md " ]]; then
			git status --short
			fatal "${@}" "you forgot modify docs/CHANGELOG!!!"
		fi
	fi
	if [[ -f ${GIT_TOPDIR}/docs/en/CHANGELOG.md ]]; then
		if [[ ! " ${try_modify[@]} " =~ " docs/en/CHANGELOG.md " ]] ||
		   [[ ! " ${try_modify[@]} " =~ " docs/zh/CHANGELOG.md " ]]; then
			git status --short
			fatal "${@}" "you forgot modify docs/{en,zh}/CHANGELOG.md!!!"
		fi
	fi
}

broken_symlinks=( $(find ${GIT_TOPDIR} -xtype l) )
if [[ ${#broken_symlinks[@]} -ge 1 ]]; then
	fatal "Broken-symlink: ${broken_symlinks[@]}"
fi

for f in ${try_add[@]}
do
	[[ -d ${f} ]] && continue

	# true: for empty file
	read -r -N 8 bin < $f || true
	if [[ $bin == $'\x7f'ELF* ]]; then
		fatal "You are trying to add <$f> ELF file to git-tree, see git status."
	# ar file start from "!<arch>\n", see /usr/include/ar.h
	elif [[ $bin == $'!<arch>\n' ]]; then
		fatal "You are trying to add <$f> ar file to git-tree, see git status."
	elif [[ $bin == $'gmon'* ]]; then
		fatal "You are trying to add <$f> GNU prof performance file to git-tree, see git status."
	fi
	if [[ $(basename $f) == vmlinux.h ]]; then
		fatal "vmlinux.h is too big, generate it with bpftool command!!!"
	fi
	if [[ $(file $f | awk '{print $NF}') == data ]] && [[ -z ${FC} ]]; then
		fatal "$f is considered a data file!!!"
	fi
done

# modify,add,delete files, need modify CHANGELOG.md too
[[ ${#try_modify[@]} -ge ${NMOD} ]] && hint_changelog "<Modify too many files, try NMOD=100>"
[[ ${#try_del[@]} -ge ${NDEL} ]] && hint_changelog "<Delete files, try NDEL=100>"
[[ ${#try_add[@]} -ge ${NADD} ]] && hint_changelog "<Add files: ${try_add[@]}, try NADD=100>"

exit 0
