#!/bin/bash

try_add=( $(git status --short | grep ^A | awk '{print $2}') )

for f in ${try_add[@]}
do
	read -r -N 8 bin < $f
	if [[ $bin == $'\x7f'ELF* ]]; then
		echo "FATAL: You are trying to add <$f> ELF file to git-tree, see git status."
		exit 1
	fi
done
