#!/bin/bash
# Copyright (C) 2025-2026 Rong Tao
#
# Usage:
# $ [AV=1] [VCM=1] [FORCE/FCM=1] git commit ...
# - AV: Match all versions
# - VCM: Verbose mode of Commit Message
# - FORCE/FCM: Force mode of Commit Message
[[ ${VCM} ]] && set -x

[[ -z ${FCM} ]] && FCM=${FORCE}

readonly COMMIT_MSG_FILE=$1
readonly COMMIT_SOURCE=$2 # commit, merge
readonly COMMIT_SHA1=$3

readonly MY_DIRECTORY=$(dirname $(realpath $0))
readonly TOPDIR=$(realpath ${MY_DIRECTORY}/../../../)
readonly VERDIR=${TOPDIR}/scripts/version
readonly VERSH=${VERDIR}/version.sh
readonly first_nonempyline=$(sed -n '/[^[:space:]]/ { =; q }' ${COMMIT_MSG_FILE})
readonly first_commentline=$(sed -n '/^#/ { =; q }' ${COMMIT_MSG_FILE})
readonly signed_off_by_line=$(awk '/^Signed-off-by:/{print NR; exit}' ${COMMIT_MSG_FILE})

readonly UNCOMMITTED_FILES=( $( ${MY_DIRECTORY}/../uncommitted-files.sh ) )
readonly LAST_SUBMITTED_FILES=( $(git log -1 --oneline --name-only --pretty=format:) )

# Changed file list (new, deleted, added, modified)
declare -a CHANGED_FILES SHEBANGS
declare is_commit_amend

# Remove old Env first.
sed -i '/^Vers:/d' ${COMMIT_MSG_FILE}
sed -i '/^Envs:/d' ${COMMIT_MSG_FILE}

CHANGED_FILES+=( ${UNCOMMITTED_FILES[@]} )

# git commit --amend
if [ "$COMMIT_SOURCE" = "commit" ] && [ "$COMMIT_SHA1" = "HEAD" ]; then
	CHANGED_FILES+=( ${LAST_SUBMITTED_FILES[@]} )
	is_commit_amend=YES
fi

for f in ${CHANGED_FILES[@]}; do
	ext=${f##*.}

	# This file have no extension, try to get it's shebang.
	if [[ ${ext} == ${f} ]]; then
		shebang="$(grep ^'#!' ${TOPDIR}${f} 2>/dev/null | tr -d '#!' || true)"
		if [[ ! -z ${shebang} ]]; then
			SHEBANGS+=( ${shebang} )
		fi
	fi
done
readonly CHANGED_FILES_RO=( ${CHANGED_FILES[@]} )

Versions=""
Environments=""

fatal() {
	echo >&2 "FATAL: "${@}", try FCM=1/FORCE=1 or VCM=1"
	[[ -z ${FCM} ]] && exit 1
}

warning() {
	echo >&2 "WARNING: "${@}
}

# $1: specify mode, values: WEAK, STRONG
__add_ver() {
	local mode=$1
	shift

	[[ -z "${@}" ]] && fatal "Bad call of add_ver()"
	[[ -z ${CHANGED_FILES_RO} ]] && return 0

	if [[ -z "$(echo ${@} | grep -oE '[0-9]')" ]]; then
		local msg="Can't found version string from '${@}'"
		if [[ ${mode} == STRONG ]]; then
			fatal "${msg}"
		else
			warning "${msg}"
		fi
		# Return directly
		return 0
	fi

	# Already exist
	if [[ "${Versions}" =~ "${@}" ]]; then
		return 0
	fi

	[[ ${Versions} ]] && Versions+=", "
	Versions+="$@"
}
add_ver_weak() {
	__add_ver WEAK "$@"
}
add_ver() {
	__add_ver STRONG "$@"
}

add_env() {
	[[ -z ${CHANGED_FILES_RO} ]] && return 0

	[[ -z "${@}" ]] && return 0

	# Already exist
	if [[ "${Environments}" =~ "${@}" ]]; then
		return 0
	fi

	[[ ${Environments} ]] && Environments+=", "
	Environments+="$@"
}

# input some key words.
# echo "YES" if any key matched.
has_key() {
	local key

	[[ ${AV} ]] && echo "YES" && return 0

	for key in ${@}
	do
		# Match the whole word
		if [[ "$(echo ${CHANGED_FILES_RO[@]} | grep -wo ${key})" ]]; then
			echo "YES"
			return 0
		fi
		if [[ "$(echo ${SHEBANGS[@]} | grep -wo ${key})" ]]; then
			echo "YES"
			return 0
		fi
	done
	return 0
}

# input some extension words, such as c, cpp, sh, cu, bt
# echo matched input words
match_type() {
	local exts=( ${@} )

	[[ ${AV} ]] && echo "${exts[@]}" && return 0

	# a.c b.sh -> c sh
	local matched=( $(echo "${CHANGED_FILES_RO[@]##*.}" | \
				grep -o -w -E "$(echo ${exts[@]} | tr ' ' '|')") )

	echo ${matched[@]} | tr ' ' '\n' | sort -u
	return 0
}

# has content in patch
has_content() {
	local str

	[[ ${AV} ]] && echo "YES" && return 0

	for str in ${@}
	do
		# search the 'str' in patch
		if [[ "$(git status --verbose | grep -e '^+' -e '^-' | \
				grep -o ${str})" ]] ||
		   [[ "$(git diff --staged | grep -e '^+' -e '^-' | \
				grep -o ${str})" ]]; then
			echo "YES"
			return 0
		fi
	done
	return 0
}

# has content in patch, return the matched inputs words
match_content() {
	local str=( ${@} )

	[[ ${AV} ]] && echo "${str[@]}" && return 0

	local matches=( $(git status --verbose | \
				grep -e '^+' -e '^-' | \
				grep -o -w -E "$(echo ${str[@]} | tr ' ' '|')") )
	matches+=( $(git diff --staged | \
			grep -e '^+' -e '^-' | \
			grep -o -w -E "$(echo ${str[@]} | tr ' ' '|')") )

	echo ${matches[@]} | tr ' ' '\n' | sort -u
	return 0
}

linux_ver() { add_ver "Linux $(uname -r)"; }
os_ver() { add_ver "$(${VERDIR}/distro.sh)"; }
redis_ver() { add_ver "$(${VERDIR}/redis.sh --name) $(${VERDIR}/redis.sh)"; }
uefi_ver() { add_ver "UEFI Spec $(${VERDIR}/uefi.sh)"; }

cpu_env() { add_env "$(${TOPDIR}/cpu/cpuname.sh)"; add_env "$(uname -m)"; }
pid1_env() { add_env "pid1=$(cat /proc/1/comm)"; }
virt_env() { add_env "$(${TOPDIR}/virt/virttype.sh)"; }

if [[ -z ${signed_off_by_line} ]] && [[ ${COMMIT_SOURCE} != merge ]]; then
	fatal "must signed with -s/--signoff"
fi

if [[ -z ${signed_off_by_line} ]]; then
	warning "Skipping git hooks of prepare-commit-msg"
	exit 0
fi

# __main__
if [[ "$(match_type asm S)$(has_key asm arch insn cpu)" ]]; then
	cpu_env
	virt_env
fi

os_ver
linux_ver

if [[ "$(match_type qcow2 raw)$(has_key qcow qcow2 qcow3 qemu)" ]]; then
	virt_env
fi

if [[ "$(has_key redis)" ]]; then
	redis_ver
fi

if [[ "$(match_type efi)$(has_key uefi UEFI efi EFI)" ]]; then
	uefi_ver
fi

if [[ "$(has_key cuda nvidia)" ]]; then
	name=$(${TOPDIR}/hpc/nvidia/gpuname.sh)
	if [[ ! -z ${name} ]]; then
		add_env "${name}"
	fi
fi

if [[ "$(has_key cuda nvidia LUCA cestc CESTC)" ]]; then
	name=$(${TOPDIR}/hpc/cestc/lingspeed/gpuname.sh)
	if [[ ! -z ${name} ]]; then
		add_env "${name}"
	fi
fi

__new_ver() {
	local allkeys=( $(${VERSH} -K) )
	local allexts=( $(${VERSH} -E) )
	local swlist swkeys swexts
	local key ext sw

	swkeys+=( $(match_content ${allkeys[@]}) )
	swexts+=( $(match_type ${allexts[@]}) )

	[[ ${swkeys} ]] && swlist+=( $(${VERSH} --k2n "${swkeys[*]}") )
	[[ ${swexts} ]] && swlist+=( $(${VERSH} --e2n "${swexts[*]}") )
	swlist=( $(echo ${swlist[@]} | tr ' ' '\n' | sort -u) )

	for sw in ${swlist[@]}
	do
		add_ver "$(${VERSH} -n ${sw}) $(${VERSH} -n ${sw} -V)"
	done
}

__new_ver

# Add lines
if [[ ${Versions} ]]; then
	sed -i "$((${signed_off_by_line}+1))i Vers: ${Versions}" ${COMMIT_MSG_FILE} || {
		fatal "Failed handle Vers: ${Versions}"
	}
fi
if [[ ${Environments} ]]; then
	sed -i "$((${signed_off_by_line}+1))i Envs: ${Environments}" ${COMMIT_MSG_FILE} || {
		fatal "Failed handle Envs: ${Environments}"
	}
fi

# If only modify The Documentation, try add Commit Message Title
if [[ -z "$(git status --short | grep -v Documentation || :)" ]] && \
   [[ -z ${is_commit_amend} ]]; then
	doc_files=( $(git status --short | grep -Eo 'Documentation.*' | grep -vw conf.py) )
	doc_names=( $(for f in ${doc_files[@]}; do basename ${f}; done) )
	doc_dirs=( $(for f in ${doc_files[@]}; do basename $(dirname ${f}); done | sort -u ) )
	doc_label=$(IFS=,; echo "${doc_dirs[*]}")
	sed -i "1i Doc: ${doc_label}: update ${doc_names[*]}" ${COMMIT_MSG_FILE} || {
		fatal "Failed add commit message"
	}
fi
