#!/bin/bash
# Copyright (C) 2025-2026 Rong Tao
#
# Env: [VERBOSE2=1] [FORCE2=1] git commit ...
#
[[ ${VERBOSE2} ]] && set -x

readonly COMMIT_MSG_FILE=$1
readonly COMMIT_SOURCE=$2 # commit, merge
readonly COMMIT_SHA1=$3

readonly MY_DIRECTORY=$(dirname $(realpath $0))
readonly TOPDIR=$(realpath ${MY_DIRECTORY}/../../../)
readonly first_nonempyline=$(sed -n '/[^[:space:]]/ { =; q }' ${COMMIT_MSG_FILE})
readonly first_commentline=$(sed -n '/^#/ { =; q }' ${COMMIT_MSG_FILE})
readonly signed_off_by_line=$(awk '/^Signed-off-by:/{print NR; exit}' ${COMMIT_MSG_FILE})

readonly UNCOMMITTED_FILES=( $( ${MY_DIRECTORY}/../uncommitted-files.sh ) )
readonly LAST_SUBMITTED_FILES=( $(git log -1 --oneline --name-only --pretty=format:) )

# Changed file list (new, deleted, added, modified)
declare -a CHANGED_FILES

# Remove old Env first.
sed -i '/^Vers:/d' ${COMMIT_MSG_FILE}
sed -i '/^Envs:/d' ${COMMIT_MSG_FILE}

CHANGED_FILES+=( ${UNCOMMITTED_FILES[@]} )

# git commit --amend
if [ "$COMMIT_SOURCE" = "commit" ] && [ "$COMMIT_SHA1" = "HEAD" ]; then
	CHANGED_FILES+=( ${LAST_SUBMITTED_FILES[@]} )
fi

for f in ${CHANGED_FILES[@]}; do
	ext=${f##*.}
	# Remove documents, since document modifications typically do not
	# depend on the environment or software version, for example, if
	# you only modify README.md, there is no need to add Envs: and Vers:.
	if ! [[ " md log " =~ " ${ext} " ]]; then
		filter+=( ${f} )
	fi
done
readonly CHANGED_FILES_FILTEROUT=( ${filter[@]} )

Versions=""
Environments=""

fatal() {
	echo >&2 "FATAL: "${@}", set FORCE2=1 or VERBOSE2=1"
	[[ -z ${FORCE2} ]] && exit 1
}

warning() {
	echo >&2 "WARNING: "${@}
}

# $1: specify mode, values: WEAK, STRONG
__add_ver() {
	local mode=$1
	shift

	[[ -z "${@}" ]] && fatal "Bad call of add_ver()"
	[[ -z ${CHANGED_FILES_FILTEROUT} ]] && return 0

	if [[ -z "$(echo ${@} | grep -oE '[0-9]')" ]]; then
		local msg="Can't found version string from '${@}'"
		if [[ ${mode} == STRONG ]]; then
			fatal "${msg}"
		else
			warning "${msg}"
		fi
		# Return directly
		return 0
	fi

	# Already exist
	if [[ "${Versions}" =~ "${@}" ]]; then
		return 0
	fi

	[[ ${Versions} ]] && Versions+=", "
	Versions+="$@"
}
add_ver_weak() {
	__add_ver WEAK "$@"
}
add_ver() {
	__add_ver STRONG "$@"
}

add_env() {
	[[ -z ${CHANGED_FILES_FILTEROUT} ]] && return 0

	[[ -z "${@}" ]] && return 0

	# Already exist
	if [[ "${Environments}" =~ "${@}" ]]; then
		return 0
	fi

	[[ ${Environments} ]] && Environments+=", "
	Environments+="$@"
}

# input some key words.
# echo "YES" if any key matched.
have_key() {
	local key
	for key in ${@}
	do
		# Match the whole word
		if [[ "$(echo ${CHANGED_FILES_FILTEROUT[@]} | grep -wo ${key})" ]]; then
			echo "YES"
			return 0
		fi
	done
	return 0
}

# input some key words, such as c, cpp, sh, cu
# echo "YES" if any file type matched.
have_type() {
	local ext
	for ext in ${@}
	do
		# a.c b.sh -> c sh
		if [[ " ${CHANGED_FILES_FILTEROUT[@]##*.} " =~ " ${ext} " ]]; then
			echo "YES"
			return 0
		fi
	done
	return 0
}

cpu_info() {
	readonly CPU_MODEL=$(lscpu | grep -e "^Model name" -e "^型号名称" | \
			awk '{ for(i=3; i<=NF; i++) printf "%s", $i (i==NF ? "\n" : " ") }')
	readonly CPU_VENDOR=$(lscpu | grep -e "^Vendor ID" -e "^厂商 ID" | \
			awk '{ for(i=3; i<=NF; i++) printf "%s", $i (i==NF ? "\n" : " ") }')
	if [[ ${CPU_MODEL} ]]; then
		echo ${CPU_MODEL}
	elif [[ ${CPU_VENDOR} ]]; then
		echo ${CPU_VENDOR}
	else
		fatal "Can't get cpu info from lscpu"
	fi
}

add_bcc_ver() { add_ver "BCC $(${TOPDIR}/bpf/bcc/version.sh)"; }
add_bpftool_ver() { add_ver "bpftool $(${TOPDIR}/bpf/bpftool/version.sh)"; }
add_bpftrace_ver() { add_ver "BPFTrace $(${TOPDIR}/bpf/bpftrace/version.sh)"; }
add_cuda_ver() { add_ver "CUDA $(${TOPDIR}/hpc/nvidia/cuda/version.sh)"; }
add_gcc_ver() { add_ver "GCC $(${TOPDIR}/gnu/gcc/version.sh)"; }
add_git_ver() { add_ver "GIT $(${TOPDIR}/scripts/git/version.sh)"; }
add_glibc_ver() { add_ver "$(getconf GNU_LIBC_VERSION 2>/dev/null)"; }
add_gnome_ver() { add_ver "GNOME $(${TOPDIR}/gnome/version.sh)"; }
add_hpcc_ver() { add_ver_weak "HPCC $(${TOPDIR}/hpc/metax/hpcc/version.sh)"; }
add_libbpf_ver() { add_ver "LIBBPF $(${TOPDIR}/bpf/libbpf/version.sh)"; }
add_llvm_ver() { add_ver "LLVM $(${TOPDIR}/compiler/llvm/version.sh)"; }
add_luca_ver() { add_ver_weak "LUCA $(${TOPDIR}/hpc/cestc/luca/version.sh)"; }
add_make_ver() { add_ver "MAKE $(${TOPDIR}/gnu/make/version.sh)"; }
add_numactl_ver() { add_ver "NUMACTL $(${TOPDIR}/numa/numactl/version.sh)"; }
add_openssl_ver() { add_ver "OpenSSL $(${TOPDIR}/security/openssl/version.sh)"; }
add_os_ver() { add_ver "$(${TOPDIR}/distro/version.sh)"; }
add_pahole_ver() { add_ver "Pahole $(${TOPDIR}/pahole/version.sh)"; }
add_pciutils_ver() { add_ver "PCIUtils $(${TOPDIR}/driver/pcie/pciutils/version.sh)"; }
add_podman_ver() { add_ver "Podman $(${TOPDIR}/tools/podman/version.sh)"; }
add_py_ver() { add_ver "Python $(${TOPDIR}/python/version.sh)"; }
add_qemu_ver() { add_ver "QEMU $(${TOPDIR}/qemu/version.sh)"; }
add_rocm_ver() { add_ver_weak "ROCm $(${TOPDIR}/hpc/amd/rocm/version.sh)"; }
add_shell_ver() { add_ver "BASH $(${TOPDIR}/shell/version.sh)"; }
add_vim_ver() { add_ver "Vim $(${TOPDIR}/tools/vim/version.sh)"; }

if [[ -z ${signed_off_by_line} ]] && [[ ${COMMIT_SOURCE} != merge ]]; then
	fatal "must signed with -s/--signoff"
fi

if [[ -z ${signed_off_by_line} ]]; then
	warning "Skipping git hooks of prepare-commit-msg"
	exit 0
fi

# __main__
add_env "CPU $(cpu_info)"
add_env "Arch $(uname -m)"
add_env "$(${TOPDIR}/virt/virttype.sh)"

add_os_ver
add_ver "Linux $(uname -r)"

if [[ "$(have_type c cpp c++ h hpp)$(have_key gcc compiler)" ]]; then
	add_gcc_ver
fi

if [[ "$(have_type c cpp c++ h hpp)$(have_key glibc ipc socket)" ]]; then
	add_glibc_ver
fi

if [[ "$(have_type sh bash)$(have_key bash shell)" ]]; then
	add_shell_ver
fi

if [[ "$(have_key qcow qcow2 qcow3 qemu)" ]]; then
	add_qemu_ver
fi

if [[ "$(have_type mk make)$(have_key make Makefile)" ]]; then
	add_make_ver
fi

if [[ "$(have_key podman Dockerfile)" ]]; then
	add_podman_ver
fi

if [[ "$(have_key gnome)" ]]; then
	add_gnome_ver
fi

if [[ "$(have_type vim)$(have_key vim)" ]]; then
	add_vim_ver
fi

if [[ "$(have_key libbpf pahole)" ]]; then
	add_pahole_ver
fi

if [[ "$(have_key pci pcie)" ]]; then
	add_pciutils_ver
fi

if [[ "$(have_key git)" ]]; then
	add_git_ver
fi

if [[ "$(have_key numa numactl)" ]]; then
	add_numactl_ver
fi

if [[ "$(have_type bt)$(have_key bpftrace)" ]]; then
	add_bpftrace_ver
fi

if [[ "$(have_type pem)$(have_key ssl openssl)" ]]; then
	add_openssl_ver
fi

if [[ "$(have_key bpftool)" ]]; then
	add_bpftool_ver
fi

if [[ "$(have_key llvm bt nvidia)" ]]; then
	add_llvm_ver
fi

if [[ "$(have_key cuda nvidia)" ]]; then
	name=$(${TOPDIR}/hpc/nvidia/gpuname.sh)
	if [[ ! -z ${name} ]]; then
		add_env "${name}"
	fi
	add_cuda_ver
	add_llvm_ver
fi

if [[ "$(have_key cuda nvidia rocm amd ROCm AMD)" ]]; then
	add_rocm_ver
	add_llvm_ver
fi

if [[ "$(have_key cuda nvidia luca LUCA cestc CESTC)" ]]; then
	name=$(${TOPDIR}/hpc/cestc/lingspeed/gpuname.sh)
	if [[ ! -z ${name} ]]; then
		add_env "Lingspeed ${name}"
	fi
	add_luca_ver
	add_llvm_ver
fi

if [[ "$(have_key cuda nvidia hpcc HPCC metax MetaX)" ]]; then
	add_hpcc_ver
	add_llvm_ver
fi

if [[ "$(have_key libbpf bcc bpf)" ]]; then
	add_bcc_ver
	add_libbpf_ver
fi

if [[ "$(have_key python py)" ]]; then
	add_py_ver
fi

# Add lines
if [[ ${Versions} ]]; then
	sed -i "$((${signed_off_by_line}+1))i Vers: ${Versions}" ${COMMIT_MSG_FILE}
fi
if [[ ${Environments} ]]; then
	sed -i "$((${signed_off_by_line}+1))i Envs: ${Environments}" ${COMMIT_MSG_FILE}
fi
