#!/bin/bash
# Copyright (C) 2025-2026 Rong Tao
#
# Env: [FORCE=1] git commit ...
#

readonly COMMIT_MSG_FILE=$1
readonly COMMIT_SOURCE=$2 # commit, merge
readonly COMMIT_SHA1=$3

# Remove old Env first.
sed -i '/^Vers:/d' ${COMMIT_MSG_FILE}
sed -i '/^Envs:/d' ${COMMIT_MSG_FILE}

readonly MY_DIRECTORY=$(dirname $(realpath $0))
readonly TOPDIR=$(realpath ${MY_DIRECTORY}/../../../)
readonly first_nonempyline=$(sed -n '/[^[:space:]]/ { =; q }' ${COMMIT_MSG_FILE})
readonly first_commentline=$(sed -n '/^#/ { =; q }' ${COMMIT_MSG_FILE})
readonly signed_off_by_line=$(awk '/^Signed-off-by:/{print NR; exit}' ${COMMIT_MSG_FILE})
readonly LLVM_CONFIG=$(which llvm-config 2>/dev/null || :)

# Changed file list (new, deleted, added, modified)
CHANGED_FILES=( $( ${MY_DIRECTORY}/get-commit-file-list ) )

# git commit --amend
if [ "$COMMIT_SOURCE" = "commit" ] && [ "$COMMIT_SHA1" = "HEAD" ]; then
	CHANGED_FILES+=( $(git log -1 --oneline --name-only --pretty=format:) )
fi

for f in ${CHANGED_FILES[@]}; do
	ext=${f##*.}
	# Remove documents, since document modifications typically do not
	# depend on the environment or software version, for example, if
	# you only modify README.md, there is no need to add Envs: and Vers:.
	if ! [[ " md log " =~ " ${ext} " ]]; then
		filter+=( ${f} )
	fi
done
readonly CHANGED_FILES_FILTEROUT=( ${filter[@]} )

Versions=""
Environments=""

fatal() {
	echo >&2 "FATAL: "${@}", use FORCE=1 environment"
	[[ -z ${FORCE} ]] && exit 1
}

warning() {
	echo >&2 "WARNING: "${@}
}

add_ver() {
	[[ -z "${@}" ]] && fatal "Bad call of add_ver()"
	[[ -z ${CHANGED_FILES_FILTEROUT} ]] && return 0

	if [[ -z "$(echo ${@} | grep -oE '[0-9]')" ]]; then
		fatal "Can't found version in '${@}'"
		# Return directly if FORCE
		return 0
	fi

	# Already exist
	if [[ "${Versions}" =~ "${@}" ]]; then
		return 0
	fi

	[[ ${Versions} ]] && Versions+=", "
	Versions+="$@"
}
add_os_ver() {
	local os_env
	[[ ! -e /etc/os-release ]] && fatal "Not found /etc/os-release"

	. /etc/os-release
	os_env+="${NAME}"
	if [[ ${VERSION_ID} ]]; then
		os_env+=" ${VERSION_ID}"
	elif [[ ${VERSION} ]]; then
		os_env+=" ${VERSION}"
	fi
	add_ver "${os_env}"
}
add_gcc_ver() {
	add_ver "GCC $(${TOPDIR}/gnu/gcc/version.sh)"
}
add_llvm_ver() {
	if [[ ${LLVM_CONFIG} ]]; then
		local ver=$(${LLVM_CONFIG} --version)
		add_ver "LLVM ${ver}"
	fi
}
add_cuda_ver() {
	local ver=$(${TOPDIR}/hpc/nvidia/cuda/version.sh)
	add_ver "CUDA ${ver}"
}
add_rocm_ver() {
	local ver=$(${TOPDIR}/hpc/amd/rocm/version.sh)
	add_ver "ROCm ${ver}"
}
add_luca_ver() {
	local ver=$(${TOPDIR}/hpc/cestc/luca/version.sh)
	add_ver "LUCA ${ver}"
}
add_hpcc_ver() {
	local ver=$(${TOPDIR}/hpc/metax/hpcc/version.sh)
	add_ver "HPCC ${ver}"
}
add_glibc_ver() {
	add_ver "$(getconf GNU_LIBC_VERSION 2>/dev/null || :)"
}
add_shell_ver() {
	local ver=$(${TOPDIR}/shell/version.sh)
	add_ver "BASH ${ver}"
}
add_qemu_ver() {
	local ver=$(${TOPDIR}/qemu/version.sh)
	add_ver "QEMU ${ver}"
}
add_make_ver() {
	local ver=$(${TOPDIR}/gnu/make/version.sh)
	add_ver "MAKE ${ver}"
}
add_vim_ver() {
	local ver=$(${TOPDIR}/tools/vim/version.sh)
	add_ver "Vim ${ver}"
}
add_pahole_ver() {
	local ver=$(${TOPDIR}/pahole/version.sh)
	add_ver "Pahole ${ver}"
}
add_pciutils_ver() {
	local ver=$(${TOPDIR}/driver/pcie/pciutils/version.sh)
	add_ver "PCIUtils ${ver}"
}
add_git_ver() {
	local ver=$(${TOPDIR}/scripts/git/version.sh)
	add_ver "GIT ${ver}"
}
add_numactl_ver() {
	local ver=$(${TOPDIR}/numa/numactl/version.sh)
	add_ver "NUMACTL ${ver}"
}
add_bpftrace_ver() {
	local ver=$(${TOPDIR}/bpf/bpftrace/version.sh)
	add_ver "BPFTrace ${ver}"
}
add_bcc_ver() {
	local ver=$(${TOPDIR}/bpf/bcc/version.sh)
	add_ver "BCC ${ver}"
}
add_libbpf_ver() {
	local ver=$(${TOPDIR}/bpf/libbpf/version.sh)
	add_ver "LIBBPF ${ver}"
}
add_py_ver() {
	local ver=$(${TOPDIR}/python/version.sh)
	add_ver "Python ${ver}"
}

add_env() {
	[[ -z ${CHANGED_FILES_FILTEROUT} ]] && return 0

	[[ -z "${@}" ]] && return 0

	# Already exist
	if [[ "${Environments}" =~ "${@}" ]]; then
		return 0
	fi

	[[ ${Environments} ]] && Environments+=", "
	Environments+="$@"
}

# input some key words.
# echo "YES" if any key matched.
files_have_key() {
	local key
	for key in ${@}
	do
		# Match the whole word
		if [[ "$(echo ${CHANGED_FILES[@]} | grep -wo ${key})" ]]; then
			echo "YES"
			return 0
		fi
	done
	return 0
}

# input some key words, such as c, cpp, sh, cu
# echo "YES" if any file type matched.
files_have_type() {
	local ext
	for ext in ${@}
	do
		# a.c b.sh -> c sh
		if [[ " ${CHANGED_FILES[@]##*.} " =~ " ${ext} " ]]; then
			echo "YES"
			return 0
		fi
	done
	return 0
}


cpu_info() {
	readonly CPU_MODEL=$(lscpu | grep "Model name" | \
			awk '{ for(i=3; i<=NF; i++) printf "%s", $i (i==NF ? "\n" : " ") }')
	readonly CPU_VENDOR=$(lscpu | grep "^Vendor ID" | \
			awk '{ for(i=3; i<=NF; i++) printf "%s", $i (i==NF ? "\n" : " ") }')
	if [[ ${CPU_MODEL} ]]; then
		echo ${CPU_MODEL}
	elif [[ ${CPU_VENDOR} ]]; then
		echo ${CPU_VENDOR}
	else
		fatal "Can't get cpu info from lscpu"
	fi
}

if [[ -z ${signed_off_by_line} ]] && [[ ${COMMIT_SOURCE} != merge ]]; then
	fatal "must signed with -s/--signoff"
fi

if [[ -z ${signed_off_by_line} ]]; then
	warning "Skipping git hooks of prepare-commit-msg"
	exit 0
fi

# __main__
add_env "CPU $(cpu_info)"
add_env "Arch $(uname -m)"

SYSTEMD_DETECT_VIRT=$(which systemd-detect-virt 2>/dev/null || :)
if [[ ${SYSTEMD_DETECT_VIRT} ]]; then
	virt=$( ${SYSTEMD_DETECT_VIRT} )
	if [[ ${virt} != none ]]; then
		add_env "VIRT-${virt}"
	fi
fi

add_os_ver
add_ver "Linux $(uname -r)"

if [[ "$(files_have_type c cpp c++ h hpp)$(files_have_key gcc compiler)" ]]; then
	add_gcc_ver
fi

if [[ "$(files_have_type c cpp c++ h hpp)$(files_have_key glibc)" ]]; then
	add_glibc_ver
fi

if [[ "$(files_have_type sh bash)$(files_have_key bash shell)" ]]; then
	add_shell_ver
fi

if [[ "$(files_have_key qcow qcow2 qcow3 qemu)" ]]; then
	add_qemu_ver
fi

if [[ "$(files_have_type mk make)$(files_have_key make Makefile)" ]]; then
	add_make_ver
fi

if [[ "$(files_have_type vim)$(files_have_key vim)" ]]; then
	add_vim_ver
fi

if [[ "$(files_have_key libbpf pahole)" ]]; then
	add_pahole_ver
fi

if [[ "$(files_have_key pci pcie)" ]]; then
	add_pciutils_ver
fi

if [[ "$(files_have_key git)" ]]; then
	add_git_ver
fi

if [[ "$(files_have_key numa numactl)" ]]; then
	add_numactl_ver
fi

if [[ "$(files_have_type bt)$(files_have_key bpftrace)" ]]; then
	add_bpftrace_ver
fi

if [[ "$(files_have_key llvm bt nvidia)" ]]; then
	add_llvm_ver
fi

if [[ "$(files_have_key cuda nvidia)" ]]; then
	add_cuda_ver
	add_llvm_ver
fi

if [[ "$(files_have_key cuda nvidia rocm amd ROCm AMD)" ]]; then
	add_rocm_ver
	add_llvm_ver
fi

if [[ "$(files_have_key cuda nvidia luca LUCA cestc CESTC)" ]]; then
	add_luca_ver
	add_llvm_ver
fi

if [[ "$(files_have_key cuda nvidia hpcc HPCC metax MetaX)" ]]; then
	add_hpcc_ver
	add_llvm_ver
fi

if [[ "$(files_have_key libbpf bcc bpf)" ]]; then
	add_bcc_ver
	add_libbpf_ver
fi

if [[ "$(files_have_key python py)" ]]; then
	add_py_ver
fi

# Add lines
if [[ ${Versions} ]]; then
	sed -i "$((${signed_off_by_line}+1))i Vers: ${Versions}" ${COMMIT_MSG_FILE}
fi
if [[ ${Environments} ]]; then
	sed -i "$((${signed_off_by_line}+1))i Envs: ${Environments}" ${COMMIT_MSG_FILE}
fi
