include kconfig.mk

ifeq ($(CONFIG_PREEMPT),y)
  PREEMPT := m
else
  $(warning WARNING: CONFIG_PREEMPT is not set, these modules will cause soft lockup)
endif

obj-m += loop.o
obj-m += timer_list.o
obj-m += rcu_stall.o
