sub-dir := mkdocs
sub-dir += numpy
sub-dir += os
sub-dir += sys

targets-shell := calendar.sh

targets-python := hexdump.py
targets-python += listdir.py
targets-python += print.py
targets-python += split.py

include ../template/main.mk
