subdir-y := mkdocs
subdir-y += numpy
subdir-y += os
subdir-y += sys

target-shell-y := calendar.sh

target-python-y := hexdump.py
target-python-y += listdir.py
target-python-y += print.py
target-python-y += split.py

include ../template/main.mk
