#include <stdio.h>
#include <linux/kvm.h>

int main()
{
#define P(ioctl)	printf("%30s = 0x%016lx\n", #ioctl, ioctl)
	P(KVM_SET_MEMORY_REGION);
	P(KVM_CREATE_VCPU);
	P(KVM_GET_DIRTY_LOG);
	P(KVM_SET_MEMORY_ALIAS);
	P(KVM_SET_NR_MMU_PAGES);
	P(KVM_GET_NR_MMU_PAGES);
	P(KVM_SET_USER_MEMORY_REGION);
	P(KVM_SET_TSS_ADDR);
	P(KVM_SET_IDENTITY_MAP_ADDR);
	P(KVM_CREATE_IRQCHIP);
	P(KVM_IRQ_LINE);
	P(KVM_GET_IRQCHIP);
	P(KVM_SET_IRQCHIP);
	P(KVM_CREATE_PIT);
	P(KVM_GET_PIT);
	P(KVM_SET_PIT);
	P(KVM_IRQ_LINE_STATUS);
	P(KVM_REGISTER_COALESCED_MMIO);
	P(KVM_RUN);
	P(KVM_GET_XSAVE);
	P(KVM_SET_XSAVE);
	P(KVM_SIGNAL_MSI);
	return 0;
}

