#!/bin/bash
answer=N
[[ ! -z $1 ]] && answer=$1

declare -a no_commit_files ignore_files

get_no_commit_files() {
	no_commit_files=( $(git status --porcelain | grep '^??' | cut -c4- | tr -d ' ') )
}

get_ignore_files() {
	ignore_files=( $(git clean -dfx --dry-run | sed 's/Would remove//g' | tr -d ' ') )
}

print_list() {
	local list=( $@ )
	local i
	for ((i = 0; i < ${#list[@]}; i++))
	do
		printf "\t%s\n" ${list[$i]}
	done
}

pre_check() {
	get_no_commit_files
	get_ignore_files

	if [[ -z "${no_commit_files[@]}" ]] && [[ -z "${ignore_files[@]}" ]]; then
		echo "Nothing to clean"
		exit 0
	fi

	if [[ "${no_commit_files[@]}" ]]; then
		echo "Files not committed will be removed:"
		print_list ${no_commit_files[@]}
	fi

	if [[ "${ignore_files[@]}" ]]; then
		echo "Files ignored will be removed:"
		print_list ${ignore_files[@]}
	fi
}

if [[ ${answer} != y ]]; then
	while pre_check && read -p "Are you sure? [N/y] " answer
	do
		case $answer in
		[Yy]|[Yy][Ee]|[Yy][Ee][Ss])
			break
			;;
		[Nn]|[Nn][On])
			echo "Bye!"
			exit 0
			;;
		*)
			echo "WARNING: Unknown $answer"
			continue
			;;
		esac
	done
fi

sudo git clean -dfx
echo "Clean git"
