# Use template to compile kernel module.
include ${CURDIR}/Kbuild

KERNEL_DIR = /lib/modules/$(shell uname -r)/build
MODULE_DIR := ${CURDIR}

build:
	${Q}make -C $(KERNEL_DIR) M=$(MODULE_DIR) modules

clean:
	${Q}make -C $(KERNEL_DIR) M=$(MODULE_DIR) clean
