# Default support definitions
OUTPUT := .output/

include arch.mk
include ansi.mk

include ${CURDIR}/Build.mk

include	main.mk

ifneq ($(wildcard ${CURDIR}/Target.mk),)
  include ${CURDIR}/Target.mk
endif
