# Use template to default support some definitions, and include main.mk is not
# necessacy.
#
OUTPUT := .output/

include arch.mk
include ansi.mk

include ${CURDIR}/Build.mk

include	main.mk

# Target.mk is not necessacy.
ifneq ($(wildcard ${CURDIR}/Target.mk),)
  include ${CURDIR}/Target.mk
endif
