# Use template to default support some definitions, and include main.mk is not
# necessacy.

# subdirectory need USRC=y by default, see also top Makefile.
USRC ?= y

include output.mk
include arch.mk
include ansi.mk

ifeq (${USRC}, y)
  include ${CURDIR}/Build.mk
endif

include	main.mk

# Target.mk is not necessacy.
ifneq ($(wildcard ${CURDIR}/Target.mk),)
  include ${CURDIR}/Target.mk
endif
