# Use template to compile kernel module.
# define in top Makefile first time, however, under sub directory need KMOD=y
# bu default.
KMOD ?= y

include dir.mk
include shell.mk
include os.mk

ifeq (${KMOD}, y)
  include ${CURDIR}/Kbuild
endif

include main.mk

# Ktarget.mk is not necessacy.
ifneq ($(wildcard ${CURDIR}/Ktarget.mk),)
  include ${CURDIR}/Ktarget.mk
endif
