# SPDX-License-Identifier: GPL-3.0
target-y :=
target-y += setxattr
target-y += getxattr
target-y += listxattr
target-y += demo-1

include ../../../template/main.mk

setxattr: setxattr.o
getxattr: getxattr.o
listxattr: listxattr.o
demo-1: demo-1.o
