# SPDX-License-Identifier: GPL-3.0
TARGETS :=
TARGETS += setxattr
TARGETS += getxattr
TARGETS += listxattr
TARGETS += demo-1

include ../../../template/main.mk

setxattr: setxattr.o
getxattr: getxattr.o
listxattr: listxattr.o
demo-1: demo-1.o
