#!/usr/bin/expect -f
set timeout 5

# start program
spawn top

# set window size
trap {
	set rows 30
	set cols 100
	stty rows $rows columns $cols
} WINCH

proc test_init {pattern} {
	global timeout
	expect {
		"$pattern" { send_user "Found $pattern\n" }
		timeout { send_user "FAIL: top\n"; exit 1 }
	}
}

test_init "top"
test_init "Tasks:"
test_init "%Cpu(s):"
test_init "PID"
test_init "USER"

# send key
send "1"
expect {
	"%Cpu0" { send_user "Found %Cpu0\n" }
	timeout { send_user "FAIL: for key 1\n"; exit 1 }
}

# send q
send "q"
expect eof
puts "PASS"
