# SPDX-License-Identifier: GPL-3.0
include ../../tlbuild.mk
# =============================================================================

ifdef TLBUILD_TLCONFIG
TLconfig := ${TLBUILD_TLCONFIG}
else
TLconfig := TLconfig
endif
