# SPDX-License-Identifier: GPL-3.0
SHELL = bash
# =============================================================================

ifdef TLBUILD_TLCONFIG
TLconfig := ${TLBUILD_TLCONFIG}
else
TLconfig := TLconfig
endif
