# SPDX-License-Identifier: GPL-3.0
include ../../tlbuild.mk
# =============================================================================

ifdef TLBUILD_TLCONFIG
  TLCONFIG := ${TLBUILD_TLCONFIG}
else
  TLCONFIG := tlconfig
endif
