TARGETS := IPPORT_
TARGETS += inet6_opt_
TARGETS += inet6_rth_

CFLAGS := -Werror -Wall -D_GNU_SOURCE

include ../../../template/main.mk

IPPORT_: IPPORT_.o
inet6_opt_: inet6_opt_.o
inet6_rth_: inet6_rth_.o
