site_name: test-linux Docs
site_url: https://github.com/rtoax/test-linux
repo_url: https://github.com/rtoax/test-linux
repo_name: rtoax/test-linux
copyright: Copyright &copy; 2021 - 2024 RToax

nav:
  - Home: index.md
  - Test: test.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    # - navigation.instant  # see https://github.com/ultrabug/mkdocs-static-i18n/issues/62
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
    - content.action.view
    - content.action.edit
    - content.tabs.link
    - content.code.copy
    - content.code.select
    - content.code.annotations

markdown_extensions:
  # Officially Supported Extensions
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - sane_lists
  - tables
  - toc:
      permalink: true
  - wikilinks
  # Third Party Extensions(Bundles, PyMdown Extensions)
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

