#!/bin/bash
WORK_DIR=${PWD}
U_BOOT_DIR=/home/rongtao/Git/u-boot
LINUX_KERNEL_DIR=/home/rongtao/Git/linux
TURST_FIRMWARE_A_DIR=/home/rongtao/Git/trusted-firmware-a

# OS aarch64 ISO
OS_ISO_AARCH64=/home/isos/Fedora-aarch64-dvd.iso
OS_ISO_DIR_AARCH64=/home/isos/
OS_AARCH64_GRUBAA64_EFI=${OS_ISO_DIR_AARCH64}/EFI/BOOT/grubaa64.efi
OS_AARCH64_GRUB_CFG=${OS_ISO_DIR_AARCH64}/EFI/BOOT/grub.cfg
OS_AARCH64_IMAGE_DIR=${OS_ISO_DIR_AARCH64}/images/
UBOOTDISK_PARTITION1_FILES_OS=(
	${OS_AARCH64_IMAGE_DIR}
	${OS_AARCH64_GRUBAA64_EFI}
	${OS_AARCH64_GRUB_CFG}
)

# BM1684
# Link: https://github.com/p7salon/linux-arm64.git
BM1684_ROOT=/home/rongtao/Git/p7salon/linux-arm64.build.1/bm1684
BM1684_KERNEL_IMAGE=${BM1684_ROOT}/normal/arch/arm64/boot/Image
BM1684_KERNEL_IMAGE_GZ=${BM1684_ROOT}/normal/arch/arm64/boot/Image.gz
BM1684_DTB=${BM1684_ROOT}/normal/arch/arm64/boot/dts/bitmain/bm1684_sm5_v1.2_tb.dtb
UBOOTDISK_PARTITION1_FILES_BM1684=(
	${BM1684_KERNEL_IMAGE}
	${BM1684_KERNEL_IMAGE_GZ}
	${BM1684_DTB}
)

UBOOTDISK_PARTITION1_FILES=( ${UBOOTDISK_PARTITION1_FILES_OS[@]} )

