TARGETS :=
TARGETS += getopt
TARGETS += getopt_long getopt_long-in
TARGETS += getsubopt
TARGETS += demo-wls
TARGETS += demo-clr

CFLAGS :=

include ../../template/main.mk

getopt: getopt.o
getopt_long: getopt_long.o
getopt_long-in: getopt_long-in.o
getsubopt: getsubopt.o
demo-wls: demo-wls.o
demo-clr: demo-clr.o
