targets := getfsent
targets += getfsfile
targets += getfsspec
targets += setfsent

CC := gcc

CFLAGS :=

include ../../template/main.mk

getfsent: getfsent.o
getfsfile: getfsfile.o
getfsspec: getfsspec.o
setfsent: setfsent.o
