TARGETS := getfsent
TARGETS += getfsfile
TARGETS += getfsspec
TARGETS += setfsent

CC := gcc

CFLAGS :=

include ../../template/main.mk

getfsent: getfsent.o
getfsfile: getfsfile.o
getfsspec: getfsspec.o
setfsent: setfsent.o
