target-y := gai_strerror
target-y += getaddrinfo
target-y += gethostbyaddr
target-y += gethostbyname gethostbyname_r gethostbyname-2
target-y += getservbyport getservbyname
target-y += hstrerror
target-y += setservent
target-y += setnetent
target-y += sethostent
target-y += innetgr
target-y += getprotoent getprotobyname getprotobynumber
target-y += getnetbyname
target-y += getipnodebyname
target-y += herror
target-y += getnameinfo

gethostbyaddr-objs := netdb_helpers.o
gethostbyname-objs := netdb_helpers.o
gethostbyname_r-objs := netdb_helpers.o
getservbyport-objs := netdb_helpers.o
getservbyname-objs := netdb_helpers.o
setnetent-objs := netdb_helpers.o
getprotoent-objs := netdb_helpers.o
getprotobynumber-objs := netdb_helpers.o
getprotobyname-objs := netdb_helpers.o
getnetbyname-objs := netdb_helpers.o
