// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
/* Copyright (C) 2026 Rong Tao */
#ifndef __CUDA_ADAPTER_CUDA_H
#define __CUDA_ADAPTER_CUDA_H 1

/**
 * TODO: Adapt to multi CUDA versions
 */
#ifndef CUDA_VERSION
#define CUDA_VERSION 13000
#endif

#include "wrapper_defs.h"

/**
 * CUDA: typedef enum cudaError_enum { ... } CUresult;
 * LUCA: typedef enum lcc_status { ... } lcc_status_t;
 * HIP: enum { HIP_SUCCESS = 0, ... };
 *
 * Note: In fact, HIP does not provide a CUresult type that is compatible
 * with CUDA.
 */
/**
 * CUDA 13: typedef CUdevice_v1 CUdevice;
 */
/**
 * CUDA: typedef struct CUmod_st *CUmodule;
 * LUCA: typedef struct LCmod_st *LCmodule;
 */
/**
 * CUDA: typedef struct CUfunc_st *CUfunction;
 * LUCA: typedef struct LCfunc_st *LCfunction;
 */
/**
 * CUDA: typedef enum CUjit_option_enum {...} CUjit_option;
 */
#if defined(__USE_HPCC__)
# include "driver_types.h"
# define CUresult hcError_t
# define CUdevice hcDevice_t
# define CUmodule hcModule_t
# define CUfunction hcFunction_t
# define CUjit_option hcJitOption
#elif defined(__USE_LUCA__)
# include "driver_types.h"
# define CUresult lcError_t
# define CUdevice lcDevice_t
# define CUmodule lcModule_t
# define CUfunction lcFunction_t
# define CUjit_option lcJitOption
#elif defined(__USE_HIP__)
# include "driver_types.h"
/* Because hip_runtime_api.h: typedef struct ihipModule_t* hipModule_t; */
# include "cuda_runtime_api.h"
# define CUresult hipError_t
# define CUdevice hipDevice_t
# define CUmodule hipModule_t
# define CUfunction hipFunction_t
# define CUjit_option hipJitOption
#endif

/**
 * HIP: /usr/include/hip/amd_detail/amd_hip_runtime.h
 *      #define CUDA_SUCCESS hipSuccess
 */
#ifndef CUDA_SUCCESS
#define CUDA_SUCCESS cudaX(Success)
#endif
#define CUDA_ERROR_INVALID_VALUE cudaX(ErrorInvalidValue) /* 1 */
#define CUDA_ERROR_OUT_OF_MEMORY CUDA_ERROR_X(ERROR_OUT_OF_MEMORY) /* 2 */
#define CUDA_ERROR_NOT_INITIALIZED CUDA_ERROR_X(ERROR_NOT_INITIALIZED) /* 3 */
#define CUDA_ERROR_DEINITIALIZED CUDA_ERROR_X(ERROR_DEINITIALIZED)
#define CUDA_ERROR_PROFILER_DISABLED CUDA_ERROR_X(ERROR_PROFILER_DISABLED)
#define CUDA_ERROR_PROFILER_NOT_INITIALIZED \
	CUDA_ERROR_X(ERROR_PROFILER_NOT_INITIALIZED)
#define CUDA_ERROR_PROFILER_ALREADY_STARTED \
	CUDA_ERROR_X(ERROR_PROFILER_ALREADY_STARTED)
#define CUDA_ERROR_PROFILER_ALREADY_STOPPED \
	CUDA_ERROR_X(ERROR_PROFILER_ALREADY_STOPPED)
#define CUDA_ERROR_STUB_LIBRARY CUDA_ERROR_X(ERROR_STUB_LIBRARY)
#define CUDA_ERROR_CALL_REQUIRES_NEWER_DRIVER \
	CUDA_ERROR_X(ERROR_CALL_REQUIRES_NEWER_DRIVER)
#define CUDA_ERROR_DEVICE_UNAVAILABLE CUDA_ERROR_X(ERROR_DEVICE_UNAVAILABLE)
#define CUDA_ERROR_NO_DEVICE CUDA_ERROR_X(ERROR_NO_DEVICE)
#define CUDA_ERROR_INVALID_DEVICE CUDA_ERROR_X(ERROR_INVALID_DEVICE) /* 101 */
#define CUDA_ERROR_DEVICE_NOT_LICENSED CUDA_ERROR_X(ERROR_DEVICE_NOT_LICENSED)
#define CUDA_ERROR_INVALID_IMAGE CUDA_ERROR_X(ERROR_INVALID_IMAGE)
#define CUDA_ERROR_INVALID_CONTEXT CUDA_ERROR_X(ERROR_INVALID_CONTEXT)
#define CUDA_ERROR_CONTEXT_ALREADY_CURRENT \
	CUDA_ERROR_X(ERROR_CONTEXT_ALREADY_CURRENT)
#define CUDA_ERROR_MAP_FAILED CUDA_ERROR_X(ERROR_MAP_FAILED)
#define CUDA_ERROR_UNMAP_FAILED CUDA_ERROR_X(ERROR_UNMAP_FAILED)
#define CUDA_ERROR_ARRAY_IS_MAPPED CUDA_ERROR_X(ERROR_ARRAY_IS_MAPPED)
#define CUDA_ERROR_ALREADY_MAPPED CUDA_ERROR_X(ERROR_ALREADY_MAPPED)
#define CUDA_ERROR_NO_BINARY_FOR_GPU CUDA_ERROR_X(ERROR_NO_BINARY_FOR_GPU)
#define CUDA_ERROR_ALREADY_ACQUIRED CUDA_ERROR_X(ERROR_ALREADY_ACQUIRED)
#define CUDA_ERROR_NOT_MAPPED CUDA_ERROR_X(ERROR_NOT_MAPPED)
#define CUDA_ERROR_NOT_MAPPED_AS_ARRAY CUDA_ERROR_X(ERROR_NOT_MAPPED_AS_ARRAY)
#define CUDA_ERROR_NOT_MAPPED_AS_POINTER \
	CUDA_ERROR_X(ERROR_NOT_MAPPED_AS_POINTER)
#define CUDA_ERROR_ECC_UNCORRECTABLE CUDA_ERROR_X(ERROR_ECC_UNCORRECTABLE)
#define CUDA_ERROR_UNSUPPORTED_LIMIT CUDA_ERROR_X(ERROR_UNSUPPORTED_LIMIT)
#define CUDA_ERROR_CONTEXT_ALREADY_IN_USE \
	CUDA_ERROR_X(ERROR_CONTEXT_ALREADY_IN_USE)
#define CUDA_ERROR_PEER_ACCESS_UNSUPPORTED \
	CUDA_ERROR_X(ERROR_PEER_ACCESS_UNSUPPORTED)
#define CUDA_ERROR_INVALID_PTX CUDA_ERROR_X(ERROR_INVALID_PTX)
#define CUDA_ERROR_INVALID_GRAPHICS_CONTEXT \
	CUDA_ERROR_X(ERROR_INVALID_GRAPHICS_CONTEXT)
#define CUDA_ERROR_NVLINK_UNCORRECTABLE CUDA_ERROR_X(ERROR_NVLINK_UNCORRECTABLE)
#define CUDA_ERROR_JIT_COMPILER_NOT_FOUND \
	CUDA_ERROR_X(ERROR_JIT_COMPILER_NOT_FOUND)
#define CUDA_ERROR_UNSUPPORTED_PTX_VERSION \
	CUDA_ERROR_X(ERROR_UNSUPPORTED_PTX_VERSION)
#define CUDA_ERROR_JIT_COMPILATION_DISABLED \
	CUDA_ERROR_X(ERROR_JIT_COMPILATION_DISABLED)
#define CUDA_ERROR_UNSUPPORTED_EXEC_AFFINITY \
	CUDA_ERROR_X(ERROR_UNSUPPORTED_EXEC_AFFINITY)
#define CUDA_ERROR_UNSUPPORTED_DEVSIDE_SYNC \
	CUDA_ERROR_X(ERROR_UNSUPPORTED_DEVSIDE_SYNC)
#define CUDA_ERROR_CONTAINED CUDA_ERROR_X(ERROR_CONTAINED)
#define CUDA_ERROR_INVALID_SOURCE CUDA_ERROR_X(ERROR_INVALID_SOURCE)
#define CUDA_ERROR_FILE_NOT_FOUND CUDA_ERROR_X(ERROR_FILE_NOT_FOUND) /* 301 */
#define CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND \
	CUDA_ERROR_X(ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND)
#define CUDA_ERROR_SHARED_OBJECT_INIT_FAILED \
	CUDA_ERROR_X(ERROR_SHARED_OBJECT_INIT_FAILED)
#define CUDA_ERROR_OPERATING_SYSTEM CUDA_ERROR_X(ERROR_OPERATING_SYSTEM)
#define CUDA_ERROR_INVALID_HANDLE CUDA_ERROR_X(ERROR_INVALID_HANDLE) /* 400 */
#define CUDA_ERROR_ILLEGAL_STATE CUDA_ERROR_X(ERROR_ILLEGAL_STATE)
#define CUDA_ERROR_LOSSY_QUERY CUDA_ERROR_X(ERROR_LOSSY_QUERY)
#define CUDA_ERROR_NOT_FOUND CUDA_ERROR_X(ERROR_NOT_FOUND) /* 500 */
#define CUDA_ERROR_NOT_READY CUDA_ERROR_X(ERROR_NOT_READY)
#define CUDA_ERROR_ILLEGAL_ADDRESS CUDA_ERROR_X(ERROR_ILLEGAL_ADDRESS)
#define CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES \
	CUDA_ERROR_X(ERROR_LAUNCH_OUT_OF_RESOURCES)
#define CUDA_ERROR_LAUNCH_TIMEOUT CUDA_ERROR_X(ERROR_LAUNCH_TIMEOUT)
#define CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING \
	CUDA_ERROR_X(ERROR_LAUNCH_INCOMPATIBLE_TEXTURING)
#define CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED \
	CUDA_ERROR_X(ERROR_PEER_ACCESS_ALREADY_ENABLED)
#define CUDA_ERROR_PEER_ACCESS_NOT_ENABLED \
	CUDA_ERROR_X(ERROR_PEER_ACCESS_NOT_ENABLED)
#define CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE \
	CUDA_ERROR_X(ERROR_PRIMARY_CONTEXT_ACTIVE)
#define CUDA_ERROR_CONTEXT_IS_DESTROYED CUDA_ERROR_X(ERROR_CONTEXT_IS_DESTROYED)
#define CUDA_ERROR_ASSERT CUDA_ERROR_X(ERROR_ASSERT)
#define CUDA_ERROR_TOO_MANY_PEERS CUDA_ERROR_X(ERROR_TOO_MANY_PEERS)
#define CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED \
	CUDA_ERROR_X(ERROR_HOST_MEMORY_ALREADY_REGISTERED)
#define CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED \
	CUDA_ERROR_X(ERROR_HOST_MEMORY_NOT_REGISTERED)
#define CUDA_ERROR_HARDWARE_STACK_ERROR CUDA_ERROR_X(ERROR_HARDWARE_STACK_ERROR)
#define CUDA_ERROR_ILLEGAL_INSTRUCTION CUDA_ERROR_X(ERROR_ILLEGAL_INSTRUCTION)
#define CUDA_ERROR_MISALIGNED_ADDRESS CUDA_ERROR_X(ERROR_MISALIGNED_ADDRESS)
#define CUDA_ERROR_INVALID_ADDRESS_SPACE \
	CUDA_ERROR_X(ERROR_INVALID_ADDRESS_SPACE)
#define CUDA_ERROR_INVALID_PC CUDA_ERROR_X(ERROR_INVALID_PC)
#define CUDA_ERROR_LAUNCH_FAILED CUDA_ERROR_X(ERROR_LAUNCH_FAILED)
#define CUDA_ERROR_COOPERATIVE_LAUNCH_TOO_LARGE \
	CUDA_ERROR_X(ERROR_COOPERATIVE_LAUNCH_TOO_LARGE)
#define CUDA_ERROR_TENSOR_MEMORY_LEAK CUDA_ERROR_X(ERROR_TENSOR_MEMORY_LEAK)
#define CUDA_ERROR_NOT_PERMITTED CUDA_ERROR_X(ERROR_NOT_PERMITTED)
#define CUDA_ERROR_NOT_SUPPORTED CUDA_ERROR_X(ERROR_NOT_SUPPORTED)
#define CUDA_ERROR_SYSTEM_NOT_READY CUDA_ERROR_X(ERROR_SYSTEM_NOT_READY)
#define CUDA_ERROR_SYSTEM_DRIVER_MISMATCH \
	CUDA_ERROR_X(ERROR_SYSTEM_DRIVER_MISMATCH)
#define CUDA_ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE \
	CUDA_ERROR_X(ERROR_COMPAT_NOT_SUPPORTED_ON_DEVICE)
#define CUDA_ERROR_MPS_CONNECTION_FAILED \
	CUDA_ERROR_X(ERROR_MPS_CONNECTION_FAILED)
#define CUDA_ERROR_MPS_RPC_FAILURE CUDA_ERROR_X(ERROR_MPS_RPC_FAILURE)
#define CUDA_ERROR_MPS_SERVER_NOT_READY CUDA_ERROR_X(ERROR_MPS_SERVER_NOT_READY)
#define CUDA_ERROR_MPS_MAX_CLIENTS_REACHED \
	CUDA_ERROR_X(ERROR_MPS_MAX_CLIENTS_REACHED)
#define CUDA_ERROR_MPS_MAX_CONNECTIONS_REACHED \
	CUDA_ERROR_X(ERROR_MPS_MAX_CONNECTIONS_REACHED)
#define CUDA_ERROR_MPS_CLIENT_TERMINATED \
	CUDA_ERROR_X(ERROR_MPS_CLIENT_TERMINATED)
#define CUDA_ERROR_CDP_NOT_SUPPORTED CUDA_ERROR_X(ERROR_CDP_NOT_SUPPORTED)
#define CUDA_ERROR_CDP_VERSION_MISMATCH CUDA_ERROR_X(ERROR_CDP_VERSION_MISMATCH)
#define CUDA_ERROR_STREAM_CAPTURE_UNSUPPORTED \
	CUDA_ERROR_X(ERROR_STREAM_CAPTURE_UNSUPPORTED)
#define CUDA_ERROR_STREAM_CAPTURE_INVALIDATED \
	CUDA_ERROR_X(ERROR_STREAM_CAPTURE_INVALIDATED)
#define CUDA_ERROR_STREAM_CAPTURE_MERGE CUDA_ERROR_X(ERROR_STREAM_CAPTURE_MERGE)
#define CUDA_ERROR_STREAM_CAPTURE_UNMATCHED \
	CUDA_ERROR_X(ERROR_STREAM_CAPTURE_UNMATCHED)
#define CUDA_ERROR_STREAM_CAPTURE_UNJOINED \
	CUDA_ERROR_X(ERROR_STREAM_CAPTURE_UNJOINED)
#define CUDA_ERROR_STREAM_CAPTURE_ISOLATION \
	CUDA_ERROR_X(ERROR_STREAM_CAPTURE_ISOLATION)
#define CUDA_ERROR_STREAM_CAPTURE_IMPLICIT \
	CUDA_ERROR_X(ERROR_STREAM_CAPTURE_IMPLICIT)
#define CUDA_ERROR_CAPTURED_EVENT CUDA_ERROR_X(ERROR_CAPTURED_EVENT)
#define CUDA_ERROR_STREAM_CAPTURE_WRONG_THREAD \
	CUDA_ERROR_X(ERROR_STREAM_CAPTURE_WRONG_THREAD)
#define CUDA_ERROR_TIMEOUT CUDA_ERROR_X(ERROR_TIMEOUT)
#define CUDA_ERROR_GRAPH_EXEC_UPDATE_FAILURE \
	CUDA_ERROR_X(ERROR_GRAPH_EXEC_UPDATE_FAILURE)
#define CUDA_ERROR_EXTERNAL_DEVICE CUDA_ERROR_X(ERROR_EXTERNAL_DEVICE)
#define CUDA_ERROR_INVALID_CLUSTER_SIZE CUDA_ERROR_X(ERROR_INVALID_CLUSTER_SIZE)
#define CUDA_ERROR_FUNCTION_NOT_LOADED CUDA_ERROR_X(ERROR_FUNCTION_NOT_LOADED)
#define CUDA_ERROR_INVALID_RESOURCE_TYPE \
	CUDA_ERROR_X(ERROR_INVALID_RESOURCE_TYPE)
#define CUDA_ERROR_INVALID_RESOURCE_CONFIGURATION \
	CUDA_ERROR_X(ERROR_INVALID_RESOURCE_CONFIGURATION)
#define CUDA_ERROR_KEY_ROTATION CUDA_ERROR_X(ERROR_KEY_ROTATION)
#define CUDA_ERROR_UNKNOWN CUDA_ERROR_X(ERROR_UNKNOWN)

/**
 * CUDA: typedef __device_builtin__ struct CUstream_st *cudaStream_t;
 */
#define CUstream_st CUX(stream_st)

/**
 * CUDA: typedef struct CUstream_st *CUstream;
 */
#define CUstream CUX(stream)

/**
 * CUDA:
 * driver_types.h: typedef struct CUevent_st *cudaEvent_t;
 * cuda.h: typedef struct CUevent_st *CUevent;
 *
 * HPCC: typedef struct HCevent_st *hcEvent_t;
 * HIP: typedef struct ihipEvent_t* hipEvent_t;
 */
#ifdef __USE_HIP__
#define CUevent_st ihipEvent_t
#else
#define CUevent_st CUX(event_st)
#endif
/**
 * CUDA: typedef struct CUevent_st *CUevent;
 * LUCA: typedef struct LCevent_st *LCevent;
 */
#define CUevent CUX(event)

/**
 * CUDA 13:
 * CUresult cuGetErrorName(CUresult error, const char **pStr);
 */
#if defined(__USE_LUCA__) || defined(__USE_HPCC__) || defined(__USE_HIP__)
#define cuGetErrorName(error, pStr)                                     \
	do {                                                            \
		const char **__pstr = pStr;                             \
		*__pstr = "cuGetErrorName(): Function not implemented"; \
	} while (0)
#endif

/**
 * CUDA V13.0.48
 * CUresult cuDeviceGet(CUdevice *device, int ordinal);
 *
 * HIP
 * hipError_t hipDeviceGet(hipDevice_t*, int ordinal);
 *
 * HPCC 3.0.0
 * hcError_t hcDeviceGet(hcDevice_t *device, int ordinal);
 */
#define cuDeviceGet(pdevice, dev_id) cuX(DeviceGet(pdevice, dev_id))

/**
 * CUresult cuDeviceComputeCapability(int *major, int *minor, CUdevice dev);
 */
#define cuDeviceComputeCapability(pmajor, pminor, pdev) \
	cuX(DeviceComputeCapability(pmajor, pminor, pdev))

/**
 * CUDA 13
 * CUresult cuLaunchKernel(CUfunction f, unsigned int gridDimX,
 *                         unsigned int gridDimY, unsigned int gridDimZ,
 *                         unsigned int blockDimX, unsigned int blockDimY,
 *                         unsigned int blockDimZ, unsigned int sharedMemBytes,
 *                         CUstream hStream, void **kernelParams, void **extra);
 */
#define cuLaunchKernel cuX(LaunchKernel)

/**
 * CUDA 13
 * CUresult cuModuleLoad(CUmodule* module, const char *fname);
 *
 * HIP
 * hipError_t hipModuleLoad(hipModule_t *module, const char* fname);
 */
#define cuModuleLoad(pmodule, name) cuX(ModuleLoad(pmodule, name))

/**
 * CUDA 13
 * CUresult cuModuleUnload(CUmodule hmod);
 *
 * HIP
 * typedef struct ihipModule_t* hipModule_t;
 * hipError_t hipModuleUnload(hipModule_t module);
 */
#define cuModuleUnload(mod) cuX(ModuleUnload(mod))

/**
 * CUDA 13
 * CUresult cuModuleGetFunction(CUfunction *hfunc, CUmodule hmod, const char *name);
 *
 * HIP
 * hipError_t hipModuleGetFunction(hipFunction_t* function, hipModule_t module,
 *                                 const char* kname);
 *
 * HPCC
 * hcError_t hcModuleGetFunction(hcFunction_t *function, hcModule_t module,
 *                               const char *kname);
 */
#define cuModuleGetFunction(pfunc, mod, name) \
	cuX(ModuleGetFunction(pfunc, mod, name))

/**
 * CUDA 13:
 * CUresult cuModuleLoadData(CUmodule *module, const void *image);
 *
 * HIP
 * hipError_t hipModuleLoadData(hipModule_t* module, const void* image);
 */
#define cuModuleLoadData cuX(ModuleLoadData)

/**
 * CUDA 13
 * CUresult cuModuleLoadDataEx(CUmodule *module, const void *image,
 *                             unsigned int numOptions, CUjit_option *options,
 *                             void **optionValues);
 *
 * HIP
 * hipError_t hipModuleLoadDataEx(hipModule_t* module, const void* image,
 *                                unsigned int numOptions,
 *                                hipJitOption* options, void** optionValues);
 */
#define cuModuleLoadDataEx cuX(ModuleLoadDataEx)

/**
 * CUresult cuDeviceGetAttribute(int *pi, CUdevice_attribute attrib, CUdevice dev);
 */
#define cuDeviceGetAttribute cuX(DeviceGetAttribute)

#define CUdevice_attribute CUX(device_attribute) /* enum */
#define CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_BLOCK \
	CUX(_DEVICE_ATTRIBUTE_MAX_THREADS_PER_BLOCK)
#define CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_X \
	CUX(_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_X)
#define CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Y \
	CUX(_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Y)
#define CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Z \
	CUX(_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Z)
#define CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_X \
	CUX(_DEVICE_ATTRIBUTE_MAX_GRID_DIM_X)
#define CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Y \
	CUX(_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Y)
#define CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Z \
	CUX(_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Z)
#define CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK \
	CUX(_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK)
#define CU_DEVICE_ATTRIBUTE_SHARED_MEMORY_PER_BLOCK \
	CUX(_DEVICE_ATTRIBUTE_SHARED_MEMORY_PER_BLOCK)
#define CU_DEVICE_ATTRIBUTE_TOTAL_CONSTANT_MEMORY \
	CUX(_DEVICE_ATTRIBUTE_TOTAL_CONSTANT_MEMORY)
#define CU_DEVICE_ATTRIBUTE_WARP_SIZE \
	CUX(_DEVICE_ATTRIBUTE_WARP_SIZE)
#define CU_DEVICE_ATTRIBUTE_MAX_PITCH \
	CUX(_DEVICE_ATTRIBUTE_MAX_PITCH)
#define CU_DEVICE_ATTRIBUTE_MAX_REGISTERS_PER_BLOCK \
	CUX(_DEVICE_ATTRIBUTE_MAX_REGISTERS_PER_BLOCK)
#define CU_DEVICE_ATTRIBUTE_REGISTERS_PER_BLOCK \
	CUX(_DEVICE_ATTRIBUTE_REGISTERS_PER_BLOCK)
#define CU_DEVICE_ATTRIBUTE_CLOCK_RATE \
	CUX(_DEVICE_ATTRIBUTE_CLOCK_RATE)
#define CU_DEVICE_ATTRIBUTE_TEXTURE_ALIGNMENT \
	CUX(_DEVICE_ATTRIBUTE_TEXTURE_ALIGNMENT)
#define CU_DEVICE_ATTRIBUTE_GPU_OVERLAP \
	CUX(_DEVICE_ATTRIBUTE_GPU_OVERLAP)
#define CU_DEVICE_ATTRIBUTE_MULTIPROCESSOR_COUNT \
	CUX(_DEVICE_ATTRIBUTE_MULTIPROCESSOR_COUNT)
#define CU_DEVICE_ATTRIBUTE_KERNEL_EXEC_TIMEOUT \
	CUX(_DEVICE_ATTRIBUTE_KERNEL_EXEC_TIMEOUT)
#define CU_DEVICE_ATTRIBUTE_INTEGRATED \
	CUX(_DEVICE_ATTRIBUTE_INTEGRATED)
#define CU_DEVICE_ATTRIBUTE_CAN_MAP_HOST_MEMORY \
	CUX(_DEVICE_ATTRIBUTE_CAN_MAP_HOST_MEMORY)
#define CU_DEVICE_ATTRIBUTE_COMPUTE_MODE \
	CUX(_DEVICE_ATTRIBUTE_COMPUTE_MODE)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_HEIGHT \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_HEIGHT)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_HEIGHT \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_HEIGHT)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_DEPTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_DEPTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_HEIGHT \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_HEIGHT)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_LAYERS \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_LAYERS)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_HEIGHT \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_HEIGHT)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_NUMSLICES \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_NUMSLICES)
#define CU_DEVICE_ATTRIBUTE_SURFACE_ALIGNMENT \
	CUX(_DEVICE_ATTRIBUTE_SURFACE_ALIGNMENT)
#define CU_DEVICE_ATTRIBUTE_CONCURRENT_KERNELS \
	CUX(_DEVICE_ATTRIBUTE_CONCURRENT_KERNELS)
#define CU_DEVICE_ATTRIBUTE_ECC_ENABLED \
	CUX(_DEVICE_ATTRIBUTE_ECC_ENABLED)
#define CU_DEVICE_ATTRIBUTE_PCI_BUS_ID \
	CUX(_DEVICE_ATTRIBUTE_PCI_BUS_ID)
#define CU_DEVICE_ATTRIBUTE_PCI_DEVICE_ID \
	CUX(_DEVICE_ATTRIBUTE_PCI_DEVICE_ID)
#define CU_DEVICE_ATTRIBUTE_TCC_DRIVER \
	CUX(_DEVICE_ATTRIBUTE_TCC_DRIVER)
#define CU_DEVICE_ATTRIBUTE_MEMORY_CLOCK_RATE \
	CUX(_DEVICE_ATTRIBUTE_MEMORY_CLOCK_RATE)
#define CU_DEVICE_ATTRIBUTE_GLOBAL_MEMORY_BUS_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_GLOBAL_MEMORY_BUS_WIDTH)
#define CU_DEVICE_ATTRIBUTE_L2_CACHE_SIZE \
	CUX(_DEVICE_ATTRIBUTE_L2_CACHE_SIZE)
#define CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_MULTIPROCESSOR \
	CUX(_DEVICE_ATTRIBUTE_MAX_THREADS_PER_MULTIPROCESSOR)
#define CU_DEVICE_ATTRIBUTE_ASYNC_ENGINE_COUNT \
	CUX(_DEVICE_ATTRIBUTE_ASYNC_ENGINE_COUNT)
#define CU_DEVICE_ATTRIBUTE_UNIFIED_ADDRESSING \
	CUX(_DEVICE_ATTRIBUTE_UNIFIED_ADDRESSING)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LAYERED_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LAYERED_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LAYERED_LAYERS \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LAYERED_LAYERS)
#define CU_DEVICE_ATTRIBUTE_CAN_TEX2D_GATHER \
	CUX(_DEVICE_ATTRIBUTE_CAN_TEX2D_GATHER)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_GATHER_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_GATHER_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_GATHER_HEIGHT \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_GATHER_HEIGHT)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_WIDTH_ALTERNATE \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_WIDTH_ALTERNATE)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_HEIGHT_ALTERNATE \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_HEIGHT_ALTERNATE)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_DEPTH_ALTERNATE \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_DEPTH_ALTERNATE)
#define CU_DEVICE_ATTRIBUTE_PCI_DOMAIN_ID \
	CUX(_DEVICE_ATTRIBUTE_PCI_DOMAIN_ID)
#define CU_DEVICE_ATTRIBUTE_TEXTURE_PITCH_ALIGNMENT \
	CUX(_DEVICE_ATTRIBUTE_TEXTURE_PITCH_ALIGNMENT)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_LAYERED_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_LAYERED_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_LAYERED_LAYERS \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_LAYERED_LAYERS)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_HEIGHT \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_HEIGHT)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_HEIGHT \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_HEIGHT)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_DEPTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_DEPTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_LAYERED_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_LAYERED_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_LAYERED_LAYERS \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_LAYERED_LAYERS)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_HEIGHT \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_HEIGHT)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_LAYERS \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_LAYERS)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_LAYERED_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_LAYERED_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_LAYERED_LAYERS \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_LAYERED_LAYERS)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LINEAR_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LINEAR_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_HEIGHT \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_HEIGHT)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_PITCH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_PITCH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_MIPMAPPED_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_MIPMAPPED_WIDTH)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_MIPMAPPED_HEIGHT \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_MIPMAPPED_HEIGHT)
#define CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR \
	CUX(_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR)
#define CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR \
	CUX(_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR)
#define CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_MIPMAPPED_WIDTH \
	CUX(_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_MIPMAPPED_WIDTH)
#define CU_DEVICE_ATTRIBUTE_STREAM_PRIORITIES_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_STREAM_PRIORITIES_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_GLOBAL_L1_CACHE_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_GLOBAL_L1_CACHE_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_LOCAL_L1_CACHE_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_LOCAL_L1_CACHE_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_MULTIPROCESSOR \
	CUX(_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_MULTIPROCESSOR)
#define CU_DEVICE_ATTRIBUTE_MAX_REGISTERS_PER_MULTIPROCESSOR \
	CUX(_DEVICE_ATTRIBUTE_MAX_REGISTERS_PER_MULTIPROCESSOR)
#define CU_DEVICE_ATTRIBUTE_MANAGED_MEMORY \
	CUX(_DEVICE_ATTRIBUTE_MANAGED_MEMORY)
#define CU_DEVICE_ATTRIBUTE_MULTI_GPU_BOARD \
	CUX(_DEVICE_ATTRIBUTE_MULTI_GPU_BOARD)
#define CU_DEVICE_ATTRIBUTE_MULTI_GPU_BOARD_GROUP_ID \
	CUX(_DEVICE_ATTRIBUTE_MULTI_GPU_BOARD_GROUP_ID)
#define CU_DEVICE_ATTRIBUTE_HOST_NATIVE_ATOMIC_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_HOST_NATIVE_ATOMIC_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_SINGLE_TO_DOUBLE_PRECISION_PERF_RATIO \
	CUX(_DEVICE_ATTRIBUTE_SINGLE_TO_DOUBLE_PRECISION_PERF_RATIO)
#define CU_DEVICE_ATTRIBUTE_PAGEABLE_MEMORY_ACCESS \
	CUX(_DEVICE_ATTRIBUTE_PAGEABLE_MEMORY_ACCESS)
#define CU_DEVICE_ATTRIBUTE_CONCURRENT_MANAGED_ACCESS \
	CUX(_DEVICE_ATTRIBUTE_CONCURRENT_MANAGED_ACCESS)
#define CU_DEVICE_ATTRIBUTE_COMPUTE_PREEMPTION_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_COMPUTE_PREEMPTION_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_CAN_USE_HOST_POINTER_FOR_REGISTERED_MEM \
	CUX(_DEVICE_ATTRIBUTE_CAN_USE_HOST_POINTER_FOR_REGISTERED_MEM)
#define CU_DEVICE_ATTRIBUTE_CAN_USE_STREAM_MEM_OPS_V1 \
	CUX(_DEVICE_ATTRIBUTE_CAN_USE_STREAM_MEM_OPS_V1)
#define CU_DEVICE_ATTRIBUTE_CAN_USE_64_BIT_STREAM_MEM_OPS_V1 \
	CUX(_DEVICE_ATTRIBUTE_CAN_USE_64_BIT_STREAM_MEM_OPS_V1)
#define CU_DEVICE_ATTRIBUTE_CAN_USE_STREAM_WAIT_VALUE_NOR_V1 \
	CUX(_DEVICE_ATTRIBUTE_CAN_USE_STREAM_WAIT_VALUE_NOR_V1)
#define CU_DEVICE_ATTRIBUTE_COOPERATIVE_LAUNCH \
	CUX(_DEVICE_ATTRIBUTE_COOPERATIVE_LAUNCH)
#define CU_DEVICE_ATTRIBUTE_COOPERATIVE_MULTI_DEVICE_LAUNCH \
	CUX(_DEVICE_ATTRIBUTE_COOPERATIVE_MULTI_DEVICE_LAUNCH)
#define CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK_OPTIN \
	CUX(_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK_OPTIN)
#define CU_DEVICE_ATTRIBUTE_CAN_FLUSH_REMOTE_WRITES \
	CUX(_DEVICE_ATTRIBUTE_CAN_FLUSH_REMOTE_WRITES)
#define CU_DEVICE_ATTRIBUTE_HOST_REGISTER_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_HOST_REGISTER_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_PAGEABLE_MEMORY_ACCESS_USES_HOST_PAGE_TABLES \
	CUX(_DEVICE_ATTRIBUTE_PAGEABLE_MEMORY_ACCESS_USES_HOST_PAGE_TABLES)
#define CU_DEVICE_ATTRIBUTE_DIRECT_MANAGED_MEM_ACCESS_FROM_HOST \
	CUX(_DEVICE_ATTRIBUTE_DIRECT_MANAGED_MEM_ACCESS_FROM_HOST)
#define CU_DEVICE_ATTRIBUTE_VIRTUAL_ADDRESS_MANAGEMENT_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_VIRTUAL_ADDRESS_MANAGEMENT_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_VIRTUAL_MEMORY_MANAGEMENT_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_VIRTUAL_MEMORY_MANAGEMENT_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_HANDLE_TYPE_POSIX_FILE_DESCRIPTOR_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_HANDLE_TYPE_POSIX_FILE_DESCRIPTOR_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_HANDLE_TYPE_WIN32_HANDLE_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_HANDLE_TYPE_WIN32_HANDLE_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_HANDLE_TYPE_WIN32_KMT_HANDLE_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_HANDLE_TYPE_WIN32_KMT_HANDLE_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_MAX_BLOCKS_PER_MULTIPROCESSOR \
	CUX(_DEVICE_ATTRIBUTE_MAX_BLOCKS_PER_MULTIPROCESSOR)
#define CU_DEVICE_ATTRIBUTE_GENERIC_COMPRESSION_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_GENERIC_COMPRESSION_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_MAX_PERSISTING_L2_CACHE_SIZE \
	CUX(_DEVICE_ATTRIBUTE_MAX_PERSISTING_L2_CACHE_SIZE)
#define CU_DEVICE_ATTRIBUTE_MAX_ACCESS_POLICY_WINDOW_SIZE \
	CUX(_DEVICE_ATTRIBUTE_MAX_ACCESS_POLICY_WINDOW_SIZE)
#define CU_DEVICE_ATTRIBUTE_GPU_DIRECT_RDMA_WITH_CUDA_VMM_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_GPU_DIRECT_RDMA_WITH_CUDA_VMM_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_RESERVED_SHARED_MEMORY_PER_BLOCK \
	CUX(_DEVICE_ATTRIBUTE_RESERVED_SHARED_MEMORY_PER_BLOCK)
#define CU_DEVICE_ATTRIBUTE_SPARSE_CUDA_ARRAY_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_SPARSE_CUDA_ARRAY_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_READ_ONLY_HOST_REGISTER_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_READ_ONLY_HOST_REGISTER_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_TIMELINE_SEMAPHORE_INTEROP_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_TIMELINE_SEMAPHORE_INTEROP_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_MEMORY_POOLS_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_MEMORY_POOLS_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_GPU_DIRECT_RDMA_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_GPU_DIRECT_RDMA_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_GPU_DIRECT_RDMA_FLUSH_WRITES_OPTIONS \
	CUX(_DEVICE_ATTRIBUTE_GPU_DIRECT_RDMA_FLUSH_WRITES_OPTIONS)
#define CU_DEVICE_ATTRIBUTE_GPU_DIRECT_RDMA_WRITES_ORDERING \
	CUX(_DEVICE_ATTRIBUTE_GPU_DIRECT_RDMA_WRITES_ORDERING)
#define CU_DEVICE_ATTRIBUTE_MEMPOOL_SUPPORTED_HANDLE_TYPES \
	CUX(_DEVICE_ATTRIBUTE_MEMPOOL_SUPPORTED_HANDLE_TYPES)
#define CU_DEVICE_ATTRIBUTE_CLUSTER_LAUNCH \
	CUX(_DEVICE_ATTRIBUTE_CLUSTER_LAUNCH)
#define CU_DEVICE_ATTRIBUTE_DEFERRED_MAPPING_CUDA_ARRAY_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_DEFERRED_MAPPING_CUDA_ARRAY_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_CAN_USE_64_BIT_STREAM_MEM_OPS \
	CUX(_DEVICE_ATTRIBUTE_CAN_USE_64_BIT_STREAM_MEM_OPS)
#define CU_DEVICE_ATTRIBUTE_CAN_USE_STREAM_WAIT_VALUE_NOR \
	CUX(_DEVICE_ATTRIBUTE_CAN_USE_STREAM_WAIT_VALUE_NOR)
#define CU_DEVICE_ATTRIBUTE_DMA_BUF_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_DMA_BUF_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_IPC_EVENT_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_IPC_EVENT_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_MEM_SYNC_DOMAIN_COUNT \
	CUX(_DEVICE_ATTRIBUTE_MEM_SYNC_DOMAIN_COUNT)
#define CU_DEVICE_ATTRIBUTE_TENSOR_MAP_ACCESS_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_TENSOR_MAP_ACCESS_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_HANDLE_TYPE_FABRIC_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_HANDLE_TYPE_FABRIC_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_UNIFIED_FUNCTION_POINTERS \
	CUX(_DEVICE_ATTRIBUTE_UNIFIED_FUNCTION_POINTERS)
#define CU_DEVICE_ATTRIBUTE_NUMA_CONFIG \
	CUX(_DEVICE_ATTRIBUTE_NUMA_CONFIG)
#define CU_DEVICE_ATTRIBUTE_NUMA_ID \
	CUX(_DEVICE_ATTRIBUTE_NUMA_ID)
#define CU_DEVICE_ATTRIBUTE_MULTICAST_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_MULTICAST_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_MPS_ENABLED \
	CUX(_DEVICE_ATTRIBUTE_MPS_ENABLED)
#define CU_DEVICE_ATTRIBUTE_HOST_NUMA_ID \
	CUX(_DEVICE_ATTRIBUTE_HOST_NUMA_ID)
#define CU_DEVICE_ATTRIBUTE_D3D12_CIG_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_D3D12_CIG_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_MEM_DECOMPRESS_ALGORITHM_MASK \
	CUX(_DEVICE_ATTRIBUTE_MEM_DECOMPRESS_ALGORITHM_MASK)
#define CU_DEVICE_ATTRIBUTE_MEM_DECOMPRESS_MAXIMUM_LENGTH \
	CUX(_DEVICE_ATTRIBUTE_MEM_DECOMPRESS_MAXIMUM_LENGTH)
#define CU_DEVICE_ATTRIBUTE_VULKAN_CIG_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_VULKAN_CIG_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_GPU_PCI_DEVICE_ID \
	CUX(_DEVICE_ATTRIBUTE_GPU_PCI_DEVICE_ID)
#define CU_DEVICE_ATTRIBUTE_GPU_PCI_SUBSYSTEM_ID \
	CUX(_DEVICE_ATTRIBUTE_GPU_PCI_SUBSYSTEM_ID)
#define CU_DEVICE_ATTRIBUTE_HOST_NUMA_VIRTUAL_MEMORY_MANAGEMENT_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_HOST_NUMA_VIRTUAL_MEMORY_MANAGEMENT_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_HOST_NUMA_MEMORY_POOLS_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_HOST_NUMA_MEMORY_POOLS_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_HOST_NUMA_MULTINODE_IPC_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_HOST_NUMA_MULTINODE_IPC_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_HOST_MEMORY_POOLS_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_HOST_MEMORY_POOLS_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_HOST_VIRTUAL_MEMORY_MANAGEMENT_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_HOST_VIRTUAL_MEMORY_MANAGEMENT_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_HOST_ALLOC_DMA_BUF_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_HOST_ALLOC_DMA_BUF_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_ONLY_PARTIAL_HOST_NATIVE_ATOMIC_SUPPORTED \
	CUX(_DEVICE_ATTRIBUTE_ONLY_PARTIAL_HOST_NATIVE_ATOMIC_SUPPORTED)
#define CU_DEVICE_ATTRIBUTE_MAX \
	CUX(_DEVICE_ATTRIBUTE_MAX)

#endif
