// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
/* Copyright (C) 2025-2026 Rong Tao */
/******************************************************************************\
 *             PTI - CUDA Profiling Tools Interface                           *
\******************************************************************************/
#ifndef __CUDA_ADAPTER_CUPTI_RUNTIME_CBID_H
#define __CUDA_ADAPTER_CUPTI_RUNTIME_CBID_H 1

#ifdef _CUPTI_RUNTIME_CBID_H
#error "CudaAdapter not allow include origin CUDA cupti_runtime_cbid.h"
#endif

#include "wrapper_defs.h"

#define CUpti_runtime_api_trace_cbid CUX(pti_runtime_api_trace_cbid) /* enum */

#define CUPTI_RUNTIME_TRACE_CBID_INVALID CUX(PTI_RUNTIME_TRACE_CBID_INVALID)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDriverGetVersion_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DriverGetVersion_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaRuntimeGetVersion_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, RuntimeGetVersion_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetDeviceCount_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetDeviceCount_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetDeviceProperties_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetDeviceProperties_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaChooseDevice_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, ChooseDevice_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetChannelDesc_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetChannelDesc_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaCreateChannelDesc_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, CreateChannelDesc_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaConfigureCall_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, ConfigureCall_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaSetupArgument_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, SetupArgument_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetLastError_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetLastError_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaPeekAtLastError_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, PeekAtLastError_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetErrorString_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetErrorString_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLaunch_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Launch_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaFuncSetCacheConfig_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, FuncSetCacheConfig_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaFuncGetAttributes_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, FuncGetAttributes_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaSetDevice_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, SetDevice_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetDevice_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetDevice_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaSetValidDevices_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, SetValidDevices_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaSetDeviceFlags_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, SetDeviceFlags_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMalloc_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Malloc_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMallocPitch_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MallocPitch_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaFree_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Free_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMallocArray_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MallocArray_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaFreeArray_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, FreeArray_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMallocHost_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MallocHost_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaFreeHost_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, FreeHost_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaHostAlloc_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, HostAlloc_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaHostGetDevicePointer_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, HostGetDevicePointer_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaHostGetFlags_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, HostGetFlags_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemGetInfo_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemGetInfo_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2D_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy2D_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyToArray_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyToArray_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DToArray_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy2DToArray_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyFromArray_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyFromArray_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DFromArray_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy2DFromArray_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyArrayToArray_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyArrayToArray_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DArrayToArray_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy2DArrayToArray_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyToSymbol_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyToSymbol_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyFromSymbol_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyFromSymbol_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyAsync_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyAsync_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyToArrayAsync_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyToArrayAsync_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyFromArrayAsync_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyFromArrayAsync_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DAsync_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy2DAsync_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DToArrayAsync_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy2DToArrayAsync_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DFromArrayAsync_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy2DFromArrayAsync_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyToSymbolAsync_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyToSymbolAsync_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyFromSymbolAsync_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyFromSymbolAsync_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemset_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memset_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemset2D_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memset2D_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemsetAsync_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemsetAsync_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemset2DAsync_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memset2DAsync_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetSymbolAddress_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetSymbolAddress_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetSymbolSize_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetSymbolSize_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaBindTexture_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, BindTexture_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaBindTexture2D_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, BindTexture2D_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaBindTextureToArray_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, BindTextureToArray_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaUnbindTexture_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, UnbindTexture_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetTextureAlignmentOffset_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetTextureAlignmentOffset_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetTextureReference_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetTextureReference_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaBindSurfaceToArray_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, BindSurfaceToArray_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetSurfaceReference_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetSurfaceReference_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGLSetGLDevice_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GLSetGLDevice_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGLRegisterBufferObject_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GLRegisterBufferObject_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGLMapBufferObject_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GLMapBufferObject_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGLUnmapBufferObject_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GLUnmapBufferObject_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGLUnregisterBufferObject_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GLUnregisterBufferObject_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGLSetBufferObjectMapFlags_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GLSetBufferObjectMapFlags_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGLMapBufferObjectAsync_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GLMapBufferObjectAsync_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGLUnmapBufferObjectAsync_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GLUnmapBufferObjectAsync_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaWGLGetDevice_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, WGLGetDevice_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsGLRegisterImage_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphicsGLRegisterImage_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsGLRegisterBuffer_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphicsGLRegisterBuffer_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsUnregisterResource_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphicsUnregisterResource_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsResourceSetMapFlags_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphicsResourceSetMapFlags_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsMapResources_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphicsMapResources_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsUnmapResources_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphicsUnmapResources_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsResourceGetMappedPointer_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GraphicsResourceGetMappedPointer_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsSubResourceGetMappedArray_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GraphicsSubResourceGetMappedArray_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaVDPAUGetDevice_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, VDPAUGetDevice_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaVDPAUSetVDPAUDevice_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, VDPAUSetVDPAUDevice_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsVDPAURegisterVideoSurface_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphicsVDPAURegisterVideoSurface_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsVDPAURegisterOutputSurface_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphicsVDPAURegisterOutputSurface_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D11GetDevice_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D11GetDevice_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D11GetDevices_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D11GetDevices_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D11SetDirect3DDevice_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D11SetDirect3DDevice_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsD3D11RegisterResource_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphicsD3D11RegisterResource_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D10GetDevice_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D10GetDevice_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D10GetDevices_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D10GetDevices_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D10SetDirect3DDevice_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D10SetDirect3DDevice_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsD3D10RegisterResource_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphicsD3D10RegisterResource_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D10RegisterResource_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D10RegisterResource_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D10UnregisterResource_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D10UnregisterResource_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D10MapResources_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D10MapResources_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D10UnmapResources_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D10UnmapResources_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D10ResourceSetMapFlags_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D10ResourceSetMapFlags_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D10ResourceGetSurfaceDimensions_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D10ResourceGetSurfaceDimensions_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D10ResourceGetMappedArray_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D10ResourceGetMappedArray_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D10ResourceGetMappedPointer_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D10ResourceGetMappedPointer_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D10ResourceGetMappedSize_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D10ResourceGetMappedSize_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D10ResourceGetMappedPitch_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D10ResourceGetMappedPitch_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9GetDevice_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9GetDevice_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9GetDevices_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9GetDevices_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9SetDirect3DDevice_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9SetDirect3DDevice_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9GetDirect3DDevice_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9GetDirect3DDevice_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsD3D9RegisterResource_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphicsD3D9RegisterResource_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9RegisterResource_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9RegisterResource_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9UnregisterResource_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9UnregisterResource_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9MapResources_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9MapResources_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9UnmapResources_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9UnmapResources_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9ResourceSetMapFlags_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9ResourceSetMapFlags_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9ResourceGetSurfaceDimensions_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9ResourceGetSurfaceDimensions_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9ResourceGetMappedArray_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9ResourceGetMappedArray_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9ResourceGetMappedPointer_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9ResourceGetMappedPointer_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9ResourceGetMappedSize_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9ResourceGetMappedSize_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9ResourceGetMappedPitch_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9ResourceGetMappedPitch_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9Begin_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9Begin_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9End_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9End_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9RegisterVertexBuffer_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9RegisterVertexBuffer_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9UnregisterVertexBuffer_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9UnregisterVertexBuffer_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9MapVertexBuffer_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9MapVertexBuffer_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D9UnmapVertexBuffer_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D9UnmapVertexBuffer_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaThreadExit_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, ThreadExit_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaSetDoubleForDevice_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, SetDoubleForDevice_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaSetDoubleForHost_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, SetDoubleForHost_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaThreadSynchronize_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, ThreadSynchronize_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaThreadGetLimit_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, ThreadGetLimit_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaThreadSetLimit_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, ThreadSetLimit_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamCreate_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamCreate_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamDestroy_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamDestroy_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamSynchronize_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamSynchronize_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamQuery_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamQuery_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEventCreate_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EventCreate_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEventCreateWithFlags_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EventCreateWithFlags_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEventRecord_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EventRecord_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEventDestroy_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EventDestroy_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEventSynchronize_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EventSynchronize_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEventQuery_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EventQuery_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEventElapsedTime_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EventElapsedTime_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMalloc3D_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Malloc3D_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMalloc3DArray_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Malloc3DArray_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemset3D_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memset3D_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemset3DAsync_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memset3DAsync_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3D_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy3D_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3DAsync_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy3DAsync_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaThreadSetCacheConfig_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, ThreadSetCacheConfig_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamWaitEvent_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamWaitEvent_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D11GetDirect3DDevice_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D11GetDirect3DDevice_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaD3D10GetDirect3DDevice_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, D3D10GetDirect3DDevice_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaThreadGetCacheConfig_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, ThreadGetCacheConfig_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaPointerGetAttributes_v4000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, PointerGetAttributes_v4000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaHostRegister_v4000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, HostRegister_v4000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaHostUnregister_v4000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, HostUnregister_v4000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceCanAccessPeer_v4000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceCanAccessPeer_v4000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceEnablePeerAccess_v4000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceEnablePeerAccess_v4000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceDisablePeerAccess_v4000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceDisablePeerAccess_v4000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaPeerRegister_v4000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, PeerRegister_v4000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaPeerUnregister_v4000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, PeerUnregister_v4000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaPeerGetDevicePointer_v4000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, PeerGetDevicePointer_v4000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyPeer_v4000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyPeer_v4000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyPeerAsync_v4000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyPeerAsync_v4000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3DPeer_v4000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy3DPeer_v4000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3DPeerAsync_v4000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy3DPeerAsync_v4000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceReset_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceReset_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceSynchronize_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceSynchronize_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetLimit_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceGetLimit_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceSetLimit_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceSetLimit_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetCacheConfig_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceGetCacheConfig_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceSetCacheConfig_v3020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceSetCacheConfig_v3020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaProfilerInitialize_v4000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, ProfilerInitialize_v4000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaProfilerStart_v4000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, ProfilerStart_v4000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaProfilerStop_v4000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, ProfilerStop_v4000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetByPCIBusId_v4010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceGetByPCIBusId_v4010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetPCIBusId_v4010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceGetPCIBusId_v4010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGLGetDevices_v4010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GLGetDevices_v4010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaIpcGetEventHandle_v4010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, IpcGetEventHandle_v4010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaIpcOpenEventHandle_v4010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, IpcOpenEventHandle_v4010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaIpcGetMemHandle_v4010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, IpcGetMemHandle_v4010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaIpcOpenMemHandle_v4010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, IpcOpenMemHandle_v4010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaIpcCloseMemHandle_v4010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, IpcCloseMemHandle_v4010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaArrayGetInfo_v4010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, ArrayGetInfo_v4010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaFuncSetSharedMemConfig_v4020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, FuncSetSharedMemConfig_v4020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetSharedMemConfig_v4020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceGetSharedMemConfig_v4020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceSetSharedMemConfig_v4020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceSetSharedMemConfig_v4020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaCreateTextureObject_v5000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, CreateTextureObject_v5000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDestroyTextureObject_v5000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DestroyTextureObject_v5000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetTextureObjectResourceDesc_v5000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetTextureObjectResourceDesc_v5000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetTextureObjectTextureDesc_v5000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetTextureObjectTextureDesc_v5000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaCreateSurfaceObject_v5000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, CreateSurfaceObject_v5000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDestroySurfaceObject_v5000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DestroySurfaceObject_v5000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetSurfaceObjectResourceDesc_v5000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetSurfaceObjectResourceDesc_v5000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMallocMipmappedArray_v5000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MallocMipmappedArray_v5000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetMipmappedArrayLevel_v5000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetMipmappedArrayLevel_v5000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaFreeMipmappedArray_v5000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, FreeMipmappedArray_v5000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaBindTextureToMipmappedArray_v5000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, BindTextureToMipmappedArray_v5000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsResourceGetMappedMipmappedArray_v5000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphicsResourceGetMappedMipmappedArray_v5000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamAddCallback_v5000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamAddCallback_v5000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamCreateWithFlags_v5000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamCreateWithFlags_v5000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetTextureObjectResourceViewDesc_v5000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetTextureObjectResourceViewDesc_v5000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetAttribute_v5000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceGetAttribute_v5000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamDestroy_v5050 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamDestroy_v5050)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamCreateWithPriority_v5050 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamCreateWithPriority_v5050)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetPriority_v5050 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamGetPriority_v5050)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetFlags_v5050 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamGetFlags_v5050)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetStreamPriorityRange_v5050 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceGetStreamPriorityRange_v5050)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMallocManaged_v6000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MallocManaged_v6000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaOccupancyMaxActiveBlocksPerMultiprocessor_v6000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 OccupancyMaxActiveBlocksPerMultiprocessor_v6000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamAttachMemAsync_v6000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamAttachMemAsync_v6000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetErrorName_v6050 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetErrorName_v6050)
#define CUPTI_RUNTIME_TRACE_CBID_cudaOccupancyMaxActiveBlocksPerMultiprocessor_v6050 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 OccupancyMaxActiveBlocksPerMultiprocessor_v6050)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLaunchKernel_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LaunchKernel_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetDeviceFlags_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetDeviceFlags_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLaunch_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Launch_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLaunchKernel_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LaunchKernel_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy_ptds_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy_ptds_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2D_ptds_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy2D_ptds_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyToArray_ptds_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyToArray_ptds_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DToArray_ptds_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy2DToArray_ptds_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyFromArray_ptds_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyFromArray_ptds_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DFromArray_ptds_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy2DFromArray_ptds_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyArrayToArray_ptds_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyArrayToArray_ptds_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DArrayToArray_ptds_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy2DArrayToArray_ptds_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyToSymbol_ptds_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyToSymbol_ptds_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyFromSymbol_ptds_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyFromSymbol_ptds_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyAsync_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyAsync_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyToArrayAsync_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyToArrayAsync_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyFromArrayAsync_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyFromArrayAsync_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DAsync_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy2DAsync_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DToArrayAsync_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy2DToArrayAsync_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy2DFromArrayAsync_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy2DFromArrayAsync_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyToSymbolAsync_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyToSymbolAsync_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyFromSymbolAsync_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyFromSymbolAsync_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemset_ptds_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memset_ptds_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemset2D_ptds_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memset2D_ptds_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemsetAsync_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemsetAsync_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemset2DAsync_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memset2DAsync_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetPriority_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamGetPriority_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetFlags_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamGetFlags_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamSynchronize_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamSynchronize_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamQuery_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamQuery_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamAttachMemAsync_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamAttachMemAsync_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEventRecord_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EventRecord_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemset3D_ptds_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memset3D_ptds_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemset3DAsync_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memset3DAsync_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3D_ptds_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy3D_ptds_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3DAsync_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy3DAsync_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamWaitEvent_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamWaitEvent_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamAddCallback_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamAddCallback_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3DPeer_ptds_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy3DPeer_ptds_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3DPeerAsync_ptsz_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy3DPeerAsync_ptsz_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 OccupancyMaxActiveBlocksPerMultiprocessorWithFlags_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemPrefetchAsync_v8000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemPrefetchAsync_v8000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemPrefetchAsync_ptsz_v8000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemPrefetchAsync_ptsz_v8000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemAdvise_v8000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemAdvise_v8000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetP2PAttribute_v8000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceGetP2PAttribute_v8000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsEGLRegisterImage_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphicsEGLRegisterImage_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEGLStreamConsumerConnect_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EGLStreamConsumerConnect_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEGLStreamConsumerDisconnect_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EGLStreamConsumerDisconnect_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEGLStreamConsumerAcquireFrame_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EGLStreamConsumerAcquireFrame_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEGLStreamConsumerReleaseFrame_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EGLStreamConsumerReleaseFrame_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEGLStreamProducerConnect_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EGLStreamProducerConnect_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEGLStreamProducerDisconnect_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EGLStreamProducerDisconnect_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEGLStreamProducerPresentFrame_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EGLStreamProducerPresentFrame_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEGLStreamProducerReturnFrame_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EGLStreamProducerReturnFrame_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphicsResourceGetMappedEglFrame_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GraphicsResourceGetMappedEglFrame_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemRangeGetAttribute_v8000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemRangeGetAttribute_v8000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemRangeGetAttributes_v8000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemRangeGetAttributes_v8000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEGLStreamConsumerConnectWithFlags_v7000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 EGLStreamConsumerConnectWithFlags_v7000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLaunchCooperativeKernel_v9000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LaunchCooperativeKernel_v9000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLaunchCooperativeKernel_ptsz_v9000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LaunchCooperativeKernel_ptsz_v9000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEventCreateFromEGLSync_v9000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EventCreateFromEGLSync_v9000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLaunchCooperativeKernelMultiDevice_v9000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 LaunchCooperativeKernelMultiDevice_v9000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaFuncSetAttribute_v9000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, FuncSetAttribute_v9000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaImportExternalMemory_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, ImportExternalMemory_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaExternalMemoryGetMappedBuffer_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, ExternalMemoryGetMappedBuffer_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaExternalMemoryGetMappedMipmappedArray_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 ExternalMemoryGetMappedMipmappedArray_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDestroyExternalMemory_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DestroyExternalMemory_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaImportExternalSemaphore_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, ImportExternalSemaphore_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaSignalExternalSemaphoresAsync_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, SignalExternalSemaphoresAsync_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaSignalExternalSemaphoresAsync_ptsz_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 SignalExternalSemaphoresAsync_ptsz_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaWaitExternalSemaphoresAsync_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, WaitExternalSemaphoresAsync_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaWaitExternalSemaphoresAsync_ptsz_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 WaitExternalSemaphoresAsync_ptsz_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDestroyExternalSemaphore_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DestroyExternalSemaphore_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLaunchHostFunc_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LaunchHostFunc_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLaunchHostFunc_ptsz_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LaunchHostFunc_ptsz_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphCreate_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphCreate_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphKernelNodeGetParams_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphKernelNodeGetParams_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphKernelNodeSetParams_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphKernelNodeSetParams_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddKernelNode_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphAddKernelNode_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddMemcpyNode_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphAddMemcpyNode_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphMemcpyNodeGetParams_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphMemcpyNodeGetParams_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphMemcpyNodeSetParams_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphMemcpyNodeSetParams_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddMemsetNode_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphAddMemsetNode_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphMemsetNodeGetParams_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphMemsetNodeGetParams_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphMemsetNodeSetParams_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphMemsetNodeSetParams_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddHostNode_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphAddHostNode_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphHostNodeGetParams_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphHostNodeGetParams_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddChildGraphNode_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphAddChildGraphNode_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphChildGraphNodeGetGraph_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphChildGraphNodeGetGraph_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddEmptyNode_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphAddEmptyNode_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphClone_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphClone_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphNodeFindInClone_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphNodeFindInClone_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphNodeGetType_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphNodeGetType_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphGetRootNodes_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphGetRootNodes_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphNodeGetDependencies_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphNodeGetDependencies_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphNodeGetDependentNodes_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphNodeGetDependentNodes_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddDependencies_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphAddDependencies_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphRemoveDependencies_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphRemoveDependencies_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphDestroyNode_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphDestroyNode_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphInstantiate_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphInstantiate_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphLaunch_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphLaunch_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphLaunch_ptsz_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphLaunch_ptsz_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExecDestroy_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphExecDestroy_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphDestroy_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphDestroy_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamBeginCapture_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamBeginCapture_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamBeginCapture_ptsz_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamBeginCapture_ptsz_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamIsCapturing_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamIsCapturing_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamIsCapturing_ptsz_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamIsCapturing_ptsz_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamEndCapture_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamEndCapture_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamEndCapture_ptsz_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamEndCapture_ptsz_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphHostNodeSetParams_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphHostNodeSetParams_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphGetNodes_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphGetNodes_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphGetEdges_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphGetEdges_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetCaptureInfo_v10010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamGetCaptureInfo_v10010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetCaptureInfo_ptsz_v10010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamGetCaptureInfo_ptsz_v10010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExecKernelNodeSetParams_v10010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphExecKernelNodeSetParams_v10010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaThreadExchangeStreamCaptureMode_v10010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 ThreadExchangeStreamCaptureMode_v10010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetNvSciSyncAttributes_v10020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceGetNvSciSyncAttributes_v10020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaOccupancyAvailableDynamicSMemPerBlock_v10200 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 OccupancyAvailableDynamicSMemPerBlock_v10200)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamSetFlags_v10200 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamSetFlags_v10200)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamSetFlags_ptsz_v10200 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamSetFlags_ptsz_v10200)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExecMemcpyNodeSetParams_v10020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphExecMemcpyNodeSetParams_v10020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExecMemsetNodeSetParams_v10020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphExecMemsetNodeSetParams_v10020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExecHostNodeSetParams_v10020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphExecHostNodeSetParams_v10020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExecUpdate_v10020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphExecUpdate_v10020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetFuncBySymbol_v11000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetFuncBySymbol_v11000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaCtxResetPersistingL2Cache_v11000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, CtxResetPersistingL2Cache_v11000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphKernelNodeCopyAttributes_v11000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphKernelNodeCopyAttributes_v11000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphKernelNodeGetAttribute_v11000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphKernelNodeGetAttribute_v11000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphKernelNodeSetAttribute_v11000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphKernelNodeSetAttribute_v11000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamCopyAttributes_v11000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamCopyAttributes_v11000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamCopyAttributes_ptsz_v11000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamCopyAttributes_ptsz_v11000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetAttribute_v11000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamGetAttribute_v11000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetAttribute_ptsz_v11000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamGetAttribute_ptsz_v11000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamSetAttribute_v11000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamSetAttribute_v11000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamSetAttribute_ptsz_v11000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamSetAttribute_ptsz_v11000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetTexture1DLinearMaxWidth_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 DeviceGetTexture1DLinearMaxWidth_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphUpload_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphUpload_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphUpload_ptsz_v10000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphUpload_ptsz_v10000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddMemcpyNodeToSymbol_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphAddMemcpyNodeToSymbol_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddMemcpyNodeFromSymbol_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphAddMemcpyNodeFromSymbol_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddMemcpyNode1D_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphAddMemcpyNode1D_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphMemcpyNodeSetParamsToSymbol_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GraphMemcpyNodeSetParamsToSymbol_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphMemcpyNodeSetParamsFromSymbol_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GraphMemcpyNodeSetParamsFromSymbol_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphMemcpyNodeSetParams1D_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphMemcpyNodeSetParams1D_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExecMemcpyNodeSetParamsToSymbol_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GraphExecMemcpyNodeSetParamsToSymbol_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExecMemcpyNodeSetParamsFromSymbol_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GraphExecMemcpyNodeSetParamsFromSymbol_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExecMemcpyNodeSetParams1D_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphExecMemcpyNodeSetParams1D_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaArrayGetSparseProperties_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, ArrayGetSparseProperties_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMipmappedArrayGetSparseProperties_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 MipmappedArrayGetSparseProperties_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExecChildGraphNodeSetParams_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GraphExecChildGraphNodeSetParams_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddEventRecordNode_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphAddEventRecordNode_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphEventRecordNodeGetEvent_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphEventRecordNodeGetEvent_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphEventRecordNodeSetEvent_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphEventRecordNodeSetEvent_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddEventWaitNode_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphAddEventWaitNode_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphEventWaitNodeGetEvent_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphEventWaitNodeGetEvent_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphEventWaitNodeSetEvent_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphEventWaitNodeSetEvent_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExecEventRecordNodeSetEvent_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GraphExecEventRecordNodeSetEvent_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExecEventWaitNodeSetEvent_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphExecEventWaitNodeSetEvent_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEventRecordWithFlags_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EventRecordWithFlags_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEventRecordWithFlags_ptsz_v11010 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EventRecordWithFlags_ptsz_v11010)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetDefaultMemPool_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceGetDefaultMemPool_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMallocAsync_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MallocAsync_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMallocAsync_ptsz_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MallocAsync_ptsz_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaFreeAsync_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, FreeAsync_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaFreeAsync_ptsz_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, FreeAsync_ptsz_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemPoolTrimTo_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemPoolTrimTo_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemPoolSetAttribute_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemPoolSetAttribute_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemPoolGetAttribute_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemPoolGetAttribute_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemPoolSetAccess_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemPoolSetAccess_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaArrayGetPlane_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, ArrayGetPlane_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemPoolGetAccess_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemPoolGetAccess_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemPoolCreate_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemPoolCreate_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemPoolDestroy_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemPoolDestroy_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceSetMemPool_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceSetMemPool_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetMemPool_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceGetMemPool_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemPoolExportToShareableHandle_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemPoolExportToShareableHandle_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemPoolImportFromShareableHandle_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 MemPoolImportFromShareableHandle_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemPoolExportPointer_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemPoolExportPointer_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemPoolImportPointer_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemPoolImportPointer_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMallocFromPoolAsync_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MallocFromPoolAsync_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMallocFromPoolAsync_ptsz_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MallocFromPoolAsync_ptsz_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaSignalExternalSemaphoresAsync_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, SignalExternalSemaphoresAsync_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaSignalExternalSemaphoresAsync_ptsz_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 SignalExternalSemaphoresAsync_ptsz_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaWaitExternalSemaphoresAsync_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, WaitExternalSemaphoresAsync_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaWaitExternalSemaphoresAsync_ptsz_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 WaitExternalSemaphoresAsync_ptsz_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddExternalSemaphoresSignalNode_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GraphAddExternalSemaphoresSignalNode_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExternalSemaphoresSignalNodeGetParams_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GraphExternalSemaphoresSignalNodeGetParams_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExternalSemaphoresSignalNodeSetParams_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GraphExternalSemaphoresSignalNodeSetParams_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddExternalSemaphoresWaitNode_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GraphAddExternalSemaphoresWaitNode_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExternalSemaphoresWaitNodeGetParams_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GraphExternalSemaphoresWaitNodeGetParams_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExternalSemaphoresWaitNodeSetParams_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GraphExternalSemaphoresWaitNodeSetParams_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExecExternalSemaphoresSignalNodeSetParams_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GraphExecExternalSemaphoresSignalNodeSetParams_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExecExternalSemaphoresWaitNodeSetParams_v11020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GraphExecExternalSemaphoresWaitNodeSetParams_v11020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceFlushGPUDirectRDMAWrites_v11030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceFlushGPUDirectRDMAWrites_v11030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetDriverEntryPoint_v11030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetDriverEntryPoint_v11030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetDriverEntryPoint_ptsz_v11030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetDriverEntryPoint_ptsz_v11030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphDebugDotPrint_v11030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphDebugDotPrint_v11030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetCaptureInfo_v2_v11030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamGetCaptureInfo_v2_v11030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetCaptureInfo_v2_ptsz_v11030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamGetCaptureInfo_v2_ptsz_v11030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamUpdateCaptureDependencies_v11030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 StreamUpdateCaptureDependencies_v11030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamUpdateCaptureDependencies_ptsz_v11030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 StreamUpdateCaptureDependencies_ptsz_v11030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaUserObjectCreate_v11030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, UserObjectCreate_v11030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaUserObjectRetain_v11030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, UserObjectRetain_v11030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaUserObjectRelease_v11030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, UserObjectRelease_v11030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphRetainUserObject_v11030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphRetainUserObject_v11030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphReleaseUserObject_v11030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphReleaseUserObject_v11030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphInstantiateWithFlags_v11040 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphInstantiateWithFlags_v11040)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddMemAllocNode_v11040 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphAddMemAllocNode_v11040)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphMemAllocNodeGetParams_v11040 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphMemAllocNodeGetParams_v11040)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddMemFreeNode_v11040 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphAddMemFreeNode_v11040)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphMemFreeNodeGetParams_v11040 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphMemFreeNodeGetParams_v11040)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGraphMemTrim_v11040 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceGraphMemTrim_v11040)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetGraphMemAttribute_v11040 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceGetGraphMemAttribute_v11040)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceSetGraphMemAttribute_v11040 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceSetGraphMemAttribute_v11040)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphNodeSetEnabled_v11060 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphNodeSetEnabled_v11060)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphNodeGetEnabled_v11060 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphNodeGetEnabled_v11060)
#define CUPTI_RUNTIME_TRACE_CBID_cudaArrayGetMemoryRequirements_v11060 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, ArrayGetMemoryRequirements_v11060)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMipmappedArrayGetMemoryRequirements_v11060 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 MipmappedArrayGetMemoryRequirements_v11060)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLaunchKernelExC_v11060 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LaunchKernelExC_v11060)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLaunchKernelExC_ptsz_v11060 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LaunchKernelExC_ptsz_v11060)
#define CUPTI_RUNTIME_TRACE_CBID_cudaOccupancyMaxPotentialClusterSize_v11070 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 OccupancyMaxPotentialClusterSize_v11070)
#define CUPTI_RUNTIME_TRACE_CBID_cudaOccupancyMaxActiveClusters_v11070 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, OccupancyMaxActiveClusters_v11070)
#define CUPTI_RUNTIME_TRACE_CBID_cudaCreateTextureObject_v2_v11080 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, CreateTextureObject_v2_v11080)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetTextureObjectTextureDesc_v2_v11080 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetTextureObjectTextureDesc_v2_v11080)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphInstantiateWithParams_v12000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphInstantiateWithParams_v12000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphInstantiateWithParams_ptsz_v12000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GraphInstantiateWithParams_ptsz_v12000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExecGetFlags_v12000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphExecGetFlags_v12000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetKernel_v12000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetKernel_v12000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetDeviceProperties_v12000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetDeviceProperties_v12000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetId_v12000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamGetId_v12000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetId_ptsz_v12000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamGetId_ptsz_v12000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphInstantiate_v12000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphInstantiate_v12000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaInitDevice_v12000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, InitDevice_v12000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddNode_v12020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphAddNode_v12020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphNodeSetParams_v12020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphNodeSetParams_v12020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphExecNodeSetParams_v12020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphExecNodeSetParams_v12020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemAdvise_v12020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemAdvise_v12020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemPrefetchAsync_v12020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemPrefetchAsync_v12020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemPrefetchAsync_ptsz_v12020 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemPrefetchAsync_ptsz_v12020)
#define CUPTI_RUNTIME_TRACE_CBID_cudaFuncGetName_v12030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, FuncGetName_v12030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamBeginCaptureToGraph_v12030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamBeginCaptureToGraph_v12030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamBeginCaptureToGraph_ptsz_v12030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamBeginCaptureToGraph_ptsz_v12030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphConditionalHandleCreate_v12030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphConditionalHandleCreate_v12030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphGetEdges_v12030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphGetEdges_v12030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphNodeGetDependencies_v12030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphNodeGetDependencies_v12030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphNodeGetDependentNodes_v12030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphNodeGetDependentNodes_v12030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddDependencies_v12030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphAddDependencies_v12030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphRemoveDependencies_v12030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphRemoveDependencies_v12030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGraphAddNode_v12030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GraphAddNode_v12030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetCaptureInfo_v12030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamGetCaptureInfo_v12030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetCaptureInfo_ptsz_v12030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamGetCaptureInfo_ptsz_v12030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamUpdateCaptureDependencies_v12030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 StreamUpdateCaptureDependencies_v12030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamUpdateCaptureDependencies_ptsz_v12030 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 StreamUpdateCaptureDependencies_ptsz_v12030)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceRegisterAsyncNotification_v12040 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 DeviceRegisterAsyncNotification_v12040)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceUnregisterAsyncNotification_v12040 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 DeviceUnregisterAsyncNotification_v12040)
#define CUPTI_RUNTIME_TRACE_CBID_cudaFuncGetParamInfo_v12040 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, FuncGetParamInfo_v12040)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetDriverEntryPointByVersion_v12050 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetDriverEntryPointByVersion_v12050)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetDriverEntryPointByVersion_ptsz_v12050 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 GetDriverEntryPointByVersion_ptsz_v12050)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLibraryLoadData_v12060 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LibraryLoadData_v12060)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLibraryLoadFromFile_v12060 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LibraryLoadFromFile_v12060)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLibraryUnload_v12060 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LibraryUnload_v12060)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLibraryGetKernel_v12060 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LibraryGetKernel_v12060)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLibraryGetGlobal_v12060 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LibraryGetGlobal_v12060)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLibraryGetManaged_v12060 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LibraryGetManaged_v12060)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLibraryGetUnifiedFunction_v12060 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LibraryGetUnifiedFunction_v12060)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLibraryGetKernelCount_v12060 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LibraryGetKernelCount_v12060)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLibraryEnumerateKernels_v12060 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LibraryEnumerateKernels_v12060)
#define CUPTI_RUNTIME_TRACE_CBID_cudaKernelSetAttributeForDevice_v12060 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, KernelSetAttributeForDevice_v12060)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetDevice_v12080 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamGetDevice_v12080)
#define CUPTI_RUNTIME_TRACE_CBID_cudaStreamGetDevice_ptsz_v12080 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, StreamGetDevice_ptsz_v12080)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyBatchAsync_v12080 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyBatchAsync_v12080)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyBatchAsync_ptsz_v12080 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyBatchAsync_ptsz_v12080)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3DBatchAsync_v12080 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy3DBatchAsync_v12080)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3DBatchAsync_ptsz_v12080 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy3DBatchAsync_ptsz_v12080)
#define CUPTI_RUNTIME_TRACE_CBID_cudaEventElapsedTime_v12080 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, EventElapsedTime_v12080)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemPrefetchBatchAsync_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemPrefetchBatchAsync_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemPrefetchBatchAsync_ptsz_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemPrefetchBatchAsync_ptsz_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemDiscardBatchAsync_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemDiscardBatchAsync_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemDiscardBatchAsync_ptsz_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemDiscardBatchAsync_ptsz_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemDiscardAndPrefetchBatchAsync_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 MemDiscardAndPrefetchBatchAsync_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemDiscardAndPrefetchBatchAsync_ptsz_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 MemDiscardAndPrefetchBatchAsync_ptsz_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaGetExportTable_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, GetExportTable_v13000)
#define CUPTI_RUNTIME_TRACE_CBID___cudaRegisterFatBinary_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID___, RegisterFatBinary_v13000)
#define CUPTI_RUNTIME_TRACE_CBID___cudaRegisterFatBinaryEnd_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID___, RegisterFatBinaryEnd_v13000)
#define CUPTI_RUNTIME_TRACE_CBID___cudaUnregisterFatBinary_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID___, UnregisterFatBinary_v13000)
#define CUPTI_RUNTIME_TRACE_CBID___cudaRegisterVar_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID___, RegisterVar_v13000)
#define CUPTI_RUNTIME_TRACE_CBID___cudaRegisterHostVar_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID___, RegisterHostVar_v13000)
#define CUPTI_RUNTIME_TRACE_CBID___cudaRegisterFunction_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID___, RegisterFunction_v13000)
#define CUPTI_RUNTIME_TRACE_CBID___cudaRegisterManagedVar_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID___, RegisterManagedVar_v13000)
#define CUPTI_RUNTIME_TRACE_CBID___cudaInitModule_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID___, InitModule_v13000)
#define CUPTI_RUNTIME_TRACE_CBID___cudaPushCallConfiguration_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID___, PushCallConfiguration_v13000)
#define CUPTI_RUNTIME_TRACE_CBID___cudaPopCallConfiguration_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID___, PopCallConfiguration_v13000)
#define CUPTI_RUNTIME_TRACE_CBID___cudaGetKernel_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID___, GetKernel_v13000)
#define CUPTI_RUNTIME_TRACE_CBID___cudaLaunchKernel_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID___, LaunchKernel_v13000)
#define CUPTI_RUNTIME_TRACE_CBID___cudaLaunchKernel_ptsz_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID___, LaunchKernel_ptsz_v13000)
#define CUPTI_RUNTIME_TRACE_CBID___cudaRegisterUnifiedTable_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID___, RegisterUnifiedTable_v13000)
#define CUPTI_RUNTIME_TRACE_CBID___cudaGetProcAddress_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID___, GetProcAddress_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyBatchAsync_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyBatchAsync_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpyBatchAsync_ptsz_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemcpyBatchAsync_ptsz_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3DBatchAsync_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy3DBatchAsync_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemcpy3DBatchAsync_ptsz_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, Memcpy3DBatchAsync_ptsz_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLogsRegisterCallback_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LogsRegisterCallback_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLogsUnregisterCallback_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LogsUnregisterCallback_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLogsCurrent_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LogsCurrent_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLogsDumpToFile_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LogsDumpToFile_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaLogsDumpToMemory_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, LogsDumpToMemory_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemGetDefaultMemPool_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemGetDefaultMemPool_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemGetMemPool_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemGetMemPool_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaMemSetMemPool_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, MemSetMemPool_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetHostAtomicCapabilities_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, \
		 DeviceGetHostAtomicCapabilities_v13000)
#define CUPTI_RUNTIME_TRACE_CBID_cudaDeviceGetP2PAtomicCapabilities_v13000 \
	CUXcudaX(PTI_RUNTIME_TRACE_CBID_, DeviceGetP2PAtomicCapabilities_v13000)

#endif
