// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
/* Copyright (C) 2025-2026 Rong Tao */
/**
 * refs
 * - https://docs.nvidia.com/cuda/curand/group__HOST.html
 */
#ifndef __CUDA_ADAPTER_RAND_H
#define __CUDA_ADAPTER_RAND_H 1

#ifdef CURAND_H_
#error "CudaAdapter not allow include origin CUDA curand.h"
#endif

#include "wrapper_defs.h"

#define curandStatus_t cuX(randStatus_t)
#define CURAND_STATUS_SUCCESS CUX(RAND_STATUS_SUCCESS)
#define CURAND_STATUS_SUCCESS CUX(RAND_STATUS_SUCCESS)
#define CURAND_STATUS_VERSION_MISMATCH CUX(RAND_STATUS_VERSION_MISMATCH)
#define CURAND_STATUS_NOT_INITIALIZED CUX(RAND_STATUS_NOT_INITIALIZED)
#define CURAND_STATUS_ALLOCATION_FAILED CUX(RAND_STATUS_ALLOCATION_FAILED)
#define CURAND_STATUS_TYPE_ERROR CUX(RAND_STATUS_TYPE_ERROR)
#define CURAND_STATUS_OUT_OF_RANGE CUX(RAND_STATUS_OUT_OF_RANGE)
#define CURAND_STATUS_LENGTH_NOT_MULTIPLE CUX(RAND_STATUS_LENGTH_NOT_MULTIPLE)
#define CURAND_STATUS_DOUBLE_PRECISION_REQUIRED \
	CUX(RAND_STATUS_DOUBLE_PRECISION_REQUIRED)
#define CURAND_STATUS_LAUNCH_FAILURE CUX(RAND_STATUS_LAUNCH_FAILURE)
#define CURAND_STATUS_PREEXISTING_FAILURE CUX(RAND_STATUS_PREEXISTING_FAILURE)
#define CURAND_STATUS_INITIALIZATION_FAILED \
	CUX(RAND_STATUS_INITIALIZATION_FAILED)
#define CURAND_STATUS_ARCH_MISMATCH CUX(RAND_STATUS_ARCH_MISMATCH)
#define CURAND_STATUS_INTERNAL_ERROR CUX(RAND_STATUS_INTERNAL_ERROR)
#define CURAND_STATUS_NOT_IMPLEMENTED CUX(RAND_STATUS_NOT_IMPLEMENTED)

#define curandGetVersion(version) cuX(randGetVersion(version))

#ifdef __USE_HPCC__
# include <hcrand/hcrand.h>
#elif defined(__USE_LUCA__)
# include <lcrand/lcrand.h>
#elif defined(__USE_HIP__)
# include <hiprand/hiprand.h>
#endif

#endif
