// SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause)
/* Copyright (C) 2025-2026 Rong Tao */
/******************************************************************************\
 *             Solver: LAPACK-marshalling library                             *
\******************************************************************************/
#ifndef __CUDA_ADAPTER_SOLVER_COMMON_H
#define __CUDA_ADAPTER_SOLVER_COMMON_H 1

#ifdef CUSOLVER_COMMON_H_
#error "CudaAdapter not allow include origin CUDA cusolver_common.h"
#endif

#include "wrapper_defs.h"

#define cusolverStatus_t nvX(solverStatus_t)
#define CUSOLVER_STATUS_SUCCESS CUX(SOLVER_STATUS_SUCCESS)
#define CUSOLVER_STATUS_NOT_INITIALIZED CUX(SOLVER_STATUS_NOT_INITIALIZED) /*1*/
#define CUSOLVER_STATUS_ALLOC_FAILED CUX(SOLVER_STATUS_ALLOC_FAILED)
#define CUSOLVER_STATUS_INVALID_VALUE CUX(SOLVER_STATUS_INVALID_VALUE)
#define CUSOLVER_STATUS_ARCH_MISMATCH CUX(SOLVER_STATUS_ARCH_MISMATCH)
#define CUSOLVER_STATUS_MAPPING_ERROR CUX(SOLVER_STATUS_MAPPING_ERROR)
#define CUSOLVER_STATUS_EXECUTION_FAILED CUX(SOLVER_STATUS_EXECUTION_FAILED)
#define CUSOLVER_STATUS_INTERNAL_ERROR CUX(SOLVER_STATUS_INTERNAL_ERROR)
#define CUSOLVER_STATUS_MATRIX_TYPE_NOT_SUPPORTED \
	CUX(SOLVER_STATUS_MATRIX_TYPE_NOT_SUPPORTED)
#define CUSOLVER_STATUS_NOT_SUPPORTED CUX(SOLVER_STATUS_NOT_SUPPORTED) /*9*/
#define CUSOLVER_STATUS_ZERO_PIVOT CUX(SOLVER_STATUS_ZERO_PIVOT)
#define CUSOLVER_STATUS_INVALID_LICENSE CUX(SOLVER_STATUS_INVALID_LICENSE)
#define CUSOLVER_STATUS_IRS_PARAMS_NOT_INITIALIZED \
	CUX(SOLVER_STATUS_IRS_PARAMS_NOT_INITIALIZED)
#define CUSOLVER_STATUS_IRS_PARAMS_INVALID \
	CUX(SOLVER_STATUS_IRS_PARAMS_INVALID)
#define CUSOLVER_STATUS_IRS_PARAMS_INVALID_PREC \
	CUX(SOLVER_STATUS_IRS_PARAMS_INVALID_PREC)
#define CUSOLVER_STATUS_IRS_PARAMS_INVALID_REFINE \
	CUX(SOLVER_STATUS_IRS_PARAMS_INVALID_REFINE)
#define CUSOLVER_STATUS_IRS_PARAMS_INVALID_MAXITER \
	CUX(SOLVER_STATUS_IRS_PARAMS_INVALID_MAXITER)
#define CUSOLVER_STATUS_IRS_INTERNAL_ERROR \
	CUX(SOLVER_STATUS_IRS_INTERNAL_ERROR)
#define CUSOLVER_STATUS_IRS_NOT_SUPPORTED CUX(SOLVER_STATUS_IRS_NOT_SUPPORTED)
#define CUSOLVER_STATUS_IRS_OUT_OF_RANGE CUX(SOLVER_STATUS_IRS_OUT_OF_RANGE)
#define CUSOLVER_STATUS_IRS_NRHS_NOT_SUPPORTED_FOR_REFINE_GMRES \
	CUX(SOLVER_STATUS_IRS_NRHS_NOT_SUPPORTED_FOR_REFINE_GMRES)
#define CUSOLVER_STATUS_IRS_INFOS_NOT_INITIALIZED \
	CUX(SOLVER_STATUS_IRS_INFOS_NOT_INITIALIZED)
#define CUSOLVER_STATUS_IRS_INFOS_NOT_DESTROYED \
	CUX(SOLVER_STATUS_IRS_INFOS_NOT_DESTROYED)
#define CUSOLVER_STATUS_IRS_MATRIX_SINGULAR \
	CUX(SOLVER_STATUS_IRS_MATRIX_SINGULAR)
#define CUSOLVER_STATUS_INVALID_WORKSPACE CUX(SOLVER_STATUS_INVALID_WORKSPACE)

/**
 * cusolverStatus_t cusolverGetVersion(int *version);
 */
#define cusolverGetVersion(v) nvX(solverGetVersion(v))

#ifdef __USE_HPCC__
# include <hcsolver/hcsolver_common.h>
#elif defined(__USE_LUCA__)
# include <lcsolver/lcsolver_common.h>
#elif defined(__USE_HIP__)
# include <hipsolver/hipsolver.h>
#endif

#endif
