subdir-y := cmake
subdir-y += criu
subdir-y += code-formatter
subdir-y += fstabd
subdir-y += libguestfs
subdir-y += libosinfo
subdir-y += ostree
subdir-y += perf
subdir-y += podman
subdir-y += psmisc
subdir-y += vim
include main.mk
