TARGETS :=
TARGETS += getmntent getmntent_r
TARGETS += setmntent

CC := gcc

CFLAGS := -Werror -Wall -D_GNU_SOURCE

include ../../template/main.mk

getmntent: getmntent.o
getmntent_r: getmntent_r.o
setmntent: setmntent.o
