target-y := getauxval
target-y += AT_ENTRY
target-y += AT_EXECFN
target-y += AT_HWCAP
target-y += AT_PAGESZ
target-y += AT_PHDR
target-y += AT_PLATFORM
target-y += AT_SYSINFO
target-y += AT_SYSINFO_EHDR

LDFLAGS := -lm

include main.mk
