subdir-y := tcg/samples/
subdir-y += qcow2

target-shell-y += libqemu_examples.sh
target-shell-y += qemu-vm.sh
target-shell-y += support-cpu.sh
target-shell-y += support-machine.sh
target-shell-y += version.sh

include main.mk
