targets :=
targets += htonl
targets += htons
targets += ntohl
targets += ntohs
targets += inet_ntoa
targets += inet_ntop
targets += inet_pton
targets += inet_aton
targets += inet_addr
targets += inet_network

CFLAGS :=
CFLAGS += -pthread

include ../../../template/main.mk

htonl: htonl.o
htons: htons.o
ntohl: ntohl.o
ntohs: ntohs.o
inet_ntoa: inet_ntoa.o
inet_pton: inet_pton.o
inet_ntop: inet_ntop.o
inet_aton: inet_aton.o
inet_addr: inet_addr.o
inet_network: inet_network.o
