# Test-Linux CI on github
name: CI

on: [push, pull_request]

permissions:
  contents: write

jobs:
  test_linux:
    runs-on: ubuntu-latest
    env:
      BASH_ENV: ~/.bashrc
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt install -y git make sudo
    - name: Test-Linux Config
      run: |
        make gitconfig
        sudo make install
    - name: Test-Linux Info
      run: |
        ls -al ~/
        make help
        make version
