# Test-Linux CI on github
name: CI

on: [push, pull_request]

permissions:
  contents: write

jobs:
  clang-format:
    name: Run clang-format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt install -y clang-format
    - name: Clang Format
      run: scripts/clang-format.sh

  test-linux:
    name: Run test
    runs-on: ubuntu-latest
    env:
      MAKE: scripts/make_tl.sh
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt install -y git make sudo
    - name: Test-Linux Config
      run: |
        sudo make install
    - name: Test-Linux Info
      run: |
        $MAKE help
    - name: Test-Linux Install Depends
      run: |
        $MAKE deps
    - name: Test-Linux Compile C
      run: |
        $MAKE $(realpath .)/c.build
