# Test-Linux Docs on github
name: Docs

on:
  push:
    paths:
      - 'Documentation/**'
      - .github/workflows/docs.yml
  pull_request:
    paths:
      - 'Documentation/**'
      - .github/workflows/docs.yml

permissions:
  contents: write

jobs:
  documentation:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install sphinx
      run: |
        pip install -r Documentation/requirements.txt
    - name: Sphinx build
      run: |
        sphinx-build -M html Documentation Documentation/build
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Documentation/build/html
        publish_branch: gh-pages
        force_orphan: true
