# SPDX-License-Identifier: GPL-3.0
subdir-y := binutils
subdir-y += gcc
subdir-y += gdb
subdir-y += glibc
subdir-y += gnupg
subdir-y += make

target-y := __GNUC__

include main.mk

__GNUC__: __GNUC__.o
