# SPDX-License-Identifier: GPL-3.0
subdir-y :=
subdir-y += icmpping

target-y :=
target-y += ping
target-y += icmp_checksum

include ../../template/main.mk

ping: ping.o
icmp_checksum: icmp_checksum.o
